hashicorp/waypoint

website/content/docs/lifecycle/build.mdx
Fixes a small type in the lifecycle docs
=> Fix Scenario Typo

website/content/docs/getting-started.mdx, website/content/docs/troubleshooting.mdx
This step may be needed to install the server to Docker.
=> Mention docker pull hashicorp/waypoint

website/content/docs/automating-execution/github-actions.mdx
This is already discussed in the README of the action but wanted to get it on the site as well.
=> website: mark the action-waypoint action as experimental

website/pages/home/index.jsx
Fix incorrect spelling of Jenkins.
=> website: Fix typo on homepage

website/content/docs/extending-waypoint/creating-plugins/compiling.mdx, website/content/docs/extending-waypoint/creating-plugins/example-application.mdx, website/content/docs/extending-waypoint/creating-plugins/main.mdx, website/content/docs/extending-waypoint/creating-plugins/testing.mdx, website/content/docs/extending-waypoint/plugin-interfaces/authenticator.mdx, website/content/docs/extending-waypoint/plugin-interfaces/builder.mdx, website/content/docs/extending-waypoint/plugin-interfaces/configurable-notify.mdx, website/content/docs/extending-waypoint/plugin-interfaces/configurable.mdx, website/content/docs/extending-waypoint/plugin-interfaces/default-parameters.mdx, website/content/docs/extending-waypoint/plugin-interfaces/destroy.mdx, website/content/docs/extending-waypoint/plugin-interfaces/platform.mdx, website/content/docs/extending-waypoint/plugin-interfaces/registry.mdx, website/content/docs/extending-waypoint/plugin-interfaces/release-manager.mdx
This PR adds links to https://pkg.go.dev/github.com/hashicorp/waypoint-plugin-sdk for the Extending Waypoint plugin documentation.
=> B add docs links

website/pages/commands/[[...page]].jsx, website/pages/docs/[[...page]].jsx, website/pages/plugins/[[...page]].jsx
=> Fix "edit this page" documentation link

website/.env.production
this will allow us to skip the deployment approval of forked PRs
=> website: move HASHI_ENV into .env.production

website/content/docs/getting-started.mdx
=> Fix typo on getting-started.mdx

website/content/docs/automating-execution/circle-ci.mdx
=> website: replace internal beta release urls

website/pages/home/index.jsx
Always good to upgrade to new versions, even if its fake terminal output lol
=> Use latest puma/ruby in demo Terminal

internal/cli/config_get.go, internal/cli/config_set.go
=> internal/cli: config commands should reuse main -app flag

internal/cli/main.go
=> Fix index out of range error in autocomplete

builtin/docker/pull/builder.go
=> builtin/docker-pull: support registry auth from docker config files

internal/cli/install.go
=> internal/cli: show https:// on ui address on install

website/pages/home/index.jsx
DRYing up these spinners.
Thank you @drnic for your code review & feedback 🙇
=> DRY up the Spinners & Loaders

.github/CONTRIBUTING.md
Follow-up on #535, recommending including some details about the browser and version of browser, as well as extensions.
=> update contributing to mention UI related issues

website/pages/downloads/index.jsx
Hastily pulled out our releases fetching to happen at build time without much thought.  This PR is a simplified version here, which only needs to send one request.
=> Simplify our releases requests into a single request

internal/cli/install.go
The K8s installation code checks if the K8s Load Balancer has an external IP address then proceeds to connect via gRPC to bootstrap the server.  In some K8s environments the load balancer gets an external IP long before the pod is ready to accept connections.
For example, pods in EKS consistently took 30 seconds or more to start after the service already had an external IP. This is due to the overhead of EBS volume provisioning to satisfy the persistent volume claim.
I've added additional checks so we can ensure everything is ready before attempting connection:
* verify the Statefulset and all its replicas are ready
* check the service for container endpoints to ensure routing is ready
* simple HTTP connection test to ensure we reach the pod.
Fixes #431.
=> install/k8s: add statefulset and endpoint test

builtin/aws/ecs/platform.go
=> aws-ecs: fix `cpu` parameter for EC2 launch type 

builtin/README.md, website/README.md
Fixed typos in the document.
Would study waypoint and try to some more meaningful contributions.
=> Fixed some typos

website/content/docs/extending-waypoint/creating-plugins/compiling.mdx, website/content/docs/extending-waypoint/creating-plugins/testing.mdx, website/content/docs/plugins.mdx
This clarifies some parts of plugin installation and adds a section
dedicated to plugin installation troubleshooting.
Ping @nicholasjackson for notice but will merge this ASAP. Let me know if you want any edits after the fact.
=> website: troubleshooting plugin installation

website/content/docs/lifecycle/build.mdx
A user on the forums pointed out that [they wasted a long time trying to figure out the private registry](https://discuss.hashicorp.com/t/digitalocean-kubernetes-waypoint/16120/6?u=jbayer). These docs that should help.
=> Added private registry docs

.github/CONTRIBUTING.md
fix bug and enhancement links to help developers see the issues faster.
=> Update CONTRIBUTING.md to reflect correct labels

builtin/aws/ec2/platform.go, builtin/aws/ecr/registry.go, builtin/aws/ecs/releaser.go, builtin/docker/platform.go, builtin/k8s/k8s.go, builtin/k8s/releaser.go, builtin/netlify/platform.go
This PR fixes some godoc in the plugins that was copy pasted when created.
=> Fix plugin godoc copy paste

internal/cli/main.go
=> fix(cli): application configuration url

builtin/google/cloudrun/platform.go
=> builtin/google/cloudrun: nil check block configs

website/content/docs/automating-execution/jenkins.mdx
- I found some typo in docs while reading docs :)
=> Fix typo in docs

website/content/docs/extending-waypoint/index.mdx
Awesome project, sorry for nitpicking but it immediately jumps to attention when reading docs 😂
=> Improve sentence flow in docs

internal/cli/install.go
Fixes (partially) #527 
This uses a heuristic on `waypoint install` to detect Kind clusters and notes to the user that it must be setup with LoadBalancer support which it does not have out of the box nor is it trivial to setup. This will surprise users less when their installs hang.
We should update the docs too but I think this is useful to have in the CLI.
=> install/k8s: detect kind and show warning about additional requirements

internal/ceb/url.go, internal/server/singleprocess/service_entrypoint.go, internal/server/singleprocess/service_hostname.go
This will let us debug connections better.
=> internal/server: send instance ID as hzn label

website/content/docs/lifecycle/build.mdx, website/content/docs/lifecycle/deploy.mdx
Based on [this report in the forum](https://discuss.hashicorp.com/t/if-you-look-for-private-docker-usage/16175), I created a PR to improve the private registry documentation.
=> Improved private registry docs

builtin/nomad/platform.go
=> Add auth property for pulling docker image from private registry #646

website/content/docs/upgrading/index.mdx
Provide a notice that `waypoint install` does not have upgrade support.
=> Add upgrade docs notice

builtin/docker/builder.go
Resolves https://github.com/hashicorp/waypoint/issues/610
=> builtin/docker: Remove intermediate containers on build

builtin/docker/builder.go
I am not sure how to generate the plugin docs to see that I did this correctly, but I was able to validate that the build completes successfully.
=> Add dockerfile docs

builtin/nomad/platform.go
This PR extends what was done in #647 by using a typed block for auth configuration instead of a map.
I also noticed that the datacenter is documented to default to `dc1` but currently does not, so I slipped in a fix for that as well.
=> builtin/nomad: use block for auth config and default datacenter to 'dc1'

internal/serverinstall/docker.go
During `waypoint install` to Docker, this will pull the image if it
doesn't exist.
=> internal/serverinstall: for docker, download server image if it doesn't exist

website/content/docs/server/run/production.mdx
This is just about a typo: Toplogy -> Topology 👍
=> Fix typo: production.mdx

website/package-lock.json, website/package.json
Fixes a typo with the label for macOS.
=> Upgrade ProductDownloader

website/content/docs/extending-waypoint/creating-plugins/configuration.mdx
I _think_ this is what is intended here from context.
=> Fix plugin guide example

website/content/partials/components/platform-aws-ecs.mdx
=> update vars for ecs deploy

builtin/google/cloudrun/platform.go, builtin/google/cloudrun/validation.go, builtin/google/cloudrun/validation_test.go
https://cloud.google.com/artifact-registry/docs/docker/quickstart
=> Fix waypoint to work with Artifact Registry

builtin/aws/ecs/platform.go
The `execution_role_name` is optional, but this is a required parameter, so is automatically created if it's left blank.
Setting `task_role_name` should also be optional, but since this is not required it isn't created automatically, and should not be referenced in the task definition if it's not set.
Fixes issue: https://github.com/hashicorp/waypoint/issues/790
=> Fix ECS task role name bug (issue #790)

website/content/docs/automating-execution/circle-ci.mdx
This is for the Waypoint orb, which aims to simplify configurations.
https://github.com/CircleCI-Public/waypoint-orb
=> Utilise waypoint orb when using CircleCI

internal/cli/config_source_get.go, internal/cli/config_source_set.go, internal/cli/main.go
Fairly simple/boilerplate PR with the CLI for setting the dynamic source config building on top of #844
=> config sync: CLI for setting/reading config source config

ui/lib/waypoint-client/ServerServiceClientPb.ts, ui/lib/waypoint-pb/server_pb.d.ts, ui/lib/waypoint-pb/server_pb.js
Just gets the UI clients up to the `main` server definitions.
=> ui: bump to latest version of ts/js clients

website/content/docs/waypoint-hcl/functions/template.mdx, website/content/docs/waypoint-hcl/index.mdx, website/content/docs/waypoint-hcl/syntax/expressions.mdx, website/content/docs/waypoint-hcl/syntax/index.mdx, website/content/docs/waypoint-hcl/syntax/json.mdx, website/data/docs-navigation.js
=> website: waypoint.hcl syntax reference

Makefile, README.md, go.mod, go.sum, tools/tools.go
This commit adds a simple go file to install some required dependencies
for building Waypoint.
=> tools: Add tools.go for bootstrapping local dev to build waypoint 

website/content/docs/intro/index.mdx
=> Fix grammar typo in intro

builtin/aws/ssm/config_sourcer.go, builtin/aws/ssm/ssm.go, go.mod, go.sum, internal/ceb/ceb.go, internal/plugin/plugin.go, website/content/partials/components/builder-aws-ssm.mdx, website/content/partials/components/configsourcer-aws-ssm.mdx, website/content/partials/components/platform-aws-ssm.mdx, website/content/partials/components/registry-aws-ssm.mdx, website/content/partials/components/releasemanager-aws-ssm.mdx, website/content/plugins/aws-ssm.mdx, website/data/plugins-navigation.js
What the title says! Docs with example shown below:
=> AWS SSM (Parameter Store) Config Source Plugin

internal/ceb/ceb.go, internal/ceb/child_exec.go, internal/ceb/config.go, internal/ceb/log.go
The end user behavioral change here is that the log stream will begin
sending to the server as soon as EntrypointConfig is established. This
means that logs will appear even if the child command is not entering
the "ready to start case", which was happening when poorly behaved
config sources were blocking.
Internally, this  changes our state tracking in the CEB to use bools and a
condition var. Previously we were using an atomic+channel. This changes the
requirement to one shared cond var + bool per state.
We aren't using a state enum because these are not mutually exclusive
states, we can have both states true at once.
**Why now?** This is one of the pain points I noticed usertesting config
syncing end to end. If the config source is buggy it could fail to start the
app, but logs also …
=> internal/ceb: logger should connect when config is ready, not child

.circleci/config.yml, website/package-lock.json, website/package.json
A couple small trailing changes that I forgot to push to the previous PR. Sorry 😞
=> CircleCI config, dependency update

website/next.config.js
- workaround based on this current bug: https://github.com/vercel/next.js/issues/14930
=> website: add explicit match for root path header

ui/README.md
Adds instructions to run a local server build, and to generate the type definitions
=> Update UI readme 

builtin/azure/aci/platform.go, builtin/google/cloudrun/platform.go, builtin/google/cloudrun/platform_test.go
=> builtin: don't use datadir for azure and cloudrun

Makefile, internal/cli/deployment_destroy.go, internal/cli/install.go, internal/cli/main.go, internal/cli/uninstall.go, internal/serverinstall/docker.go, internal/serverinstall/k8s.go, internal/serverinstall/nomad.go, internal/serverinstall/serverinstall.go, website/content/commands/install.mdx, website/content/commands/server-config-set.mdx, website/content/commands/server-install.mdx, website/content/commands/server-restore.mdx, website/content/commands/server-snapshot.mdx, website/content/commands/server-uninstall.mdx, website/content/docs/troubleshooting.mdx
Backport of https://github.com/hashicorp/waypoint/pull/972
This includes Mitchell's refactor for `InstallOpts`.
=> Backport feature: uninstall onto release/0.2.x

ui/lib/waypoint-client/ServerServiceClientPb.ts, ui/lib/waypoint-pb/server_pb.d.ts, ui/lib/waypoint-pb/server_pb.js
This just upgrades the Waypoint clients to the latest on `main`.
=> ui: bump to latest version of clients

internal/cli/install.go, internal/serverinstall/docker.go
PR to fix cherry-pick merge conflict from https://github.com/hashicorp/waypoint/pull/1031
=> Backport of internal/install: Attempt to use default context for auth token into release/0.2.x

ui/app/components/app-item/deployment.hbs, ui/app/controllers/workspace/projects/project/app/deployments.ts, ui/app/routes/workspace/projects/project/app/deployments.ts, ui/app/styles/_app-item.scss, ui/app/styles/_page.scss, ui/app/templates/workspace/projects/project/app/deployments.hbs, ui/tests/unit/controllers/workspace/projects/project/app/deployments-test.ts
This PR addresses [issue 958](https://github.com/hashicorp/waypoint/issues/958).
=> UI: show destroyed resources

internal/cli/exec.go
Prior to this commit, the CLI would attempt to use `FindExecInstance` on
the server when searching for deployments. If the cli made a request
against an old server version, it would fail with Unimplemented. It
would also not surface this error to the user and instead just exit.
This commit fixes that by setting the deployment ID and Sequence first,
and if the server responds Unimplmenented, it simply returns early
instead of setting the Instance ID. It also displays any errors from
searching deployments in the case that we get a different error other
than unimplemeneted or ResourceExhausted.
=> cli/exec: Fail back to old search if FindExecInstance unimplemented

ui/config/targets.js
=> Drop Internet Explorer support

builtin/k8s/config_sourcer.go
Prior to this commit, we only handled configs that fit the ConfigMap
type. This commit updates that to also handle the case where we try to
receive secret configs when `secret = true` from configdynamic.
Fixes https://github.com/hashicorp/waypoint/issues/1055
=> builtin/k8s: Handle secret configs from k8s

builtin/aws/ecs/platform.go
=> builtin/aws/ecs: 856 rebase to use

builtin/k8s/platform.go
Prior to this commit, if a pod failed to pull an image, the error
wouldn't surface to the user and it would just look like the deployment
was hanging. This commit fixes that by using the `ui` to surface the
known pod failure of not being able to pull a container image.
=> builtin/k8s: Surface pod failures on deploy

internal/serverinstall/k8s.go
This commit includes a new install option for defining what storage
class name should be used for the servers persistent volume claim.
Fixes #933
=> serverinstall/k8s: Include option to define storageClassName on install

builtin/aws/alb/releaser.go, builtin/aws/ecr/registry.go, builtin/aws/lambda/platform.go, website/content/docs/lifecycle/deploy.mdx, website/content/partials/components/builder-aws-lambda.mdx, website/content/partials/components/configsourcer-aws-lambda.mdx, website/content/partials/components/platform-aws-lambda.mdx, website/content/partials/components/registry-aws-lambda.mdx, website/content/partials/components/releasemanager-aws-lambda.mdx, website/content/plugins/aws-lambda.mdx, website/data/plugins-navigation.js
Get those lambda docs out there!
=> Generate Lambda docs, add index page with example

builtin/aws/ecs/platform.go, website/content/partials/components/platform-aws-ecs.mdx
backport of https://github.com/hashicorp/waypoint/pull/1120
=> backport of plugin/aws-ecs: handle nil logging case

website/content/docs/waypoint-hcl/app.mdx
Hi All,
Feel free to throw any and all of this away.
- Adding example for using multiple app stanza.  I attempted to people can understand the concepts of multiple app stanza.
=> Update docs example for multiple app stanza

internal/server/auth.go, website/content/commands/runner-agent.mdx, website/content/docs/extending-waypoint/plugin-interfaces/index.mdx, website/content/docs/glossary.mdx, website/content/docs/internals/execution.mdx, website/content/docs/intro/index.mdx, website/content/docs/intro/vs/helm.mdx, website/content/docs/intro/vs/index.mdx, website/content/docs/roadmap.mdx, website/content/docs/waypoint-hcl/index.mdx
I've been collecting small typos over the months and figured I should push up this set now 😄
=> docs: collection of typo fixes

website/content/docs/getting-started.mdx
=> Use single-hyphen `-platform` in getting-started

internal/serverinstall/nomad.go
This adds runner management to Nomad.
=> internal/serverinstall: runner support in nomad

internal/cli/base.go, internal/cli/base_init.go, internal/cli/init.go
Backport assistant failed to find branch due to the name used. So manual backport it is.
=> Backport of Update -from-project to handle local projects #722

internal/cli/init.go, website/content/commands/init.mdx, website/content/commands/server-install.mdx, website/content/commands/server-upgrade.mdx, website/content/partials/components/builder-pack.mdx, website/content/partials/components/platform-kubernetes.mdx, website/content/partials/components/releasemanager-kubernetes.mdx, website/data/version.js
Will mark as "ready" soon when ready, but for now, this PR is in preparation for release.
=> Generate CLI and Website Docs for Release

.changelog/README.md
This pull request updates the expectation of how we expect CHANGELOG entries to be formatted for a component versus how we expect git commits to look.
=> Improve CHANGELOG Readme

.changelog/1213.txt, builtin/aws/ecs/platform.go, builtin/docker/pull/builder.go, internal/cli/app_docs.go, website/content/partials/components/builder-aws-ami.mdx, website/content/partials/components/builder-docker-pull.mdx, website/content/partials/components/builder-pack.mdx, website/content/partials/components/builder-terraform-cloud.mdx, website/content/partials/components/configsourcer-aws-ssm.mdx, website/content/partials/components/configsourcer-terraform-cloud.mdx, website/content/partials/components/configsourcer-vault.mdx, website/content/partials/components/platform-aws-ec2.mdx, website/content/partials/components/platform-aws-ecs.mdx, website/content/partials/components/platform-azure-container-instance.mdx, website/content/partials/components/platform-docker.mdx, website/content/partials/components/platform-exec.mdx, website/content/partials/components/platform-google-cloud-run.mdx, website/content/partials/components/platform-kubernetes.mdx, website/content/partials/components/platform-nomad.mdx, website/content/partials/components/platform-terraform-cloud.mdx, website/content/partials/components/registry-docker.mdx, website/content/partials/components/registry-terraform-cloud.mdx, website/content/partials/components/releasemanager-aws-alb.mdx, website/content/partials/components/releasemanager-kubernetes.mdx, website/content/partials/components/releasemanager-terraform-cloud.mdx, website/content/partials/funcs.mdx
This pulls in https://github.com/hashicorp/waypoint-plugin-sdk/pull/17 and adds the rendering for the new subfields values.
It also tries up the field rendering and makes it emit "clean" markdown by default.
=> Add ability to have nested fields in docs

.changelog/1057.txt, ui/.template-lintrc.js, ui/app/components/app-form/project-settings.hbs, ui/app/components/app-form/project-settings.ts, ui/app/router.js, ui/app/routes/workspace/projects/project/settings.ts, ui/app/styles/_pds-form.scss, ui/app/styles/_x-toggle.scss, ui/app/styles/app.scss, ui/app/templates/workspace/projects/project/apps.hbs, ui/app/templates/workspace/projects/project/settings.hbs, ui/config/environment.js, ui/package.json, ui/tests/unit/routes/workspace/projects/project/settings-test.ts, ui/translations/en-us.yaml, ui/yarn.lock
This PR adds a new settings screen for projects. 
Currently, the happy path works (with correct user input), but there is no success/error messaging, but I will add that as soon as https://github.com/hashicorp/waypoint/pull/1206 is reviewed and merged.
=> UI: git settings

.changelog/1253.txt, ui/app/components/app-form/project-settings.hbs, ui/app/components/app-form/project-settings.ts, ui/app/styles/_pds-form.scss, ui/app/templates/workspace/projects/project/settings.hbs, ui/translations/en-us.yaml
https://user-images.githubusercontent.com/1416421/113445410-2233f380-93f6-11eb-8b3e-7f6e149618ae.mp4
=> UI: hcl config input from project settings

ui/translations/en-us.yaml
Adresses #1265 by renaming the SSH key field's label
=> rename label to SSH Private Key

builtin/pack/builder.go
Pack requires a Docker daemon and we can't currently fallback to any
Dockerless solutions. This error message makes it clearer to users
earlier what is happening versus a more opaque "Docker daemon can't
connect" error that Docker provides later.
=> builtin/pack: output to user if Docker is not available

.changelog/1280.txt, ui/app/components/operation-logs/index.ts, ui/app/templates/workspace/projects/project/app/build.hbs, ui/app/templates/workspace/projects/project/app/deployment.hbs, ui/app/templates/workspace/projects/project/app/release.hbs
Fixes for https://github.com/hashicorp/waypoint/issues/1266
=> Add error message on failed builds

ui/app/components/app-card/deployment.hbs, ui/app/components/app-card/release.hbs
=> Add status badges for releases and deployments

internal/cli/config_get.go, internal/cli/config_set.go
This allows using `waypoint config` to set and read env vars for runners. 
The core functionality to enable this was done before Waypoint 0.1 (I think) but we never exposed this cause we never had runners exposed before! This exposes that functionality. I verified it works (already was unit tested in core anyways). 
This doesn't include any docs yet which I can add later.
=> internal/cli: config get/set support -runner for runner config

builtin/aws/ecr/registry.go
This modifies the aws-ecr plugin to support Dockerless builds.
=> aws/ecr: registry supports Dockerless

CHANGELOG.md
Couldn't find the consul script so I did it in vim instead:
```
%s/\[GH-\(.*\)\]/[[GH-\1](https:\/\/github.com\/hashicorp\/waypoint\/issues\/\1)]/gc
```
=> CHANGELOG: Add github URLs for each issue

.changelog/1312.txt, ui/package.json, ui/yarn.lock
Fixes https://github.com/hashicorp/waypoint/issues/1305
=> Fix hidden Checkbox being partially visible

.changelog/1106.txt, internal/serverinstall/nomad.go
This fixes the issue preventing waypoint from installing onto nomad clusters that have cred helpers on nodes.
Fixes https://github.com/hashicorp/waypoint/issues/1034
=> Auth soft fail

.changelog/1326.txt, internal/cli/uninstall.go, internal/serverinstall/nomad.go, website/content/commands/install.mdx, website/content/commands/server-install.mdx, website/content/commands/server-uninstall.mdx, website/content/commands/server-upgrade.mdx
=> Make `purge` default behavior for Nomad uninstall; remove flag

website/content/commands/index.mdx
This provides some documentation about the autocomplete install and uninstall command and how it changes the shell init script
=> add some documentation about autocomplete install and uninstall

.changelog/1373.txt, ui/app/components/log-stream/index.ts
Fixes #1362 
https://user-images.githubusercontent.com/1416421/115595728-90722480-a2d7-11eb-8b48-dd2d691e7430.mp4
=> reset count badge on scroll

.circleci/config.yml
Updated fingerprint for new ci service account
=> Updated ssh key fingerprint

.github/CONTRIBUTING.md
This PR fills in some info that will help folks onboard as contributors.
=> github/contributing: updates to onboarding docs

.changelog/1317.txt, builtin/k8s/deployment.go, builtin/k8s/platform.go
Manual backport since https://github.com/hashicorp/waypoint/pull/1421 failed from a merge conflict
=> Manual Backport of #1317 K8S Improvements

.changelog/1450.txt, go.mod, go.sum
This is to pickup https://github.com/hashicorp/waypoint-plugin-sdk/pull/28
=> Bump waypoint-plugin-sdk to pickup fix. Fixes #1377

.changelog/1461.txt, internal/cli/server_upgrade.go
=> Default the platform on upgrade to the one in the context

website/data/alert-banner.js, website/pages/_app.js
[🔍 Preview](https://waypoint-21dgdewa0-hashicorp.vercel.app/)
Adding an AlertBanner component to promote HashiConf Europe.
=> Updates banner for HashiConf EU

builtin/docker/platform.go
This commit introduces the implementation of the Status function for
docker on deploy. It queries the current deployed containers health and
looks for if it was configured using dockers built in health checks. If
not, the function attempts to make some basic assumptions for
determining the health of the container.
=> plugin/docker: Report on deploy status

ui/app/styles/_page.scss
=> UI: Fixed logo alignment on authentication screen

builtin/nomad/platform.go
This commit introduces the StatusFunc for determinig the health of a
deployed Nomad job
=> plugin/nomad: Report on deployment status

.changelog/1475.txt
https://github.com/hashicorp/waypoint/pull/1475
=> Changelog entry for PR #1475

website/content/docs/app-config/files.mdx, website/content/docs/app-config/index.mdx, website/content/docs/app-config/internal.mdx, website/content/docs/waypoint-hcl/config.mdx, website/data/docs-nav-data.json
We forgot to write the docs for this amazing feature!
=> website: document configuration files and internal values

ui/app/styles/_animations.scss, ui/app/styles/_status-badge.scss
Fixes https://github.com/hashicorp/waypoint/issues/1587 
https://user-images.githubusercontent.com/1416421/121063588-cd7e7180-c7c6-11eb-9f89-ddc5ba38a416.mov
@almonk let me know if you want to tweak the animation
=> Add animation to alive state icon

ui/app/components/app-form/project-settings.ts, ui/app/routes/workspace/projects/project/app/deployments.ts, ui/tests/acceptance/deployments-list-test.ts, ui/tests/integration/components/app-form/project-settings-test.ts
**Issue This PR is Fixing**
#1397
=> ui: Fixed git settings input field repeat bug + cleanup

.changelog/1648.txt, builtin/aws/alb/plugin.pb.go, builtin/aws/alb/plugin.proto, builtin/aws/alb/releaser.go
Similar to https://github.com/hashicorp/waypoint/pull/1528 and https://github.com/hashicorp/waypoint/pull/1477, this PR updates the ALB Releaser to use the Waypoint SDK Release Manager for creation and deletion.
Also implements #1081 and fixes #1011
=> Update ALB Releaser to use Resource Manager

website/content/commands/server-uninstall.mdx, website/content/commands/server-upgrade.mdx
This added one new flag, but also decided to give nomad top billing on the server uninstall command. I think that's fine.
=> Ran `go run ./tools/gendocs`

CHANGELOG.md
Changelog entry for 0.4.1 release
=> Update changelog for 0.4.1 release

.changelog/1828.txt, ui/app/components/app-card/release.hbs
Fixes https://github.com/hashicorp/waypoint/issues/1827
=> Fix release URL links

contrib/waypoint-local/README.md, contrib/waypoint-local/setup-waypoint-local.sh, contrib/waypoint-local/shutdown-waypoint.sh
This commit adds some simple setup and management scripts for runninng a
Waypoint server and runner locally for development purposes.
=> contrib/waypoint-local: Add setup scripts for running locally

ui/lib/waypoint-client/ServerServiceClientPb.ts, ui/lib/waypoint-pb/server_pb.d.ts, ui/lib/waypoint-pb/server_pb.js
Updates the Javascript client to include proto changes from https://github.com/hashicorp/waypoint/pull/1878
=> Generate API bindings for OIDC protos

website/content/docs/server/run/maintenance.mdx
The server maintenance page had a typo in it
=> Fix docs typo

website/content/docs/automating-execution/index.mdx, website/content/docs/runner/run-manual.mdx, website/content/docs/server/auth.mdx, website/content/docs/server/auth/oidc.mdx, website/content/docs/troubleshooting.mdx, website/data/docs-nav-data.json
Subject is self-explanatory for this one I hope!
=> OIDC Documentation

.changelog/1740.txt, .changelog/1919.txt, builtin/aws/ecs/platform.go, website/content/partials/components/platform-aws-ecs.mdx
Closes #1740
This PR adds a fixup commit to the above original PR. See that PR for more context.
=> Feature/aws ecs/additional security groups

.changelog/1941.txt, builtin/nomad/platform.go, builtin/nomad/plugin.pb.go, builtin/nomad/plugin.proto, website/content/partials/components/platform-nomad-jobspec.mdx, website/content/partials/components/platform-nomad.mdx
=> builtin/nomad: add resource manager to nomad platform

internal/server/singleprocess/auth.go, internal/server/singleprocess/auth_test.go
For now, everyone is a superuser (we have no policy system yet) so we
allow anyone to do this. However, we do want to ensure that the user
exists. This implements and tests that.
=> internal/server: invite tokens for other users are allowed

.changelog/1958.txt, builtin/google/cloudrun/deployment.go
Updating the error message per feedback in #1942
=> plugin/gcp: a bit more helpful error msg

website/content/docs/getting-started.mdx
=>  -auto-approve

.changelog/1966.txt, internal/cli/base.go, internal/cli/deployment_list.go, internal/cli/filter_status.go, internal/cli/main.go, internal/cli/option.go, internal/cli/status.go, internal/core/app_release.go, internal/server/singleprocess/service_ui_deploy.go, internal/server/singleprocess/service_ui_deploy_test.go, internal/server/singleprocess/service_ui_release.go, internal/server/singleprocess/service_ui_release_test.go, website/content/commands/status.mdx, website/data/commands-nav-data.json
This pull request introduces a new command `waypoint status`.
Fixes https://github.com/hashicorp/waypoint/issues/1501
=> feature: waypoint status CLI

internal/cli/status.go
This commit adds some extra handling for when the local CLI has no
default CLI context set. If not set, it will display a warning and
display the server address as an empty string rather than panic on
not having a CLI context to load.
=> cli/status: Handle case where CLI has no default server context loaded

internal/cli/status.go
Responding to PR feedback from @krantzinator https://github.com/hashicorp/waypoint/pull/2015#issuecomment-896150686
=> Add note about local mode

.changelog/2013.txt, internal/cli/project_apply.go, internal/server/gen/server.pb.go, internal/server/proto/server.proto, website/content/commands/project-apply.mdx
This was only possible via the UI before.
=> Adding `-git-path` flag to `waypoint project apply`

ui/app/components/app-form/project-repository-settings.hbs
Fixes https://github.com/hashicorp/waypoint/issues/1965
=> UI: Git configuration - Add help text and switch placeholder to https protocol

internal/server/singleprocess/poll_test.go
This commit fixes the occasional flakey test for turning off the
application status poll queuer. If circle-ci was under heavy load and
was slow, our requirement that a single poll job would exist would never
be satisfied due to project polling likely starting up in the test
server. This commit fixes that by only looking at jobs with the specific
singleton id when testing this functionality.
Fixes #2017
=> tests: Ensure turnoff test only looks for app status poll job by id

internal/config/variables/variables.go
I used the `tip.waypointproject.io` link and replaced `tip` with `www` so this should be a good link when all is published.
=> resolve TODO for docs link

builtin/docker/platform.go, builtin/k8s/platform.go, builtin/k8s/releaser.go, go.mod, go.sum, internal/cli/status.go
Depends on https://github.com/hashicorp/waypoint-plugin-sdk/pull/55
The new StatusReport function pushes all of this work into the plugin sdk!
=> Update docker and k8s plugins to use the new StatusReport helper func.

ARCHITECTURE.md, builtin/aws/lambda/ecs.go, builtin/docker/copy.go, internal/appconfig/option.go, internal/cli/base.go, internal/cli/exec.go, internal/cli/runner_agent.go, internal/cli/status.go, internal/client/project.go, internal/config/app_config.go, internal/config/app_config_sort.go, internal/core/operation.go, internal/pkg/copy/copy.go, internal/plugin/invoke.go, internal/runner/accept.go, internal/runner/operation_release.go, internal/server/grpc.go, internal/server/singleprocess/service_entrypoint.go, internal/server/singleprocess/service_exec.go, x/slack/pkg/bot/ui.go
Had a few minutes before a meeting, and decided to redeem myself after https://github.com/hashicorp/waypoint/pull/2049#discussion_r690423926
The apostrophe in "it's" does not denote possession, only contraction.
=> Correct usage of its and it's.

builtin/docker/builder.go, website/content/docs/projects/index.mdx, website/content/docs/projects/remote.mdx, website/content/docs/waypoint-hcl/index.mdx, website/content/docs/waypoint-hcl/runner.mdx, website/content/partials/components/builder-docker.mdx
A few things I noticed while working on other stuff.
=> docs typos and fixups

internal/cli/install.go, internal/cli/main.go, internal/cli/ondemand_runner_inspect.go, internal/server/proto/server.proto, internal/server/singleprocess/service_job.go
=> waypoint on-demand runner inspect and small copy changes

website/content/commands/release-list.mdx, website/data/commands-nav-data.json
Generated documentation for `waypoint release list` that should get added to the website.
=> docs/ui: Add documentation for `waypoint release list`

.changelog/2055.txt, internal/cli/main.go, internal/cli/project_inspect.go, internal/cliformat/format.go, website/content/commands/project-inspect.mdx, website/data/commands-nav-data.json
This PR adds a new subcommand to `waypoint project` named `inspect`.
It lists the details of the requested project, or if in a project
directory, list that projects details.
Fixes #1267
=> cli/project: Add project inspect command

.changelog/2204.txt, internal/server/singleprocess/poll_application.go
=> server/singleprocess: poll exit logic

.gitignore, .vscode/settings.json, website/.vscode/settings.json
🎟️ [Asana Task](https://app.asana.com/0/1200392284811676/1200498586643633/f)
In an attempt to make it easier when working with multiple vscode windows open at once, we have set out to customize the status bar color of each project to its theme color.
This is a preview of what it looks like:
=> Vscode Customization - Status Bar Background

.changelog/2217.txt, internal/config/variables/testdata/complex.wpvars, internal/config/variables/variables.go, internal/config/variables/variables_test.go
=> internal/config: file vars not parsing complex HCL types

.circleci/config.yml
Fixes: https://github.com/hashicorp/waypoint/issues/2260
starting with `medium+`, we'll see if that works, otherwise we could go to `large` to be sure.
=> Bump the `ember-build-tests` resource class

.circleci/config.yml
=> Increase resource memory for `ember-build-prod` step

builtin/pack/builder.go
Follow up to https://github.com/hashicorp/waypoint/pull/2323 I missed another typo
=> fix other occurence of "negoate"

internal/cli/base_init.go, internal/cli/k8s_bootstrap.go, internal/cli/main.go, website/content/commands/k8s-bootstrap.mdx, website/data/commands-nav-data.json
This introduces a `waypoint k8s bootstrap` command. This command is used by the Helm chart to bootstrap the cluster and set up all the initial secrets. This should never be executed manually by a user so it is hidden.
=> "waypoint k8s bootstrap" hidden command used by the Helm chart

internal/core/app_build.go
@evanphx this came up in discussion a few weeks back; I wasn't sure what else we should do here so we at least log a warning. Is there any recovery available here?
=> Log warnings if some things we expect to work actually don't

website/content/docs/runner/config.mdx
Runners now support dynamic config values
=> Update runner config page

.circleci/config.yml
I'll do a squash-merge on this 😄
=> Fix letsencrypt expiration

internal/cli/login.go
=> internal/cli: detect waypoint ui address that is a hostname

.changelog/1992.txt, builtin/docker/builder.go, builtin/docker/img.go, website/content/partials/components/builder-docker.mdx
Docker and Img can stop the build at the specified target stage.
If not set the full Dockerfile will be build.
Closes: #1969
=> plugin/docker: add multi-stage target config

internal/serverinstall/nomad.go
Addresses https://github.com/hashicorp/waypoint/issues/2314, but we'll need a better solution eventually.
=> Add a warning to nomad server install about ephemeral addresses.

contrib/waypoint-grpc/README.md, contrib/waypoint-grpc/waypoint-grpc.sh
Closes #2500
1. Check out the branch `git checkout contrib/waypoint-grpc`
2. Try running some commands (i.e. `./contrib/waypoint-grpc/waypoint-grpc.sh GetVersionInfo`)
3. Verify it does what you want (within reason)
=> contrib: add waypoint-grpc

.changelog/2526.txt, internal/cli/base.go
Fixes #2523
Also closes #2525; Izaak and I chatted in Slack about preferring this strategy.
=> cli: set project on cfg

builtin/aws/ecs/platform.go
Addresses the problem found in this discuss post: https://discuss.hashicorp.com/t/waypoint-issue-with-alb-subnets/31056/2
=> Better error message if no subnets are found.

.changelog/2593.txt, builtin/nomad/nomad.go, builtin/nomad/platform.go, builtin/nomad/plugin.pb.go, builtin/nomad/plugin.proto, builtin/nomad/task.go, internal/cli/install.go, internal/serverinstall/nomad.go, website/content/commands/install.mdx, website/content/commands/server-install.mdx, website/content/commands/server-upgrade.mdx, website/content/partials/components/task-nomad.mdx
This pull request introduces support for launching on-demand runner tasks with Nomad. It launches a nomad job using the ODR image to build containers. Now that StopTask is implemented, it also cleans up the nomad jobs once complete.
Fixes #2503
=> Feature: Nomad On-Demand Runner Support

website/next.config.js, website/pages/404.jsx
=> feat(404): helper text for notfound docs

Makefile, builtin/exec/platform.go, website/content/commands/index.mdx, website/content/commands/install.mdx, website/content/commands/server-uninstall.mdx, website/content/commands/server-upgrade.mdx, website/content/partials/components/platform-exec.mdx, website/content/partials/components/platform-nomad.mdx
Fixes https://www.waypointproject.io/plugins/v0.3.x/exec
=> fix(v0.3.x): platform exec mdx

test-e2e/cli_smoke.test.go, test-e2e/docker_smoke_test.go, test-e2e/e2e_test.go, test-e2e/k8s_smoke_test.go, test-e2e/nomad_smoke_test.go, test-e2e/util.go
This adds some new cli end-to-end tests. They're not hooked up to CI yet - that'll take a bit more work - but they're as useful as the other e2e tests. 
I'm about to make a PR that affects a ton of our CLI's surface area, and rather than _just_ doing a bunch of manual testing, I wrote this.
=> CLI end-to-end tests

.changelog/2645.txt, .changelog/2755.txt, .github/CHANGELOG_GUIDE.md, internal/cli/deployment_create.go
Fixes #2645
I'm new to this project so please let me know if any updates are needed.
=> Fix for empty deployUrl check in deployment_create

internal/client/job.go, internal/pkg/gitdirty/gitdirty_test.go, website/package-lock.json
This will fix the lint failures on `main`
=> rename func to new name

.circleci/config.yml
=> ci: improve `publish-static-assets` change detection

website/redirects.js
[https://waypoint-fvqfexxjv-hashicorp.vercel.app/home](https://waypoint-fvqfexxjv-hashicorp.vercel.app/home)
=> fix: redirect website `/home` to `/`

internal/client/job.go
I attempted to run a remote operation with `-local=false` before properly configuring the data source. As a result, I hit this panic:
```
$ waypoint up -local=false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x337c900]
github.com/hashicorp/waypoint/internal/client.(*Project).setupLocalJobSystem.func2(0xc00041fee0, {0x4443d10, 0xc0006f7280}, 0xc0005bb860, {0x43b84c0, 0xc000290a00})
/Users/clint/go-src/github.com/hashicorp/waypoint/internal/client/job.go:164 +0x520
```
Full log:
<details>
```
$ waypoint up -local=false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x337c900]
goroutine 1 …
```
=> Guard against a misconfigured project datasource

builtin/aws/ssm/config_sourcer.go, builtin/k8s/config_sourcer.go, builtin/null/config_sourcer.go, builtin/tfc/config_sourcer.go, builtin/vault/config_sourcer.go, internal/cli/app_docs.go, website/content/docs/app-config/dynamic.mdx, website/content/docs/app-config/internal.mdx, website/content/docs/kubernetes/config.mdx, website/content/docs/waypoint-hcl/config.mdx, website/content/docs/waypoint-hcl/functions/all.mdx, website/content/docs/waypoint-hcl/variables/dynamic.mdx, website/content/docs/waypoint-hcl/variables/input.mdx, website/content/partials/components/configsourcer-aws-ssm.mdx, website/content/partials/components/configsourcer-kubernetes.mdx, website/content/partials/components/configsourcer-terraform-cloud.mdx, website/content/partials/components/configsourcer-vault.mdx, website/data/docs-nav-data.json
This adds docs for #2889.
This uses the new `dynamic` function name which I'm opening a PR for separately now.
=> website: document dynamic variable values

internal/runner/operation_init.go, internal/runner/operation_init_test.go
This PR adds a call to `UpsertWorkspace` when executing a remote init operation (for example, from the UI). 
Note that the UI does not currently offer any option to specify the Workspace
=> Upsert Workspace with remote init operation is called

website/content/docs/upgrading/index.mdx
extra `/` made for a broken link
=> Fix broken link on upgrading page

.vscode/launch_template.json
Just a few debug profiles to get us started
=> Add `.vscode/launch_template.json`

internal/server/singleprocess/service_runner.go
Functionally, it doesn't make a difference, but practically there's no
reason to create the runner before validating the token. If the token is
invalid, it just creates more work that was unnecessary. If the token is
valid, we would've done it anyways.
=> internal/server: RunnerConfig: create runner after token validation

builtin/aws/lambda/platform.go
Sorry, this typo of allotted was bothering me in some output. Let me know if I should submit differently. Thanks.
=> Fix minor typo

ui/tests/integration/components/workspace-switcher-test.ts
Reverts hashicorp/waypoint#2985
=> Revert "Backport of ui: remove unused import into release/0.7.x"

Makefile
Minor organizing, moved new `docker/tools` & `docker/gen/server` up with the other docker commands & fixed spacing.
=> Format Makefile

website/data/commands-nav-data.json
=> Add `waypoint runner inspect` to website

internal/runner/accept.go, internal/runner/accept_test.go, internal/runner/operation_task.go
Bug 1: we were ignoring an error
But 2: we weren't propagating the token from the runner adoption flow into all the contexts we were using to make client api calls.
=> Fixing two bugs in the adopt runner flow

ui/README.md
Could definitely be better fleshed out, but wanted to PR it now so is not forgotten / is a step in the right direction.
=> Add /ui README update

website/content/commands/index.mdx, website/content/docs/kubernetes/container-build.mdx, website/content/docs/projects/remote.mdx
ref. https://github.com/hashicorp/waypoint/pull/2771
replace `-remote` flag with `-local`
=> doc: deprecate `-remote` flag

internal/client/job.go
Fixes https://github.com/hashicorp/waypoint/issues/3077
=> Fix panic when running `waypoint build` remotely outside of project directory

website/README.md, website/package-lock.json, website/package.json
Pulls in an update to our CLI, which changes how we format package-lock. Hopefully this should address the package-lock formatting woes once and for all!
=> website: fix package-lock formatting

pkg/serverstate/statetest/test_runner_ondemand.go
Was a relatively new feature that could stand a test!
=> Test reading/writing ODR target labels

pkg/serverstate/statetest/test_release.go
This is documented in the rpc definition - workspace ref can be nil, and in that case it should return the latest in any workspace.
=> Test nil workspace in latest release state req

builtin/nomad/platform.go
Fix nil pointer dereference for Consul/Vault tokens in Nomad platform deployer.
=> Fix nil pointer dereference

builtin/nomad/jobspec/platform.go, website/content/partials/components/platform-nomad-jobspec-canary.mdx, website/content/partials/components/platform-nomad-jobspec.mdx
=> Document conflict between Waypoint/Nomad entrypoint

website/package-lock.json, website/package.json
Closes https://github.com/hashicorp/waypoint/security/dependabot/75
Also ran `npm audit fix`
Closes https://github.com/hashicorp/waypoint/security/dependabot/48
=> upgrade platform-cli to resolve vuln in async version

internal/cli/deployment_create.go, website/content/commands/deploy.mdx, website/content/commands/deployment-deploy.mdx
Co-authored-by: Brian Cain <bcain@hashicorp.com>
=> Adds paragraph to 'deploy' command docs regarding '-release' flag

website/README.md
In case people were curious how to run the website locally via Docker! 🐳
=> website: Add notes on how to use the Docker flow with `make`

.github/dependabot.yml
Was failing here: https://github.com/hashicorp/waypoint/runs/6459131838
Reformatted through https://jsonformatter.org/yaml-validator
=> Fix dependabot, was missing "updates:"

.changelog/3213.txt, builtin/aws/lambda/platform.go, builtin/aws/lambda/platform_test.go, builtin/aws/lambda/plugin.proto, go.mod, website/content/partials/components/platform-aws-lambda.mdx
- feat(aws-lambda): storage
- chore: docs
Closes https://github.com/hashicorp/waypoint/issues/3194
=> feat(aws-lambda): storage

.changelog/3213.txt, builtin/aws/lambda/platform.go, builtin/aws/lambda/platform_test.go, builtin/aws/lambda/plugin.proto, go.mod, go.sum, website/content/partials/components/platform-aws-lambda.mdx
Manual backport because of merge conflicts in https://github.com/hashicorp/waypoint/pull/3363
=> Cherry pick/3213

go.mod, go.sum
Getting some checksum errors in build due to a new release for go-getter.
Updating go-getter to latest release.
=> Getting some checksum issues. Need latest release of go-getter.

website/content/docs/getting-started/index.mdx
update links to tutorials so they'll get rewritten correctly in dev-portal.
=> website: fix tutorials links

.github/CODEOWNERS
Update CODEOWNERS to set the ecosystem team as an automatic reviewer for plugin changes.
=> Update CODEOWNERS for Ecosystem

website/content/docs/extending-waypoint/plugin-interfaces/configsourcer.mdx, website/data/docs-nav-data.json
=> Docs: Add ConfigSourcer plugin interface docs for extending Waypoint

go.mod, internal/cli/main.go, internal/cli/runner_install.go, internal/cli/runner_uninstall.go, internal/installutil/aws/ecs.go, internal/installutil/k8s/k8s.go, internal/runnerinstall/docker.go, internal/runnerinstall/ecs.go, internal/runnerinstall/k8s.go, internal/runnerinstall/nomad.go, internal/serverinstall/ecs.go, internal/serverinstall/k8s.go, internal/serverinstall/serverinstall.go
This PR adds a runner uninstall implementation for kubernetes
=> Add k8s runner uninstallation

pkg/serverstate/statetest/test_deployment.go
We weren't testing this elsewhere, and it caught a bug for me.
We could also test this in all the other ops, but this is enough of an improvement for me for now.
=> Test serverstate deploy filtering

internal/cli/destroy.go, internal/cli/server_upgrade.go, internal/cli/uninstall.go, website/content/commands/destroy.mdx, website/content/commands/server-uninstall.mdx, website/content/commands/server-upgrade.mdx
We now support interactive input, so these commands' docs can be updated to reflect that.
Not including a changelog as the functional change is reflected in the changelog already.
=> update language for commands that have `auto-approve` flags

website/content/docs/runner/profiles.mdx
The Vercel deploy will fail. That update is in #3482
=> update runner profile delete docs

internal/pkg/jsonpb/decode.go, internal/pkg/jsonpb/encode.go, internal/pkg/jsonpb/json.go, pkg/serverstate/statetest/test_project.go
This tests that we're storing and retrieving most of the project settings correctly.
=> Comprehensive project set/get test

CHANGELOG.md
=> changelog 0.9.0

tools.Dockerfile
It's been a while, not sure if this works
=> Make `make docker/gen/server` work on arm macs

.changelog/3605.txt, internal/cli/base.go, internal/cli/base_init.go, internal/cli/init.go, internal/config/app_test.go, internal/config/validate.go, internal/config/validate_test.go, internal/core/project.go, internal/runner/operation.go
=> Fix the appening deprecating warning being fatal

pkg/server/singleprocess/service_project.go
@sdav9375  and I hit this error in practice (I think), and it wasn't clear where it came from! This should help in the future.
=> Improve queue init job error

.changelog/3656.txt, internal/cli/logs.go, internal/client/operation.go, website/content/commands/logs.mdx
=> Get logs for a specific deployment with `waypoint logs`

internal/serverinstall/docker.go
The length of a slice will never be negative. I believe the intent was to check for `0` here
=> Update check for existing docker server install

internal/cli/runner_install.go, internal/runnerinstall/ecs.go
=> Minor runner install fixes

internal/server/boltdbstate/ondemand_runner.go, pkg/serverhandler/handlertest/test_service_ondemand_runner.go, pkg/serverstate/statetest/test_runner_ondemand.go
Also adding more tests around runner profiles, that may cover bugs found in other state implementations.
=> Not allowing user to set runner profile IDs

docs/gen/platform-aws-ecs.json, docs/gen/platform-azure-container-instance.json, docs/gen/platform-exec.json, docs/gen/platform-google-cloud-run.json, docs/gen/task-aws-ecs.json, docs/gen/task-kubernetes.json
For whatever reason, these json docs were missing from `main`. This pr generates them.
=> docs/gen: Auto-generate platform docs for json

internal/cli/runner_install.go, website/content/commands/runner-install.mdx
=> add docs for new -- on runner install

pkg/inlinekeepalive/keepalive.go
With the old log level, if there's a problem with the server connection, we'd usually log _two_ errors - one for the currently active stream (like RunnerConfig), and also an inline keepalive error.
The keepalive error is really just noise for the user in that case, and the client failing to send a keepalive isn't something a user should generally act on, so i'm downgrading this to debug level.
I've also noticed this log-erroring sometimes on shutdown. I think it's possible for us to call SendMsg in the keepalive routine after CloseSend has been invoked elsewhere, but before the context is cancelled, which yields us a grpc Internal type error from SendMsg. We could avoid this with more mutexes, but I don't think it's worth the complexity to avoid.
=> Making keepalive send errors quieter.

internal/cli/init.go, internal/cli/pipeline_run.go, pkg/server/singleprocess/service_pipeline.go, website/content/commands/pipeline-run.mdx
This pull request introduces auto config syncing pipeline configs from a Waypoint project during the `waypoint init` CLI as well as prior to requesting a pipeline run in `waypoint pipeline run`.
Fixes #3715
=> CLI: Auto ConfigSync Pipelines

.changelog/3761.txt, internal/cli/install.go, internal/installutil/adoption.go, internal/runnerinstall/nomad.go
=> Fix error message for missing Nomad runner install persistence args

website/content/docs/runner/adoption.mdx, website/data/docs-nav-data.json
This PR adds a summary of the Runner adoption flow to the website
Closes #3336
=> docs: Add runner adoption workflow to website

internal/cli/pipeline_inspect.go
Before this commit waypoint would attempt to fetch the -1th Pipeline run if no pipelines had ran when inspecting a pipeline. This commit adds an error to the output instead of crashing.
=> bug: Show error if inspecting pipeline with no runs

pkg/serverstate/statetest/test_project.go
=> Added a test for deleting all project input vars

website/content/docs/runner/index.mdx
=> chore: fix links

CHANGELOG.md
Waypoint v0.10.1 was released today, this PR is an update to our CHANGELOG to reflect that
=> Update CHANGELOG from 0.10.1 release

pkg/server/singleprocess/service_auth_method.go
Wrap error returns in [hcerr.Externalize()](https://github.com/hashicorp/waypoint/blob/52e13de50ac6da2ffedb9c34f17f592c76de9fe1/pkg/server/hcerr/hcerr.go#L16-L29) to log more details correctly, and keep some details in logs as opposed to surfacing them to users. 
This PR builds off of #3940 and should only be merged afterwards
=> Externalize auth method

pkg/server/singleprocess/service_auth_oidc.go
Like https://github.com/hashicorp/waypoint/pull/3947, but for `singleprocess/service_auth_oidc.go`
=> Externalize errors in service_auth_oidc

pkg/server/singleprocess/service_config.go
Like https://github.com/hashicorp/waypoint/pull/3952, but for `singleprocess/service_conifig.go`
=> externalize service_config

.changelog/3972.txt, internal/cli/project_apply.go
Closes https://github.com/hashicorp/waypoint/issues/3966
=> Fixing panic when setting datasource to local on cli

pkg/server/singleprocess/service_deploy.go, pkg/server/singleprocess/service_entrypoint.go, pkg/server/singleprocess/service_exec.go, pkg/server/singleprocess/service_hostname.go, pkg/server/singleprocess/service_instance.go, pkg/server/singleprocess/service_job.go, pkg/server/singleprocess/service_logs.go, pkg/server/singleprocess/service_ondemand_runner.go, pkg/server/singleprocess/service_project.go
More externalizing errors like https://github.com/hashicorp/waypoint/pull/3956
=> Externalize multiple services

website/content/docs/pipelines/index.mdx, website/content/docs/resources/roadmap.mdx
This finishes [the PR](https://github.com/hashicorp/waypoint/pull/3877) started by @BukkyAdebayo -- thanks Bukky!
=> Finish roadmap update

website/content/docs/pipelines/index.mdx, website/content/docs/roadmap.mdx
=> Backport/finish roadmap updates/onto stable website

website/content/docs/pipelines/index.mdx, website/content/docs/roadmap.mdx
=> Backport/finish roadmap updates/onto release/0.10.x

pkg/server/singleprocess/service_pipeline.go, pkg/server/singleprocess/service_pipeline_run.go
More externalizing errors like https://github.com/hashicorp/waypoint/pull/3956
=> Externalize service pipeline

website/Makefile, website/README.md, website/redirects.js, website/scripts/website-build.sh, website/scripts/website-start.sh
Updates managed website-related files.
- `website/Makefile`
- `website/scripts/should-build.sh`
- `website/scripts/website-build.sh`
- `website/scripts/website-start.sh`
> **Note**
>
> This pull request was opened via the Digital team's automation. If you have questions, please tag @hashicorp/web-platform
=> chore: Update Digital Team Files

pkg/serverstate/statetest/test_project.go
This wasn't tested before.
NOTE: these tests aren't complete on purpose - it would be great to test the full suite of transitions, but currently not all sqlstate implementations support explicitly setting the local datasource type, and rely on the null state to represent that.
=> Tests for chaging datasource type

website/content/docs/resources/troubleshooting.mdx, website/content/docs/server/install.mdx
Minor updates to install docs.
=> Install documentation updates

internal/server/boltdbstate/application.go, internal/server/boltdbstate/job.go, internal/server/boltdbstate/job_test.go, internal/server/boltdbstate/project.go, internal/server/boltdbstate/project_test.go, pkg/server/singleprocess/poll_application.go, pkg/server/singleprocess/poll_project.go, pkg/server/singleprocess/poll_test.go, pkg/server/singleprocess/service_job.go, pkg/server/singleprocess/service_project.go, pkg/server/singleprocess/service_runner.go, pkg/server/singleprocess/service_status_report.go, pkg/server/singleprocess/service_trigger.go, pkg/server/singleprocess/service_ui_project.go, pkg/serverstate/serverstate.go, pkg/serverstate/statetest/test_application.go, pkg/serverstate/statetest/test_artifact.go, pkg/serverstate/statetest/test_build.go, pkg/serverstate/statetest/test_deployment.go, pkg/serverstate/statetest/test_instance.go, pkg/serverstate/statetest/test_job.go, pkg/serverstate/statetest/test_pipeline.go, pkg/serverstate/statetest/test_pipeline_run.go, pkg/serverstate/statetest/test_project.go, pkg/serverstate/statetest/test_release.go, pkg/serverstate/statetest/test_snapshot.go, pkg/serverstate/statetest/test_status_report.go
Adding ctx to the project server state interface methods to be able to better access the ctx to cancel expensive queries. I am phasing this out into smaller PRs, so there will be more to come.
=> update project serverState interface methods to add context

internal/server/boltdbstate/artifact.go, internal/server/boltdbstate/build.go, internal/server/boltdbstate/build_test.go, internal/server/boltdbstate/job.go, internal/server/boltdbstate/pipeline.go, internal/server/boltdbstate/pipeline_run.go, internal/server/boltdbstate/project.go, internal/server/boltdbstate/project_test.go, internal/server/boltdbstate/task.go, pkg/server/singleprocess/service_artifact.go, pkg/server/singleprocess/service_build.go, pkg/server/singleprocess/service_deploy.go, pkg/server/singleprocess/service_job.go, pkg/server/singleprocess/service_pipeline.go, pkg/server/singleprocess/service_pipeline_run.go, pkg/server/singleprocess/service_release.go, pkg/server/singleprocess/service_task.go, pkg/server/singleprocess/service_task_test.go, pkg/server/singleprocess/service_trigger.go, pkg/server/singleprocess/service_ui_deploy.go, pkg/serverhandler/handlertest/test_service_job.go, pkg/serverstate/serverstate.go, pkg/serverstate/statetest/test_artifact.go, pkg/serverstate/statetest/test_build.go, pkg/serverstate/statetest/test_job.go, pkg/serverstate/statetest/test_pipeline.go, pkg/serverstate/statetest/test_pipeline_run.go, pkg/serverstate/statetest/test_project.go, pkg/serverstate/statetest/test_task.go, pkg/serverstate/statetest/test_workspace.go
I'm phasing this out. There will be more to come. 
Ctx is added to the following funcs:
- Artifact
- Build
- Task
- Pipeline
- PipelineRun
=> Add ctx to some serverstate app ops

internal/ceb/server.go, pkg/serverclient/client.go
Resolves https://github.com/hashicorp/waypoint/issues/4015
=> Slightly less generic server connection error.

website/content/docs/lifecycle/hooks.mdx, website/content/docs/lifecycle/index.mdx, website/content/docs/resources/internals/architecture.mdx, website/content/docs/resources/internals/execution.mdx, website/content/docs/resources/troubleshooting.mdx, website/content/docs/runner/adoption.mdx, website/content/docs/runner/config.mdx, website/content/docs/runner/index.mdx, website/content/docs/runner/on-demand-runner.mdx, website/content/docs/runner/profiles.mdx, website/content/docs/runner/run-manual.mdx, website/content/docs/upgrading/index.mdx, website/content/docs/waypoint-hcl/registry.mdx, website/content/docs/waypoint-hcl/variables/dynamic.mdx
This PR should address the failed backport [here](https://github.com/hashicorp/waypoint/pull/4154).
=> Cleanup docs about runners.

website/content/docs/entrypoint/index.mdx, website/content/docs/lifecycle/index.mdx
=> Fix backport #4127

pkg/server/singleprocess/service_runner.go
It is possible for a job to disappear and have the event handler attempt to use job before checking if there was an error on the error stream which can cause Waypoint to panic.
=> Add additional logging to find race condition

website/content/docs/app-config/dynamic.mdx
As suggested here: https://github.com/hashicorp/waypoint/pull/4215#discussion_r1026534010
=> website: add Consul to app-config/dynamic docs

pkg/server/singleprocess/service_runner.go
Without validation, events can cause nil derefs
=> Properly validate form of event types

.changelog/4196.txt, internal/cli/config_source_get.go, internal/cli/config_source_set.go, pkg/server/singleprocess/service_entrypoint.go, pkg/server/singleprocess/service_runner.go, website/content/commands/config-source-get.mdx, website/content/commands/config-source-set.mdx
=> Fix backport #4234

pkg/server/singleprocess/service_job.go
Not all of them, but some of them.
=> Externalizing a few more errors in service_job

website/content/docs/upgrading/version-guides/0.10.0.mdx, website/content/docs/upgrading/version-guides/0.2.0.mdx, website/content/docs/upgrading/version-guides/0.6.0.mdx, website/content/docs/upgrading/version-guides/0.8.0.mdx, website/content/docs/upgrading/version-guides/0.9.0.mdx, website/data/docs-nav-data.json
And some grammatical/spelling fixes in older guides!
=> v0.10.0 upgrade guide

website/Makefile, website/package-lock.json, website/package.json, website/scripts/should-build.sh, website/scripts/website-build.sh, website/scripts/website-start.sh
Update our website scripts to their latest versions. This aligns with what's on `main`.
=> fix: update website scripts to reflect the most recent versions

pkg/server/singleprocess/service_job.go, pkg/server/singleprocess/service_runner.go
Manual backport of https://github.com/hashicorp/waypoint/pull/4325
=> Backport of server: Ensure a job is not stuck in Running and is Completed on err processing job events into release/0.10.x

internal/server/boltdbstate/job.go, pkg/server/singleprocess/service_ui_project.go, pkg/serverstate/serverstate.go, pkg/serverstate/statetest/test_job.go
Should help us to speed up loading of the project UI against BoltDB and other state implementations.
=> state: add `JobLatestInit`

website/content/docs/intro/use-cases/waypoint-gh-actions.mdx
Updates a few legacy links that were merged into `main` since #4277
=> docs: Updating legacy links

website/content/docs/waypoint-hcl/syntax/index.mdx
=> Fixed Stanzas example

website/README.md
Follow up from https://github.com/hashicorp/waypoint/pull/4400
=> website: Fix typo in readme

website/content/docs/runner/profiles.mdx
Adding to runner profile set to be more explicit on editing runner profile plugin config.
=> Add to runner profile docs

pkg/server/singleprocess/service_job.go
This causes a server panic in the error parsing
=> Not ignoring errors in the job service

website/content/docs/runner/profiles.mdx
Going to remove this [backport PR](https://github.com/hashicorp/waypoint/pull/4428).  Adding back in changes [from this PR](https://github.com/hashicorp/waypoint/pull/4426/files).
=> Fix backport runner profile

website/README.md, website/package-lock.json, website/package.json
Add a `content-check` command and document it in the website directory's README file.
=> website(README): add content-check command

website/content/docs/extending-waypoint/api/index.mdx, website/data/docs-nav-data.json
This PR adds a page overview of our API Docs to the website
=> Add API docs to website

CHANGELOG.md
Adds the changelog entries for upcoming v0.11.0 release
=> Add changelog for v0.11.0

pkg/server/gen/server.pb.gw.go, pkg/server/gen/server.swagger.json, pkg/server/proto/gateway.yml, scripts/gateway-yml-check.sh
This has been missing for ages, suggesting we’re not currently using it. Still, doesn’t hurt to plug the gap.
=> Add `UI_GetDeployment` to `gateway.yml`

.github/workflows/jira.yml
Update the value for custom field 10371 for Jira from GitHub Issue to GitHub.
=> More Jira fixes

pkg/server/singleprocess/service_ui_pipeline.go, pkg/serverhandler/handlertest/test_service_ui_pipeline.go
Adding queueTime and friends to UI_ListPipelines.
=> Add missing fields to `UI_ListPipelines`

pkg/server/singleprocess/service_job.go, pkg/server/singleprocess/service_runner.go
Log at info level the proper lifecycle of a job to aid in debugging
=> More context fixes, better job logging

pkg/server/gen/mocks/waypoint_client.go, pkg/server/gen/mocks/waypoint_server.go, pkg/server/gen/server.pb.go, pkg/server/gen/server.pb.gw.go, pkg/server/gen/server.pb.json.go, pkg/server/gen/server.swagger.json, pkg/server/gen/server_grpc.pb.go, pkg/server/proto/gateway.yml, pkg/server/proto/server.proto
A precursor to #4567. I still have a few kinks to iron out in #4567 but UI work can proceed against these types.
=> Declare `UI_GetPipelineRun` and friends

pkg/server/gen/server.pb.gw.go, pkg/server/gen/server.swagger.json, pkg/server/proto/gateway.yml
Without this, we can’t pass any of the attributes over HTTP :)
=> Add `body: *` to CreateProjectFromTemplate grpc-gateway mapping

website/content/docs/lifecycle/build.mdx
Fixup from https://github.com/hashicorp/waypoint/pull/4579
=> Update ref markdown

.github/workflows/labeler.yml
Per https://github.com/actions/labeler/issues/136#issuecomment-1357839196
=> labeler needs 'write' to add labels

pkg/serverstate/statetest/test_job.go
Identical to #4723, but in a few more places!
=> Remove more race conditions in job test

internal/cli/release_create.go, internal/runner/accept_test.go
Fixed the typo as requested in issue #4738
Fixes #4738
=> Typo fixes in release_create.go and accept_test.go

website/content/partials/components/platform-aws-ecs.mdx
The smallest doc fix PR you'll ever see.
=> ECS plugin doc fix

internal/installutil/helm/helm.go
This was causing [linting failures](https://github.com/hashicorp/waypoint/actions/runs/5192229574/jobs/9361106481).
=> go fmt ./internal/installutil/helm/helm.go

internal/cli/main.go, internal/cli/template_create.go, internal/cli/template_delete.go, internal/cli/template_inspect.go, internal/cli/template_list.go, internal/cli/template_update.go
This PR adds in the cli interface to managing project templates within Waypoint.
=> core/cli: Add project template crud commands to cli

pkg/serverstate/statetest/test_config_source.go
=> More config sourcer state tests

internal/jobstream/stream.go
Prior to this commit, we didn't give the user much context for why a job might be stuck. This commit adds more debug help when a job has waited an unusual amount of time to be picked up by a runner. The expected scenario here is that a bad or invalid runner profile was selected, and the runner associated with this profile no longer exists.
There might also be a bug here with our Job timeouts not properly erroring out the job after ~2 minutes since it seems to hang forever in the Queued state waiting for a runner to Ack the job.
=> jobstream: Add additional context for long runner ack times
