- website/content/docs/extending-waypoint/creating-plugins/testing.mdx
The link to the plugin examples was broken.
> Fix plugin example link

- website/content/docs/lifecycle/build.mdx
While the Paketo buildpacks project is in the CFF, their OSS name is just Paketo Buildpacks.
CC @sclevine
> Rename Cloud Foundry Paketo -> Paketo

- internal/cli/install.go
- website/content/commands/install.mdx
- website/content/commands/server-install.mdx
Fixes a small typo in the install cmd + docs.
> docs: fix service typo

- website/content/docs/automating-execution/gitlab-cicd.mdx
- website/content/docs/index.mdx
- website/data/docs-navigation.js
Hi,
we've tested Waypoint with GitLab CI/CD and EC2 in this project: https://gitlab.com/brendan-demo/waypoint/ 
This PR adds the integration documentation for involving the GitLab CI/CD configuration, and tips for using GitLab environments with Waypoint workspaces.
> Docs: Add GitLab CI/CD exec integration

- builtin/azure/aci/deployment.go
This fixes a dropped `err` variable in `builtin/azure/aci`.
> builtin/azure/aci: fix dropped error

- website/pages/home/index.jsx
Adds GitLab to CI/CD + VCS section on homepage
[🔍  Preview link](https://waypoint-git-jmwebsite-gitlab-txt.hashicorp.vercel.app)
> [Website] Add GitLab to CI/CD + VCS section on Homepage

- website/components/temporary_docs-page/index.jsx
There was a regression caused that ended up breaking this when we fixed the 'edit this page' bug, when we changed the product passed in here to be waypoint.  That was the right call, but another unexpected bug was that the DocsPage component actually expects `blue` here, and not waypoint.  This is an artifact of our product codename usage that we'll clean up soon.
Here's a hotfix that gives us the right theme, while also maintaining the right edit this page links.
> Add back docs blue theme

- go.mod
- go.sum
We try to use the ConPTY set of APIs which were introduced in 1809. The
Waypoint SDK was updated to fallback to pipes for earlier versions of
Windows:
https://github.com/hashicorp/waypoint-plugin-sdk/commit/59421183d54fd19cbeaa37b72bcd48ab7252699e
> update waypoint-plugin-sdk for <= Windows 10 1809 compat

- builtin/aws/ecs/platform.go
Closes: https://github.com/hashicorp/waypoint/issues/513
This will allow you to use an existing ECS cluster with Waypoint even when there is only one ECS cluster in the AWS account.
> Handle case where there is only one ECS cluster with a given name

- builtin/docker/builder.go
Closes https://github.com/hashicorp/waypoint/issues/538
Add the variable `Dockerfile` to the `BuilderConfig` of the Docker Plugin to support cases where the Dockerfile is not in the root of the project.
Please let me know if you think the variable should have another name or if you think the dockerfile name shouldn't be relative to the path of the app.
> builtin/docker/builder: Add dockerfile variable to BuilderConfig

- website/vercel.json
this will make the website’s build logs public to outside contributors to view and troubleshoot potential build errors on their PRs. it also sneaks in the `version: 2` config, which is encouraged by vercel. 
reference docs: https://vercel.com/docs/configuration#project/public
> website: set up public build logs for vercel

- website/content/docs/lifecycle/deploy.mdx
Fix 2 broken or incorrect links in the deploy documentation.
> Fix broken links in docs/lifecycle/deploy

- internal/ceb/config.go
- internal/ceb/url.go
We can just do this whole thing in a goroutine, there's no reason to block on this.
I checked the Horizon agent code and there are some places that are questionable on retries but overall this is an improvement so I think we should get this in at least for 0.1.2 today.
> internal/ceb: do not block child process startup on URL service conn

- website/components/footer/index.jsx
- website/content/docs/url.mdx
We want any URL service users to be able to find the status page, so I put it in the footer and on the URL service page.
Longer term, it'd be great if we could render this dynamically in the header or similar if that statuspage.io component has issues.
Ref #519.
> website: add notes about status.hashicorp.com

- internal/cli/base_init.go
- internal/cli/init.go
Fix #552 
We weren't validating the basic config structure on `init`, only semantics with plugins. This can cause panics. We need to validate much earlier.
> internal/cli: validate config on init properly

- builtin/nomad/platform.go
We were targeting the ID when it should've been the name.
Fixes #560
> builtin/nomad: destroy works

- internal/cli/install.go
- internal/serverinstall/docker.go
- internal/serverinstall/nomad.go
This is just a CLI UI thing. It is clunky to use both status and stepgroups together, and we've inched towards preferring stepgroups. This makes the change for all our supported install platforms.
> internal/serverinstall: convert installation methods to use stepgroups

- website/README.md
updated link to direct to waypointproject.io which I assume is the correct site.
> fix: updated waypoint link as current link points to a dead website

- website/content/docs/server/index.mdx
Fix documentation about adding a new context. Name of the context must be at the end of the command and not right after the `create` parameter.
This way it works, the other way around it does not work.
> fix(documentation)

- website/content/docs/automating-execution/github-actions.mdx
Closes #579.
This demo uses the experimental action-waypoint, which may not be maintained longer term,  and I'd rather us limit the maintenance burden associated with this demo repository (that is currently private). I think the screenshot serves this well, and the example is the same as is used in the demo.
This demo can easily be demonstrated by:
- Copying the example action workflow in the documentation
- Grabbing one of the examples (https://github.com/hashicorp/waypoint-examples)
- Pushing it up to GitHub
> website: drop link to github actions demo

- builtin/pack/builder.go
This PR adds support for environment variables with the pack build phase 
Some buildpacks allow configuration via environment variables such as https://github.com/GoogleCloudPlatform/buildpacks see https://github.com/GoogleCloudPlatform/buildpacks#common-options for available environment variables
I copied the configuration style from the docker build stage so configuration looks like the following: 
```
build {
use "pack" {
builder     = "gcr.io/buildpacks/builder"
static_environment = {
"GOOGLE_BUILDABLE" : "./cmd/webhook"
}
}
}
```
I've tested it locally and can see from the output that it used my environment variable as expected 
```
│ [builder] Running "go build -o /layers/google.go.build/bin/main ./cmd/webhook (GOCACHE=/layers/google.go.build/gocache)"
```
> Add support for environment variables with pack build

- Makefile
alpine docker images and scratch images [were not working](https://discuss.hashicorp.com/t/how-do-you-build-a-project-with-a-dockerfile-that-has-its-own-entrypoint/16086/8) until CGO_ENABLED was used in the build for `waypoint-entrypoint`.
> Add CGO_ENABLED to entrypoint

- builtin/aws/alb/releaser.go
- builtin/aws/ami/builder.go
- builtin/aws/ec2/platform.go
- builtin/aws/ecr/registry.go
- builtin/aws/ecs/platform.go
- builtin/aws/ecs/releaser.go
From the `godoc` for `github.com/aws/aws-sdk-go/aws/session`:
> Deprecated: Use NewSession functions to create sessions instead. NewSession has the same functionality as New except an error can be returned when the func is called instead of waiting to receive an error until a request is made.
This replaces `session.New()` with `session.NewSession()` throughout `builtin/aws`. 
I'm happy to squash this into a single commit, if that is preferred.
> Replace Deprecated AWS session.New

- website/content/partials/components/platform-kubernetes.mdx
- The example suggests using a `count` config variable, and the plugin errors out when trying to use that. This changes the example variable to `replicas` (which is the one documented above)
> docs: fix k8s example using count instead of replicas

- internal/pkg/flag/flag_string_slice.go
Fixes #601
We should only use the default string slice value if no flags are given.
Nomad is currently the only user of this flag and this is the expected
behavior there, plus I believe elsewhere.
> internal/pkg/flag: string slice defaults only if no flags given

- builtin/aws/ecs/platform.go
As far as I can tell, when an ECS user deletes a cluster it does not actually remove all references to it from the API. The describe-clusters endpoint still returns the deleted cluster with the status of `INACTIVE`.
After deleting the cluster myself and attempting to test a different change I noticed waypoint logged that the cluster existed and skipped creation later on failing for a non existent cluster.
This PR adds a check for this status before determining if the cluster is found.
I have tested this change for both existing and deleted clusters.
> Check for active ECS cluster

- builtin/docker/platform.go
- website/content/partials/components/platform-docker.mdx
I had to define the command as an array otherwise it fails during the build phase with the following error:
```
! waypoint.hcl:15,17-19: Unsuitable value type; Unsuitable value: list of string
```
> Fix deploy docker command doc

- website/content/partials/components/platform-aws-ecs.mdx
since above it is described as an `int`, as well as in the Config struct https://github.com/hashicorp/waypoint/blob/cabbaf7d25c17a9dd94b5576f597bc8a986e6e07/builtin/aws/ecs/platform.go#L1130
In my testing, strings do work though :shrug:
> docs: fix string example for aws-ecs memory

- .circleci/config.yml
As discussed in https://github.com/hashicorp/waypoint/pull/524#issuecomment-710144890
everyone should run `make format` before submitting their code, otherwise
the pipeline will fail (now).
> Enable mandatory go formatting check in CI pipeline

- builtin/docker/platform.go
- website/content/docs/extending-waypoint/creating-plugins/compiling.mdx
- website/content/docs/extending-waypoint/passing-values.mdx
This PR enables the ability for the Docker plugin to target a remote docker engine when doing a deployment.
While it is possible to target the Remote Docker Engine using the environment variables `DOCKER_HOST` this would take effect for the build and deploy phases. It is not possible to build locally and then deploy to a remote instance.  The individual options can be specified independently.
```javascript
project = "wpmini"
app "wpmini" {
labels = {
"service" = "wpmini",
"env"     = "dev"
}
build {
use "pack" {}
}
deploy {
use "docker" {
client_config {
host = "tcp://remote.ip:2375"
cert_path = "./remote_certs"
api_version = "19.03"
}
}
}
```
In addition, this PR checks the presence of a Docker Image in the Engine cache before attempting to start a container, an option has been created …
> Docker Remote Engine

- .circleci/config.yml
Not every job that needs to notify imports the environment. Since we only use this value in the job to notify slack, we don't need to rely on the env var.
> replace env var with link

- internal/clicontext/storage.go
- internal/clicontext/storage_test.go
Fixes #625
This is a fallback because this is not an _atomic_ writing solution. On
Windows, it appears this isn't possible to begin with so this is best
effort.
Symlinks generally do work fine on Windows and other systems, but if
they don't for any reason (usually permissions), we fall back to normal
files.
> internal/clicontext: fall back to plain files if symlinks don't work

- builtin/aws/ecs/platform.go
> builtin/aws-ecs: fix crash if subnets are specified

- builtin/aws/alb/releaser.go
- builtin/aws/ami/builder.go
- builtin/aws/ec2/platform.go
- builtin/aws/ecr/registry.go
- builtin/aws/ecs/platform.go
- builtin/aws/ecs/releaser.go
- builtin/aws/utils/session.go
Fixes #604
This enables loading ~/.aws/config for assumed role auth.
We should talk to the Terraform team about making aws-sdk-go-base less
Terraform-specific so we can share it, since they've solved a lot more
problems that we're going to run into: https://github.com/hashicorp/aws-sdk-go-base
But for now, this will work.
> builtin/aws: use SharedConfig to load ~/.aws/config

- builtin/aws/ecs/platform.go
Fixes #369 
An ALB listener cannot exist without a target group.
This PR deletes the ALB listener if there is only one target group to avoid a validation error.
I'm not sure if this is the best route forward here but opening to discuss.
Other options to consider:
* Delete the ALB altogether
* Leave the target group but remove the targets? I think ECS handles this registration.
> Delete ECS ALB listener if there is a single target group on destroy

- builtin/aws/ecs/platform.go
First of all, I'd like to say how excited I am about this project! As an ECS user, while there are multiple deploy tools available, I haven't found anything that feels flexible enough to meet our requirements. The hooks feel especially beneficial. 
I'm really interested in the design choices around running an application because there are lots of opinionated tools that lack the flexibility we need. At the moment deploying into ECS with Waypoint assumes a bunch of stuff (single container on a specified port), and I'm assuming that this is mostly because it's an early release. 
I guess my main question here is: how much flexibility between the configuration and the "assumed defaults" are going to be a feature of Waypoint? Will it be possible to deploy into a very specific ECS setup, or is …
> Updated options for ECS deploys

- ui/app/routes/onboarding/install/index.ts
- ui/app/templates/onboarding/install/chocolatey.hbs
- ui/tests/acceptance/onboarding-test.ts
We don't currently have a chocolatey package, so we can't list this as an option. Though, did leave the Chocolatey stuff there for the future and fixed a broken link.
Also means we need to switch the test to linux.
> ui: remove windows onboarding install for now

- builtin/k8s/platform.go
- builtin/k8s/releaser.go
- website/content/partials/components/platform-kubernetes.mdx
- website/content/partials/components/releasemanager-kubernetes.mdx
Adding namespace as a configuration parameter to the Kubernetes plugin allows for
dynamically setting the namespace to target without having to set a different kubeconfig
context for each.
> Adding namespace config to k8s deploy/release

- internal/cli/server_bootstrap.go
We previously allowed bootstrap to work for in-memory server processes,
and this was making user error when running a real server.
Realistically, bootstrap makes no sense for in-memory servers so show an
error if this is the case.
> internal/cli: server bootstrap should error on in-process mode

- .github/workflows/backport.yml
***Note:** This should only be merged after we create a `stable-website` branch.*
`backport-assistant` enables us to merge documentation around future releases into `main`, and selectively automerge documentation for the current release into `stable-website.`
If there are no merge conflicts it will create and automerge the targeted PR into stable-website - [example automerged PR](https://github.com/krantzinator/waypoint/pull/3)
If there are merge conflicts, it will leave the PR open - [example open PR](https://github.com/krantzinator/waypoint/pull/5)
This action runs if a merged PR has the label `website/cherrypick`, and it targets the branch `stable-website` for automerging.
> Website: Add action for automerging docs updates into stable-website

- builtin/aws/ecs/platform.go
This PR enables users to configure the listening port for container workloads to deploy in ECS. This is useful for application workloads that require a specific port configured, or application deployments done via a Dockerfile. 
The default port remains 3000. This PR is similar to exposed configurations we have in Nomad, K8s, and Docker currently.
> Allow configuration of container listening port on ECS

- builtin/aws/ecr/registry.go
- builtin/docker/builder.go
- builtin/docker/client/client.go
- builtin/docker/platform.go
- builtin/docker/pull/builder.go
- builtin/docker/registry.go
- builtin/pack/builder.go
Resolves https://github.com/hashicorp/waypoint/issues/663
This package makes possible the creation of a Docker client that can connect to a remote daemon host that requires custom logic. It uses the connhelper package from the Docker CLI to accomplish this.
> Add builtin/docker/client

- internal/serverinstall/nomad.go
When running `waypoint server install ...` there is no way to override Nomad sentinel policies. This allows a simple override flag to allow folks to get running as quickly as possible.
> Allow Nomad sentinel policy override on install

- website/content/partials/components/platform-kubernetes.mdx
> Fix typo in docs

- website/content/docs/automating-execution/gitlab-cicd.mdx
Instead of downloading the images on every run, GitLab provides regularly updated custom images for Waypoint hosted on GitLab's container registry for every version and the latest version tagged with `latest`.
> Change  Docker Image used by GitLab CI/CD

- website/content/docs/extending-waypoint/creating-plugins/index.mdx
Was following the guide and noticed that `clone.sh` also requires you to specify a name
> Fix clone script snippet

- internal/cli/config_set.go
Fixes #561.
This change allows the user to pass arguments to `waypoint config set` using pipes:
```
$ cat .env | waypoint config set
```
---
The linked issue also proposes a `-raw` flag for `config get`, but this flag apparently already exists:
https://github.com/hashicorp/waypoint/blob/b00f8ab1b17db429bc8242cb06a922bcdd9c8203/internal/cli/config_get.go#L137-L141
However, `waypoint config get -raw` doesn't print anything to my console. Maybe this is a separate issue.
> Make waypoint config set command pipeable

- internal/cli/base_init.go
Fixes #673
Without this, a flag never takes precedence if a context exists and
therefore doesn't work at all.
> internal/cli: fix precedence on conn info to context => env => flags

- internal/datasource/local.go
- internal/runner/accept.go
The local datasource needs to return the pwd so that plugin discovery
uses an absolute path and doesn't attempt to search by PATH (#691).
This also adds validation in internal/runner that this behavior holds.
/cc @tomhjp
> internal/datasource: local data should return pwd

- internal/plugin/discover.go
This supports this path even if it does not match the XDG path. The XDG
path still takes priority over this path.
> internal/plugin: support plugins in $HOME/.config/waypoint/plugins

- builtin/aws/ecs/platform.go
In ECS, there are two concepts for IAM roles: the execution role[1], that allows AWS to make API calls on your behalf, to do things like pull images from ECR and write logs to CloudWatch; and the task role[2], that allows the containers within your task access to whatever resources you need them to.
Given we almost always need the execution role, it makes sense to have this created by default if it isn't specified.
The task role should not be created by default since we have no way to know what the application requires, but we should allow being able to configure it.
Initially this commit allows specifying the name of a role created elsewhere. I suspect though that it might be incredibly useful to be able to define which resources your application needs in `waypoint.hcl`, and have a role …
> Update ECS plugin for execution and task roles

- .github/workflows/backport.yml
One day we will want to cherrypick bug fixes into previous releases when we merge them into `main`. Merging this in now means we are ready to go when we decide to start using this pattern.
Example use case:
- add a label `backport/0.1.x`
- merge PR
- Backport Assistant attempts to duplicate the PR+commits into the corresponding `release/0.1.x` branch and automerge; if cherrypicks fail, the PR stays open noting that the cherrypicks failed and it requires manual attention
This pattern allows us to make use of both general (`0.1.x`) and specific (`0.1.1`) branch names in the `backport/*` labels.
> support backporting into release branches via labels

- .circleci/config.yml
- Dockerfile
Dockerhub is going to rate limit unauthenticated pulls.
Use internal mirror for CI and Dockerfiles built in CI.
> Use Dockerhub Mirror.

- website/content/docs/workspaces.mdx
Apologies, forgot to tag the typo fix PR with the right cherry-pick label, so doing it manually.
> Backport of Fix doc typo

- builtin/google/cloudrun/platform.go
This makes the default experience for Google Cloud Run better because it
will actually release the site and make it able to be visited. This
seems to also fix an issue where GCR locks down network access
completely without this set.
> builtin/google/cloudrun: default releaser

- builtin/aws/ecs/platform.go
When using `ec2_cluster = true` there is an error `InvalidParameterException: Assign public IP is not supported for this launch type`. This wraps the `AssignPublicIp` network configuration so that on ec2_clusters this is not set to enabled.
This was reported in #643, and I've experienced it myself. Without ec2_cluster = true, Fargate will be used, and this setting works.
> Update ECS plugin to not assign public ip on ec2_cluster

- internal/ceb/ceb.go
- internal/ceb/url.go
Looking through the connect and reconnect code paths, it's pretty clear that we're leaking an agent instance on every reconnect. If a user had a waypoint server that was having trouble running steady state (perhaps due to too tight of a memory budget), then it would be easy to see how an entrypoint could spawn thousands of agents accidentally.
This code just makes sure that we only run one at a time by canceling the context for the previous one if there is a context set.
> internal/ceb: prevent multiple horizon agents from running in the same ceb

- internal/server/id.go
These are not concurrency-safe. Realistically our operations that
generate IDs are not fast enough to worry about forcing monotonic
behavior: it should happen naturally from the timestamp.
> internal/server: don't use monotonic ulids

- internal/core/app.go
- internal/core/app_release.go
- internal/core/app_release_destroy.go
This was an outstanding TODO from #680 I forgot to complete.
This takes the deferred loading and still loads the default releaser if
that is set. Without this, our default releasers weren't loading at all.
> internal/core: load default releaser with new deferred config

- builtin/google/cloudrun/validation.go
- builtin/google/cloudrun/validation_test.go
Fixes #725
It seems to be possible for projects to have slashes. This eases up on
validation to allow more projects to work.
> builtin/google-cloud-run: less strict image validation

- builtin/k8s/platform.go
Default releasers do not get configured (as documented) since they have
no config. It is up to the platform to specify any default configs as
well. We need to forward along the Namespace config to ensure it starts
in the same NS.
I also copied over other shared fields.
Fixes #727
> builtin/k8s: default releaser should mirror namespace settings

- internal/cli/app_docs.go
- internal/cli/artifact_build.go
- internal/cli/artifact_push.go
- internal/cli/base.go
- internal/cli/deployment_create.go
- internal/core/operation.go
Address #719 
We were neglecting to return a non-nil error when dealing with `ErrSentinel` types, which is what we use most of the time.
> internal/core: return error if type is ErrSentinel to signal exit codes

- internal/ceb/ceb.go
- internal/ceb/ceb_test.go
- internal/ceb/child_exec.go
- internal/ceb/config.go
- internal/ceb/config_test.go
- internal/ceb/exec.go
- internal/ceb/init.go
- internal/ceb/log.go
- internal/ceb/server.go
- website/content/docs/app-config.mdx
When config variables change, this will gracefully restart the child process to get the new config variables.
"Graceful restart" follows the same process as [Heroku](https://devcenter.heroku.com/articles/what-happens-to-ruby-apps-when-they-are-restarted): we send the child a SIGTERM and if the child doesn't exit in 30 seconds we send a SIGKILL.
This required quite a bit of refactoring, but all tests are passing and I added a test to verify we restart properly for env var changes.
> internal/ceb: support child process restarts on config change

- .circleci/config.yml
We'll still get two failure notifications if `lint` fails, but they will be quick and then stop.
> run lint first to limit excessive failures

- internal/core/app_deploy_destroy.go
- internal/core/app_release_destroy.go
This commit includes the application name that waypoint is destroying to
give the user a bit more information when the destroy command is
running.
> Add more descriptive output to `waypoint destroy`

- .github/workflows/backport.yml
Updates:
- v0.2.2 bug fixes:
- PRs opened by users without write access will request review from the person who merged the PR, rather than the original PR author
- PRs that are automerged skip requesting reviews
- team review requests uses slugs only now to avoid excessive checks (we don't use team assignments in waypoint; FYI only)
- changed the `stable-website` label to `backport/website` to match the backport labels format in this project
- updated regex for release branch label
I'll create the `backport/website` and delete the `website/cherrypick` labels when this is merged.
> backport version and label regex updates

- nix/sources.json
Lovely to see nix in the wild :heart: I was looking forward to something like this since @mitchellh's first nix related tweet
https://github.com/nixos/nixpkgs-channels has been depricated.
Updated niv source to use main https://github.com/nixos/nixpkgs repo.
Using the same channel/branch and rev there shouldn't be any incompatibilities.
> nix: move depricated nixpkgs-channels to nixpkgs

- internal/cli/config_get.go
Prior to this commit, if a user left off an argument for `waypoint
config get -raw`, it would simply exit 1. This commit first ensures that
a named variable was passed in to match against, and otherwise adds some
additional error output to let the user know what went wrong.
> Fixes #813: Improve error handling for config get command

- internal/cli/server_config_set.go
> internal/cli: server config set doesn't require waypoint.hcl

- internal/version/version.go
I'm not sure if this got missed in the last release, but I noticed when I compile waypoint locally I kept getting `0.1.4`, and noticed the Makefile references this file on github to determine its version. It might of just got missed, so this PR updates that version to match the current release of `0.1.5`.
> Fix dev version to be current released 0.1.5

- internal/cli/config_get.go
Fixes #823.
This is a rather simple fix, so let me know if this is actually sufficient.
**Before this PR:**
```shell script
$ waypoint config get -raw
```
**With this PR:**
```
$ waypoint config get -raw
PASSWORD=test
USERNAME=alice
```
> waypoint config get: Make -raw print all variables

- internal/cli/config_get.go
- website/content/commands/config-get.mdx
This pull request updates the docs around the new behavior of the `-raw` flag for `waypoint config get`. It also ensures that if an argument is passed, it still prints it as a `key=value` so that it behaves just like the `json` flag.
Built off of the initial commit https://github.com/hashicorp/waypoint/pull/828, can be merged once the manual backport PR is merged https://github.com/hashicorp/waypoint/pull/832
> Docs update for `config get raw`

- website/content/docs/troubleshooting.mdx
This context was taken directly from the Learn tutorials. Given that
it's useful for investigating deployed applications, and the fact that a
user might miss this context if they didn't follow the Learn guide, it
seems useful to also have this context on the docs where it's more
discoverable for people.
> docs/troubleshooting: Include extra help for troubleshooting deployments

- builtin/aws/ecr/registry.go
I thought I'd give this a go as it looked like a pretty simple change and a good "first issue"
A few thoughts:
1. This logic should be centralised for all aws environment config.
2. Packer and terraform use https://github.com/hashicorp/aws-sdk-go-base which seems reasonable to migrate to.
3. This logic is too simple, it should try and lean on the SDK more (ie: load region from default profile)
4. The logic about leaning on the sdk seems similar between terraform and packer - maybe we can push that into the aws-sdk-go-base?
Finally, my dev environment is not healthy enough to check the documentation output.
After installing protobuf from homebrew and running:
```make gen/doc```
> ./vendor/proto/api-common-protos/: warning: directory does not exist.
google/rpc/status.proto: File not found. …
> #745 environment variables to be used instead of 'region' property for aws-ecr registry

- CHANGELOG.md
- builtin/google/cloudrun/deployment.go
- builtin/google/cloudrun/platform.go
fixes: https://github.com/hashicorp/waypoint/issues/764
Also I can't seem to run `make gen/doc` , getting the following error
```
protoc -I=. \
-I=./vendor/proto/api-common-protos/ \
--doc_out=./doc --doc_opt=html,index.html \
./internal/server/proto/server.proto
google/rpc/status.proto: File not found.
internal/server/proto/server.proto:10:1: Import "google/rpc/status.proto" was not found or had errors.
internal/server/proto/server.proto:403:3: "google.rpc.Status" is not defined.
internal/server/proto/server.proto:502:3: "google.rpc.Status" is not defined.
internal/server/proto/server.proto:687:7: "google.rpc.Status" is not defined.
internal/server/proto/server.proto:694:7: "google.rpc.Status" is not defined.
internal/server/proto/server.proto:583:3: "google.rpc.Status" is not defined. …
```
> Add Service Account Field to Cloud Run

- internal/cli/app_docs.go
- website/content/docs/waypoint-hcl/functions/all.mdx
- website/content/docs/waypoint-hcl/functions/index.mdx
- website/content/docs/waypoint-hcl/functions/template.mdx
- website/content/docs/waypoint-hcl/index.mdx
- website/content/docs/waypoint-hcl/variables/artifact.mdx
- website/content/docs/waypoint-hcl/variables/deploy.mdx
- website/content/docs/waypoint-hcl/variables/entrypoint.mdx
- website/content/docs/waypoint-hcl/variables/index.mdx
- website/content/docs/waypoint-hcl/variables/path.mdx
- website/content/partials/funcs.mdx
- website/data/docs-navigation.js
This adds complete documentation for:
* `path` vars
* `template*` functions
* Full function reference (completing Evan's work!)
* `artifact` and `deploy` variables
This **does not** include docs for dynamic config since that is not merged yet to main and also is huge on its own so I want to PR those docs separately.
> Docs for path vars, template functions, and artifact/deploy variables

- internal/server/server.go
Prior to this commit, go generate would run in the dir
`internal/server`, so when it went to look for the server.proto, it
would look inside
`waypoint/internal/server/internal/server/proto/server.proto`. This
commit fixes that by ensuring it goes back to the root dir to find
`server.proto`.
> Fix path for server proto when using go generate

- ui/app/components/log-stream/index.hbs
- ui/app/components/log-stream/index.ts
- ui/app/components/operation-logs/index.hbs
- ui/app/components/operation-logs/index.ts
- ui/app/styles/_app-card.scss
- ui/app/styles/_page.scss
- ui/app/templates/workspace/projects/project/app/build.hbs
- ui/app/templates/workspace/projects/project/app/deployment.hbs
- ui/app/templates/workspace/projects/project/app/logs.hbs
- ui/app/templates/workspace/projects/project/app/release.hbs
- ui/package.json
- ui/yarn.lock
Updates the streaming logs components in the UI client to support auto-scrolling and pinning/unpinning.
By default, when new lines start to overflow the logs container, the container will automatically scroll so that you remain pinned to the latest log line. If you scroll up that behavior is paused and you'll be unpinned and free to scroll up and down even as new lines are added. If you scroll back to the bottom you will become pinned again and the auto-scrolling kicks back in.
While in the unpinned mode, a button will be displayed in the top right corner - clicking the button will scroll to the bottom of the container and pin. If new lines are added while the button is visible it will display a count of how many new lines have been added.
> Auto-scroll UI client log components

- internal/cli/base_init.go
- internal/config/path.go
- internal/runner/operation.go
The way we load (using the hclsimple package) will automatically use the
JSON loader if it ends in ".json", we just never accepted ".json"
before.
> internal/config: support waypoint.hcl.json for HCL-flavored JSON syntax

- website/.gitignore
- website/package.json
> 🙇‍♂️ i will squash all my tmp commits on merge. needed to test out some ENV variables on our build machines before i came to the correct ones.
this creates a `prebuild` script which runs prior to our `build` script on vercel's build machines, and injects a `robots.txt` file that prevents crawling for all deployments based on our `main` branch. 
this logic is a predecessor to creating a [tip.waypointproject.io](https://tip.waypointproject.io) branch domain, which will continuously build a preview of docs content on `main`. 
⚠️ at the time of this PR, the DNS is not yet in place for the `tip` subdomain. 
you can verify this worked via a [commit](https://github.com/hashicorp/waypoint/pull/865/commits/eacde5393f90764de11e54e665734d2c502f4de2) where i used the inverse of the conditional to …
> website: add robots.txt for deploys from master

- builtin/aws/ecs/platform.go
Just a typo fix for "registring" -> "registering" in a debug statement.
> Fix typo in ECS debug logging

- internal/ceb/config.go
- internal/ceb/exec.go
This fixes an issue where `waypoint exec` sessions weren't getting
access to any of the config vars set with `waypoint config` or the
config stanza, including dynamically synced values.
This is important so that use cases like `waypoint exec rake db:migrate`
do the right thing.
> internal/ceb: exec sessions should get all config vars

- internal/ceb/exec.go
- internal/server/singleprocess/service_entrypoint.go
I could never reproduce this bug nor write a test for it since it was
racey in nature but eyeball-tracing I belive this is the fix.
Prior to this change, there was a scenario that could exist where
EntrypointExecStream would exit before the recv goroutine. When
EntrypointExecStream exited, it would close the event channel that the
recv goroutine sends to. If the recv goroutine simultaneously had a
message buffered, it could try to send to the closed channel.
With this change, we moved the channel close into the recv goroutine.
This way there is never a send-after-close possibility.
The one important detail is that the event channel MUST ALWAYS be closed
when the EntrypointExecStream exits, because closing this channel
signals to the client side (typically a CLI) that they should exit …
> internal/server: fix send-after-close possibility in exec

- internal/cli/main.go
- internal/cli/snapshot_backup.go
- internal/cli/snapshot_restore.go
This adds access to the snapshot API functionality. It supports reading and writing to and from files, as well as standard input and output.
Closes #682 
As we don't yet have a CLI testing framework, I've included the output from adhoc testing here for review:
```
~/hc-git/waypoint f-snapshot-cli*
❯ ./waypoint server snapshot
failed to open output: stdout is a terminal, refusing to pollute (use '-' to force)
~/hc-git/waypoint f-snapshot-cli* 36s
❯ ./waypoint server snapshot out1.snap
Snapshot written to 'out1.snap'
~/hc-git/waypoint f-snapshot-cli*
❯ less out1.snap
"out1.snap" may be a binary file.  See it anyway?
~/hc-git/waypoint f-snapshot-cli*
❯ ./waypoint server snapshot > out2.snap
~/hc-git/waypoint f-snapshot-cli*
❯ shasum out1.snap
cc4fd6cdc75e3da5f51f5664a310a75814052d34 …
```
> Add CLI commands to access snapshot functionality

- internal/cli/token.go
Fixes #884
This avoids the output being cut off in a narrow terminal.
> internal/cli: output token directly to stdout

- Dockerfile
- Makefile
This introduces a dedicated Make task to build the entrypoint and
modifies the Dockerfile to build it and copy it into our final image.
> Add waypoint-entrypoint to Docker image

- ui/app/components/actions/context.hbs
- ui/app/components/actions/context.ts
- ui/app/components/actions/invite.hbs
- ui/app/components/header/index.hbs
- ui/app/styles/_header.scss
Adds a new "Connect" button to the UI header that displays a popover containing the `context create` CLI command that is shown during the initial onboarding flow. This resolves #781.
> Add Connect item to UI header

- builtin/vault/freeport/freeport.go
I don't actually know how this happens and its not super important cause we only use this library for tests, but once in a very rare while we'd get a nil panic here so this fixes that.
> builtin/vault: nil check on freeport

- ui/app/routes/workspace/projects/project/app.ts
Issue: https://github.com/hashicorp/waypoint/issues/783 
I initially went down the rabbit hole of changing the polling pattern to avoid calling `model.refresh()`, and instead creating an Ember Concurrency task to wrap the model fetching instead. 
Then while debugging I realized the issue was probably caused by the model resolving partial data (creating "gaps" in the state as the UI refreshes). It turn out that using [`rsvp.hash`](https://api.emberjs.com/ember/release/classes/rsvp/methods/hash?anchor=hash), to wait for all promises to resolve, works just fine.
> Resolve polling flash in UI

- .circleci/config.yml
Files in `ui/lib` may change without a change to `yarn.lock`, causing the wrong cached assets to be built. 
This PR: 
- creates a md5 hash of `ui/lib` and outputs it to a text file 
- uses the hash of that file as an additional item on the Yarn cache key (redundant hash of a hash, I know, but Circle only allows `checksum` on a file)
- invalidates the build cache if `ui/lib` has any changes (or at least that's the plan)
The only important commit is https://github.com/hashicorp/waypoint/pull/901/commits/0537dceab6dedc47f9582f7a7a586f23ee637b63 , the other ones are whitespace changes to verify cache key behavior
> bust cache if ui/lib changes

- builtin/exec/platform.go
This commit ensures that the command configured to run for `exec`
respects the `dir` config option if defined, otherwise it will go back
to the default which is the src path.
Fixes #903
> builtin/exec: Respect `dir` if defined for deploy command

- internal/cli/base.go
- internal/cli/base_init.go
- internal/cli/install.go
- internal/cli/option.go
- internal/cli/runner_agent.go
- internal/serverconfig/config.go
- internal/serverconfig/config_test.go
- internal/serverinstall/docker.go
- internal/serverinstall/k8s.go
- internal/serverinstall/nomad.go
- internal/serverinstall/serverinstall.go
This adds a flag to `waypoint install` to install a runner. This is a hidden flag for now for dev work. I need this to work on runner-related functionality more easily for this release. 😄 
The `waypoint install` command grabs an auth token for the runner and calls a new `InstallRunner` platform installer function. This way the platform can install the runner and the runner can connect & auth to the server for registration.
Only Docker support for installing runners in this PR since this is still experimental. The K8S/Nomad implementation is a noop but would definitely be done prior to a release.
> Flag to install runner, support installing runner with Docker

- internal/serverinstall/k8s.go
- website/content/commands/install.mdx
- website/content/commands/server-install.mdx
- website/content/docs/upgrading/index.mdx
This temporary note in our upgrade guide will help users work around the issue prior to the next release.
> cli: match k8s image pull policy to k8s defaults

- website/.gitignore
- website/next.config.js
- website/package.json
this switches out our `robots.txt` approach for a `x-robots-tag` HTTP header to hide tip.waypointproject.io from search crawlers. in the near future, we'll clean up the implementation to be centrally managed by our `nextjs-scripts` package, but this direct implementation does the trick here.
> website: add http header to prevent tip indexing

- internal/cli/server_config_set.go
- internal/cli/snapshot_backup.go
- internal/cli/snapshot_restore.go
- internal/clisnapshot/snapshot.go
- internal/clisnapshot/snapshot_test.go
This pulls out the core snapshot logic from the CLI into its own package, so we can use the snapshot creation in our uninstall and upgrade functions.
> Refactor snapshot cli commands

- builtin/aws/ecs/platform.go
The old code would panic (see #873), this new version achieves the aim of the existing code, but in a bonus move, doesn't panic at all!
> builtin/aws/ecs: properly clamp the service name. Closes #873

- Makefile
This pull request just copies the `docker/mitchellh` make target to something more generic for building a waypoint server. I'm happy to remove the other targets if they aren't going to be used, but don't want to mess up anyones workflow by removing them yet :smile:
> Add a generic build target for waypoint server container

- internal/pkg/grpcready/grpcready.go
- internal/server/singleprocess/service.go
- internal/server/singleprocess/service_deploy.go
- internal/server/singleprocess/service_hostname.go
- internal/server/singleprocess/service_url.go
- internal/server/singleprocess/service_url_test.go
If the URL service is down, the server fails to startup. We should not behave this way.
This changes the server to attempt a blocking connection _once_. If that fails, we move to background retries. This will enable the server to come up when the URL service is down (though it may try the first blocking attempt for ~10 seconds). Additionally, logging is much improved here.
> Don't block server startup on URL service

- internal/ceb/log.go
This changes the ERROR message to a DEBUG and adds a new ERROR-level
message only if we failed to reconnect the log stream.
It is expected that long-running streams such as the log stream will be
disconnected periodically due to any number of reasons, but most
commonly a load balancer in the middle limiting connection times. In
this scenario, we quickly reconnect and its not an issue. It creates too
much noise to log every disconnect as an error.
However, if we fail to reconnect the log stream, it is an error that
should be noted.
> internal/ceb: quiet ceb log disconnection messages

- internal/cli/server_run.go
- website/content/docs/server/run/index.mdx
- website/content/docs/server/run/production.mdx
This adds flags to `waypoint server run` to specify custom TLS certs.
This doesn't expose this yet to `waypoint install`, but we can't even work on that now if this doesn't support it!
> internal/cli: flags to set a custom TLS cert for `server run`

- internal/cli/server_run.go
This change allows Firefox users to bypass the previous
`SEC_ERROR_REUSED_ISSUER_AND_SERIAL` error that blocked access to
the UI when a new server instance was installed or run locally.
> use random serial number per cert

- Dockerfile
- builtin/docker/auth.go
- builtin/docker/builder.go
- builtin/docker/img.go
- builtin/docker/pull/builder.go
- builtin/docker/registry_img.go
The diff is deceiving, this is more or less just copying similar logic from the Docker builder into the registry but calling `img pull` instead of `img build`. I also updated the Dockerfile to use an updated fork which has fixes for `img pull`
> builtin/docker-pull: support daemonless image pulls

- internal/client/project.go
While attempting to connect to a server, Ctrl-C was not working. This is
because we were using `context.Background` rather than the passed in
context when attempting to connect.
I don't know why we did this, it looks like a simple mistake from dev.
Verified that this makes Ctrl-C work properly for server connection.
Labeling for backport to 0.2.x.
> internal/client: use given context so it can be cancelled

- internal/cli/uninstall.go
By moving the platform check earlier, we avoid generating a snapshot
locally on disk if there are flag validation issues.
> internal/cli: make -platform required and do platform check earlier

- internal/ceb/app_config.go
- internal/ceb/ceb.go
- internal/ceb/exec.go
- internal/ceb/plugin.go
- internal/ceb/virtual.go
- internal/ceb/virtual_test.go
- internal/server/execclient/client.go
- internal/server/singleprocess/service_entrypoint.go
- internal/server/singleprocess/service_exec.go
- internal/server/singleprocess/state/instance_exec.go
This work lays the groundwork for the exec plugin, which will use the virtual CEB running inside a runner, with a VirtualExecHandler wired up to an exec function provided by the Deploy plugin.
> feature: Add CEB Virtual instance type

- internal/cli/help.go
This modifies our CLI help output to do two things:
1. We always highlighted commands such as "waypoint foo", but nested
subcommands "waypoint foo bar" weren't highlighted. This fixes
that.
2. Flags in the help text body such as -foo and -foo-bar are now
highlighted as well. This is only in the help text summary and not
the flag documentation itself.
Screenshots (sorry my colors are very muted so its hard to see):
Flag highlight (see -waypoint-hcl):
Nested subcommand highlight:
> internal/cli: colorize flags in help text and nested subcommands

- Dockerfile
With the recent img additions to waypoint server, gcc needs libseccomp
static available as well as pkg-config to properly build runc for img
against our forked copy.
Before these changes, the server fails to build:
```
=> CANCELED [imgbase 6/6] RUN ./autogen.sh --disable-nls --disable-man --without-audit     --without-selinux --without-acl --without-attr --without-tcb     --without-nscd     && make     14.0s
=> ERROR [imgbuilder 7/7] RUN make static && mv img /usr/bin/img                                                                                                                           13.8s
=> CACHED [builder  2/15] RUN apk add --no-cache git gcc libc-dev openssh                                                                                                                   0.0s …
```
> Include libseccomp-static and pkgconfig for building wp/server with img

- Dockerfile
Userid for waypoint inside waypoint server must remain at 100, otherwise
if the id changes and the server image is refreshed with a different id,
the waypoint user will fail to read boltdb with permission denied.
> Dockerfile: Ensure userid is 100 for waypoint server user

- internal/cli/main.go
- internal/cli/project_apply.go
- internal/cli/project_list.go
This introduces `waypoint project list` and `waypoint project apply` CLIs.
(Note: there is no `waypoint project delete` cause we don't yet support project delete. Once we do, we'll add that.)
The "apply" CLI behaves as we described in the RFC, it merges wherever possible and everything is optional. We also have a `-waypoint-hcl` flag that can be used to specify a path to a `waypoint.hcl` file that we use to source config. Additional CLI flags can still be provided when using the HCL file mode to override values in there.
Example full CLI command to enable Git (no HCL file used):
```
waypoint project apply \
-data-source=git \
-git-url=https://github.com/mitchellh/waypoint-test-app.git \
-git-auth-type=basic \
-git-username=github \
-git-password=abcd1234 \
example-python
```
> `waypoint project` CLI 

- internal/cli/install.go
Small PR to match the error messaging we give on `uninstall` if the `-platform` flag is missing.
> cli: more specific error msgs on install

- internal/serverinstall/docker.go
This commit updates the behavior of the docker server installer by
looking for any stopped waypoint server containers and attempting to
start it when the install command is invoked.
Fixes #925
> serverinstall/docker: Start waypoint server container if stopped

- builtin/aws/ami/builder.go
- website/content/partials/components/builder-aws-ami.mdx
Fixes #879 
Note: this bug moved from the `init` stage to the `build` stage. Verify by running `waypoint build`; you should see an output of `Resolved AMI: ami-04e229bcb91f0f16b`.
> builtin/aws/ami: require []string for aws-ami filters

- internal/cli/base.go
- internal/cli/server_upgrade.go
- internal/cli/uninstall.go
- internal/clisnapshot/snapshot.go
This pull request adds better error messaging to the user if they attempt to uninstall or upgrade an old Waypoint server that does not support snapshots.
It also fixes the `clisnapshot` package to preserve the original grpc status codes while still wrapping them with the snapshot operation specific message.
> internal/{uninstall,upgrade}: Better error message for when server does not implement snapshots

- go.mod
- go.sum
- internal/ceb/virtual.go
- internal/core/app_exec_test.go
- internal/server/singleprocess/service_entrypoint.go
- internal/server/singleprocess/service_exec.go
- internal/server/singleprocess/service_exec_test.go
This fixes a very specific edgecase where if the virtual side of the
exec handler sends an Exit message and then cancels the context in quick
succession, the server side may not see the message, only the context
cancelation. gRPC seems to prioritize the cancelation above pending
events, possibly because message sends are not guaranteed (the docs
state this).
The change then is to wait for the server side to close the stream after
the virtual side sends it's exit code. This means that the server side
is in control of seeing the messages and shutting down the stream.
We also can now simplify the handling of the ExecStream messages by
allowing server.Recv() to return any buffered messages even if the
context has already been canceled. Effectively, if we check that the
context the server …
> internal/{ceb,core,server/singleprocess}: Fix exec stream closure

- internal/server/singleprocess/state/project.go
- internal/server/singleprocess/state/project_test.go
We document that project-related APIs cannot be used for applications,
but previously we didn't preserve existing applications. If a user
called UpsertProject to modify an existing project it'd blow away all
their applications.
This couldn't be hit in the real world unless the user was using the API
directly, since `waypoint init -update` is the only thing that calls
this API and it always registers applications again.
But with future changes such as introducing server side waypoint.hcl and
future UI changes to modify projects, this would've become a big issue.
> internal/server/state: project put should not modify applications

- internal/serverinstall/k8s.go
- website/content/commands/install.mdx
- website/content/commands/server-install.mdx
- website/content/commands/server-uninstall.mdx
- website/content/commands/server-upgrade.mdx
This commit introduces the ability for users to specify a kubernetes
context on install/upgrade/uninstall. If left unset, it will use the
current environment kubernetes context, but if set, it will attempt to
use the context specified for the given serverinstall operation.
Fixes #928
> serverinstall/k8s: Allow using k8s context

- internal/cli/install.go
- internal/serverinstall/docker.go
If a server has been restarted with the install step, the bootstrap
token step will certainly fail due to the server already being
configured. This commit fixes that by attempting to use the default
context to see if its auth token is valid for the server. If not, fail
like it was going to fail. If it's valid, go ahead and use the default
context since its the one we're looking for for the restarted server
container.
Fixes https://github.com/hashicorp/waypoint/issues/1013
> internal/install: Attempt to use default context for auth token 

- internal/core/project.go
- internal/core/project_test.go
- internal/server/singleprocess/service_job.go
We removed this check because it introduces a chicken/egg problem with
onboarding a new project: the user needs to have the waypoint.hcl loaded
to queue a job (to know what apps are defined), but with remote GitOps
style builds, we need to queue a job first to load the waypoint.hcl.
By removing this check, we move to a "late binding" approach where
non-existent applications will still error, but later in the process
after the job starts running.
This is one in a series of likely small PRs targeting a better CLI user
experience for remote runner based workflows.
> Don't require app to exist on QueueJob

- internal/server/singleprocess/state/instance_exec.go
- internal/server/singleprocess/state/instance_exec_test.go
This fixes an issue where if we looped over instances in the order of
most to least loaded, they would ALL be candidates. We need to reset the
candidate list when we find a lower loaded value.
> internal/server/state: CalculateInstanceExec picks least loaded

- test-e2e/README.md
- test-e2e/cli_smoke.test.go
- test-e2e/docker_smoke_test.go
- test-e2e/k8s_smoke_test.go
- test-e2e/nomad_smoke_test.go
- test-e2e/run-test.sh
- test-e2e/util.go
This pull request adds the remaining supported server platforms for smoke tests. It also moves out the basic CLI test into its own file instead of living in just the docker tests.
> test-e2e/{nomad,k8s}: smoke tests for remaining server platforms

- internal/ceb/config.go
- internal/server/singleprocess/service.go
- internal/server/singleprocess/service_deploy.go
- internal/server/singleprocess/service_entrypoint.go
- internal/server/singleprocess/service_entrypoint_test.go
- internal/server/singleprocess/service_url.go
- internal/server/singleprocess/testing.go
At the server level, this sets us up completely for any scenario where
the URL service configuration changes. However, the CEB doesn't yet
support changing URL configurations (it ignores them once it has
initialized) so we only send down the URL config once we are ready.
Future changes will just be ignored.
> internal/server: send entrypoint URL config only when we get a token

- builtin/k8s/platform.go
This pull request introduces the ability to define resource limits for pods during deployment.
Tested with https://github.com/hashicorp/waypoint-examples/tree/main/kubernetes/nodejs
```diff
diff --git a/kubernetes/nodejs/waypoint.hcl b/kubernetes/nodejs/waypoint.hcl
index d3eb818..67ef4da 100644
--- a/kubernetes/nodejs/waypoint.hcl
+++ b/kubernetes/nodejs/waypoint.hcl
@@ -20,6 +20,13 @@ app "example-nodejs" {
deploy {
use "kubernetes" {
probe_path = "/"
+
+      resources = {
+        limits_cpu = "500m"
+        limits_memory = "512Mi"
+        request_cpu = "100m"
+        request_memory = "256Mi"
+      }
}
}
```
After a `waypoint up`, describing the pod deployed you can see the resources are updated:
```
Containers:
example-nodejs-01ex7nsq75ndyevxqrxajqb4rq:
Container ID:
Image: …
```
> builtin/k8s: Allow for defined resource limits for pods

- internal/cli/hostname_delete.go
A lil order-of-operations issue resulted in an unsightly panic.
Before:
```
❯ waypoint hostname delete
panic: runtime error: index out of range [0] with length 0
... trace ...
```
After:
```
❯ ./waypoint hostname delete
! hostname required for deletion
```
> Fix panic from `waypoint hostname delete` with no hostname specified

- internal/cli/main.go
This commit introduces a `-version` flag to `waypoint -version`. It also
overrides `-v` to print version instead of being verbose only in the
case where there is 1 arg.
> cli/main: Add -version flag for CLI version

- contrib/serverinstall/kind-k8s/README.md
- contrib/serverinstall/kind-k8s/configs/cluster-config.yaml
- contrib/serverinstall/kind-k8s/destroy-k8s.sh
- contrib/serverinstall/kind-k8s/setup-k8s.sh
This pull request updates the automated kind-k8s install to include a local registry container. This allows waypoint to push the app it builds locally and have k8s pull from the local registry.
> contrib/serverinstall: Setup local registry for kind

- internal/server/gen/mocks/waypoint_client.go
- internal/server/gen/mocks/waypoint_server.go
- internal/server/gen/server.pb.go
- internal/server/gen/server.pb.json.go
- internal/server/proto/server.proto
- internal/server/singleprocess/service_waypointhcl.go
- internal/server/singleprocess/service_waypointhcl_test.go
This introduces a new `WaypointHclFmt` RPC that just formats the given waypoint.hcl configuration.
The intention for this API is for the web UI to be able to use it to auto-format Waypoint configuration.
Open to discussion here.
> WaypointHclFmt API

- internal/cli/up.go
- internal/server/singleprocess/service_job.go
This just adds back the old "up" logic from 0.2.x as a fallback. Over
time, it is possible that the UX of these two diverge but I expect that
we'll see less and less of the old behavior as people upgrade.
> internal/cli: fall back to legacy "up" if server doesn't support op up

- builtin/docker/platform.go
This pull request introduces three new config options for the docker platform for deploys:
- Labels
- Networks
- Binds
It allows users to label their deployed container, as well as connect additional networks.
Fixes https://github.com/hashicorp/waypoint/issues/1064
> builtin/docker: Add Binds, Labels and Networks config options

- ui/app/components/app-breadcrumbs/index.hbs
- ui/app/components/app-breadcrumbs/index.js
- ui/app/styles/_breadcrumbs.scss
- ui/package.json
- ui/yarn.lock
@meirish released v0.4.2 of the `@hashicorp/pds-ember` addon with a large improvement to the production payload size. 
This PR upgrades the addon and fixes a minor regression with the breadcrumbs styles (and adopts the addon's styles for that component)
> UI: upgrade pds-addon to 0.4.2

- internal/runner/accept.go
- internal/runner/accept_test.go
- internal/runner/runner.go
- internal/server/singleprocess/service_runner.go
The old code had a race condition where it was possible to shutdown the runner while a job had just started and would have continued to run.
Because of the behavior around executing the runner within the client package as a local runner inside the CLI, this bug has likely never been hit. But a busy system running a standalone runner certainly would have.
> internal/runner: Fix race condition around runner shutdown

- internal/client/job.go
- internal/client/noop_test.go
- internal/client/project.go
- internal/runner/accept.go
This moves runners from being spawn per job to creating a single runner that runs for the lifetime of a client Project value. The reason for this change to make it possible for a server to spawn jobs on a CLI client in response to a client RPC call, rather than just when the CLI client queues the job itself.
We're going to be using this server spawned jobs function (future PR) to cleanup the API for exec and logs plugin functionality, allowing the server to decide if the plugin needs to be spawned or not, rather than the client.
> internal/{client,runner}: start a single runner at the start of the CLI

- builtin/aws/ecs/platform.go
- builtin/aws/ecs/releaser.go
rebased #693 and added a doc field for the additional config
closes #693
> rebase and fixup 693

- builtin/aws/ecs/platform.go
Makes this comment true
```
If there is only 1 target group, delete the listener
```
Closes #765
Smaller implementation of #795 and closes #795
> builtin/aws/ecs: fix listener deletion check

- internal/serverinstall/k8s.go
When attempting to install Waypoint into a namespace that does not exist, the `waypoint install` command will hang indefinitely. Errors are printed to screen, but the process never exits.
```
$ waypoint install -accept-tos -k8s-namespace=waypoint -platform=kubernetes
✓ Creating Kubernetes resources...
⠧ Waiting for Kubernetes StatefulSet to be ready...
! Error creating service namespaces "waypoint" not found
! Error creating statefulset namespaces "waypoint" not found
```
The error is checked and used to populate `ui.Output`, but it is not actually returned.
With this change, it fails correctly:
```
$ ./waypoint install -accept-tos -k8s-namespace=waypoint -platform=kubernetes
❌ Creating Kubernetes resources...
! Error creating service namespaces "waypoint" not found
! Error installing …
```
> k8s install: Return error creating service/statefulset.

- website/package-lock.json
- website/package.json
- website/pages/style.css
This PR bumps `@hashicorp/react-section-header` to a recently published version which does not process markdown within the component.
- [`/community`](https://waypoint-git-zsbump-components.hashicorp.vercel.app/community), should be identical to [live site](https://waypointproject.io/community)
> Bump react-section-header

- internal/config/funcs/vcs_git.go
Fixes https://github.com/hashicorp/waypoint/issues/978
I was able to reproduce #978 with this config and a local git repo with 2 tags, one in the past and one on the current `HEAD` :
<details>
```hcl
project = "example-nodejs"
app "example-nodejs" {
labels = {
"service" = "example-nodejs"
"env"     = "dev"
}
config {
env = {
TEST = "hiya"
REFHASH   = gitrefhash()
REFPRETTY = gitrefpretty()
}
}
build {
use "pack" {}
}
deploy {
use "exec" {
command = [ "echo", gitreftag() ]
}
}
}
```
</details>
The deploy output was always `echo ` (empty)
I dug in an found that `refTagFunc` was always hitting an `EOF` here (L157):
- https://github.com/hashicorp/waypoint/blob/298ec9289ea651bc80ca2c757bde7d325e1e70c7/internal/config/funcs/vcs_git.go#L148-L168
I dug in more and found a built-in iterator for …
> Fix empty gitreftag response (#978)

- website/content/commands/exec.mdx
- website/content/commands/install.mdx
- website/content/commands/server-install.mdx
- website/content/commands/server-uninstall.mdx
- website/content/commands/server-upgrade.mdx
- website/content/docs/getting-started.mdx
- website/content/partials/components/platform-aws-ecs.mdx
- website/content/partials/components/platform-docker.mdx
- website/content/partials/components/platform-kubernetes.mdx
- website/content/partials/components/releasemanager-kubernetes.mdx
- website/data/version.js
This PR generates all of the various component docs for the website off of the `release/0.2.x` branch. It also cherry-picks a docs update that should be included in stable website from main.
> website: Update docs from components for release

- builtin/k8s/api.go
- builtin/k8s/config_sourcer.go
This attempts to auth with K8S using in-cluster auth by default, unless
a kubeconfig file is explicitly specified. If we detect we're not in a
cluster, then we fall back to out of cluster auth.
This is particularly important for a GitOps and runner-based future where
we expect to be deploying to platforms like this from potentially within
the target cluster.
> builtin/k8s: support in-cluster auth

- go.mod
- internal/serverinstall/k8s.go
This commit removes the instance of using kubectl in favor of just using
the k8s client for installing a secrets file.
> serverinstall/k8s: Use k8s client over execing kubectl

- internal/ceb/ssh/server_test.go
This fixes a dropped test error in `internal/ceb/ssh`.
> internal/ceb/ssh: fix dropped test error

- builtin/docker/platform.go
Fixes https://github.com/hashicorp/waypoint/issues/687 by specifying a host port (for Docker deployments) instead of an empty string (Which leads to random port assignment).
> Fixes https://github.com/hashicorp/waypoint/issues/687

- builtin/aws/ecr/ecr.go
This does not need to be backported; it is only on `main`.
This resolves the error `argument cannot be satisfied: type *anypb.Any` received when using the `aws-ecr` registry.
> builtin/aws/ecr: use the ecr mapper

- builtin/docker/platform.go
- go.mod
This commit introduces the ability to configure a containers resources
limits around cpu and memory when deploying with docker.
Fixes #608
> builtin/docker: Introduce Resources map for configuring cpu, memory

- builtin/aws/lambda/platform.go
We need the region, it's used by the ALB to figure out where to set things up.
> Add missing Region value from Deployment

- builtin/nomad/platform.go
- internal/serverinstall/nomad.go
This commit incldues the platform option when installing nomad, because
the cli context config ends up being redefined if the server install was
successful.
> serverinstall/nomad: Set platform as nomad at end of Install 

- internal/server/singleprocess/state/app_operation.go
This commit returns a more descriptive error message when a non-existent
application is attempted to be deployed.
Fixes #973
Before:
```
brian@localghost:go % waypoint deploy -plain -app=FOO]
! none available
```
After:
```
brian@localghost:go % waypoint deploy -plain -app=FOO
! No application named "FOO" is available!
```
> internal/server: More descriptive error for unknown application deploys

- builtin/aws/ecs/platform.go
- website/content/partials/components/platform-aws-ecs.mdx
- website/content/partials/components/platform-docker.mdx
- website/content/partials/components/platform-kubernetes.mdx
- website/content/partials/components/releasemanager-kubernetes.mdx
This fixes two bugs.
One was our lack of a nil check on `logging` options in waypoint hcl.
The other was the aws error message we receive for `awslogs-endpoint`. I've submitted a ticket via their docs page and will update if/when I hear back. Until then, I don't want to hold up this bug fix.
> check for nil logging opts; remove endpoint

- builtin/aws/alb/releaser.go
The automatically created security group is created incorrectly if we use the auto-calculated port value, but we were also not honoring the Port value that the ALB defined.
> Honor the ALB config's port, but use the correct auto-calculated port

- internal/serverinstall/k8s.go
- internal/serverinstall/nomad.go
This fixes both Kubernetes and Nomad dropped errors in `internal/serverinstall`.
> internal/serverinstall: fix dropped errors

- internal/serverinstall/k8s.go
- internal/serverinstall/nomad.go
Overrides https://github.com/hashicorp/waypoint/pull/1144. Had to redo a commit because the original PR rebased code that wasn't meant for backport.
> Backport of internal/serverinstall: fix dropped errors into release/0.2.x

- builtin/k8s/deployment.go
- builtin/k8s/platform.go
This pull request introduces a couple of changes and enhancements for a kubeernetes deploy:
- Includes any user defined labels to apply to the app pod on deploy from the deploy stanza in a waypoint.hcl
- Duplicates the label `name` to be `app`. This fits with how we label `waypoint-server` pod, and will fit what is expected for other services that integrate with k8s such as Istio https://istio.io/latest/docs/ops/deployment/requirements/#pod-requirements
- Duplicates the namespaced waypoint id label as `version`, because `version` is an expected key that k8s integrations expect to have (also used by Istio).
Fixes #966
> builtin/k8s: Include user defined labels on deploy and add name/version labels

- builtin/pack/builder.go
Addresses https://github.com/hashicorp/waypoint/issues/942
Adds support for specifying multiple buildpacks with the `pack` plugin.
```
app "example-app" {
build {
use "pack" {
buildpacks = [
"./path/to/buildpack",
"heroku/nodejs",
"heroku/ruby",
]
}
}
```
> builtin/pack: support specifying buildpacks

- builtin/pack/builder.go
Missed the backport label on the original PR https://github.com/hashicorp/waypoint/pull/943, so doing a manual backport.
> Backport of builtin/pack: support specifying buildpacks into release/0.2.x

- ui/README.md
We had a few undocumented dependency requirements to build the server and the API ts definitions. This PR updates the UI README to make this process more consistent. I chose to keep them in the section rather than the `Prerequisites`, as one can start ramping up on the repo without those.
> Update readme with dependency instructions for the gen/ts command

- go.mod
- internal/server/singleprocess/service.go
- internal/server/singleprocess/service_url.go
This introduces an exponential backoff (up to 60s max wait) when the URL
service can't be initialized. Without this, we were spinning at nearly
100% CPU trying to reconnect, and I'm sure that's causing quite a lot of
network load on the service as well.
> internal/server: backoff on URL service not available

- internal/serverinstall/k8s.go
- nix/sources.json
- shell.nix
This adds Kubernetes support for runner management. 
I use a Deployment for runners since they have no state. 
The only sneaky thing here is that during uninstall of a runner, I grab the cpu and memory requirements of the last install and persist them so we can use them on the next install (in the same process) which happens during an upgrade. I do this because we don't ask for these flags for the upgrade command and I think we shouldn't, we should just copy the existing settings.
Most of the LOC in this PR is just extracting client initialization into a standalone function. 😄
> Kubernetes Runner Management

- go.mod
- internal/cli/project_apply.go
- internal/pkg/validationext/doc.go
- internal/pkg/validationext/error.go
- internal/pkg/validationext/error_test.go
- internal/pkg/validationext/rule_cidrblock.go
- internal/pkg/validationext/rule_cidrblock_test.go
- internal/pkg/validationext/rule_duration.go
- internal/pkg/validationext/rule_duration_test.go
- internal/pkg/validationext/rule_version.go
- internal/pkg/validationext/rule_version_test.go
- internal/pkg/validationext/struct.go
- internal/pkg/validationext/struct_test.go
- internal/server/ptypes/job.go
- internal/server/ptypes/project.go
- internal/server/ptypes/project_test.go
- internal/server/ptypes/ref.go
- internal/server/ptypes/workspace.go
- internal/server/ptypes/workspace_test.go
- internal/server/singleprocess/service_project.go
- internal/server/singleprocess/service_workspace.go
- shell.nix
This brings in the foundation for API input validation.
This copies in the `internal/pkg/validationext` package that we've extracted out of our other projects. This package helps to format validation errors in proto `status` formats using `InvalidArgument` and `fieldViolations` so callers can break down individual errors. This package also adds helpers for `ozzo-validation` to work nicely with deeply nested structs and proto-style "oneof" fields.
I've implemented workspace and project validation in this PR, but stopped there so we can PR the foundation and add more validation as we go.
An example of the format is below. This should be inspectable by UIs (@gregone) to provide nicer error formatting:
> API Input Validation Foundations

- internal/cli/install.go
- internal/cli/runner_agent.go
- internal/cli/server_upgrade.go
- internal/cli/uninstall.go
- internal/runner/accept.go
- internal/serverinstall/docker.go
- internal/serverinstall/k8s.go
- internal/serverinstall/nomad.go
- internal/serverinstall/serverinstall.go
- nix/sources.json
- shell.nix
This formalizes the runner management machinery: `waypoint install`, `waypoint server upgrade`, `waypoint server uninstall`, etc. RFC is [WP-053](https://docs.google.com/document/d/1im3U7iYtZLhKSjJKtqadNxJA0Ur3U30l70krz-b1WH4/edit#). 
This PR focuses on the machinery and **does not** implement Kubernetes or Nomad completely yet. I will make subsequent PRs for that. Docker is fully working since I used that for testing.
This PR also fixes a couple major bugs that manifested themselves and affect `main`:
* Runner accept loops (in two places) handle runner deregistration and server restarts more gracefully, namely by not DDoSing the server.
* Upgrade and uninstall do not start local servers, which prevents a local runner from starting up during these operations and DDoSing the server from …
> Runner upgrade/uninstall machinery, default runner install to true

- internal/datasource/git.go
- internal/datasource/git_test.go
The previous polling implementation only looked at HEAD. Users may
configure a separate Ref for their Git datasource, but the polling
didn't respect this.
This commit changes the polling to respect the Ref setting. The ref
setting can be in any format `git rev-parse` takes but only hash
references; caret refs and so on such as `HEAD~2` are not allowed.
> internal/datasource: Git polling respects Ref configuration

- builtin/k8s/releaser.go
When defining a ServicePort, TargetPort can be a string label _or_ it
can also be the port number. This commit fixes that by accounting for
when TargetPort is defined to be an int rather than a string label.
Fixes #987
> builtin/k8s/release: Allow target_port to be int or string

- internal/datasource/git.go
This fixes two bugs that prevented SSH auth from properly working with Git:
* If no "user" is specified, use "git" (which is what every public Git host I found uses)
* We have to disable host key verification since we have no way to set that up in runners.
With these changes, I verified locally that polling setup to use SSH with GitHub works.
> Fix a couple minor bugs in SSH auth with Git

- internal/cli/base.go
- internal/cli/base_init.go
- internal/cli/init.go
Fixes #717.
This is some approach to solve #717. It does 3 things:
* Rename the `from` struct field for `-from-project` to `fromProject` for consistency.
* Introduce the `-from` option and store it in the "new" `from` struct field.
* Read the configuration based on `-from` instead of `configpkg.Filename`.
Happy to hear your suggestions and improvements.
> Update -from-project to handle local projects

- builtin/k8s/releaser.go
This commit fixes a bug where a name is expected to be defined if more
than one port is configured for the release stanza.
> builtin/k8s: Include name field for service port release

- internal/cli/exec.go
- internal/server/ptypes/exec.go
- internal/server/ptypes/exec_test.go
- internal/server/ptypes/job.go
- internal/server/singleprocess/service_exec.go
One argument (the command to execute) is required. This validates it.
Without this, users would get exec just terminated with no message.
> Validate in CLI and serverside that exec gets at least one arg

- builtin/docker/platform.go
Reverts hashicorp/waypoint#918
This is required to allow `waypoint up` to continue to work beyond the first iteration. Without this, the second `waypoint up` fails with an error that there is already a container bound for the port requested.
For now we'll go back to leaving it randomly assigned, which supports waypoints deployment model here. We have plans in a future release for supporting mutable deployments, which should hopefully allow the original issue to be resolved. /cc @Wakeful-Cloud
> Revert "Fixes https://github.com/hashicorp/waypoint/issues/687"

- website/scripts/should-build.sh
Adding a script to be run during the site build process to determine if we should actually build.
More information on the feature: https://vercel.com/docs/platform/projects#ignored-build-step
> chore: adds should build script for website

- internal/ceb/app_config_test.go
- internal/ceb/virtualceb/ceb.go
This fixes dropped errors in `internal/ceb` and its subpackage `internal/ceb/virtualceb`.
> internal/ceb: fix dropped errors

- internal/cli/init.go
- internal/config/config.go
- internal/datasource/git.go
- website/content/docs/waypoint-hcl/runner.mdx
This was a small asymmetry I noticed when working on docs: we allow every other project setting to be configured in the waypoint.hcl file but didnt allow polling. This extends support for that and updates the docs.
> Allow poll settings to be configured in `runner` stanza

- ui/app/components/app-form/project-settings.hbs
- ui/app/styles/_x-toggle.scss
- ui/app/styles/app.scss
The default theme used for the toggle component wasn't passing accessibility standards. This updates the theme to have a higher contrast in the default state, and use the styleguide blue for the checked state. 
A next step would possibly be to re-export the addon with a fully customized style for consumption by the `pds-addon`, or more simply have a custom theme class, but this shoudl do for now.
> Use accessible values for toggle theme

- cmd/waypoint-entrypoint/debug.go
- cmd/waypoint-entrypoint/main.go
This adds functionality to dump a heap profile (in pprof format) when the entrypoint receives a SIGUSR1. The profile is written to the system temporary directory with a timestamp. The exact path that was dumped is logged. 
I hope to use this to debug #1192 and any future issues.
In the future, the team mentioned it'd be really cool if the server can request this information from an entrypoint and we can potentially use that to debug weird deployments. I think that's a good idea, but this is a simple thing we can do now and backport safely so I'm opening this PR first.
> cmd/waypoint-entrypoint: dump heap profile on SIGUSR1

- website/components/animated-steps-list/steps-indicator/StepsIndicator.module.css
- website/components/branded-cta/branded-cta.module.css
- website/components/features/Features.module.css
- website/components/footer/style.module.css
- website/components/homepage-section/HomepageSection.module.css
- website/package-lock.json
- website/package.json
Removes references to deprecated gray CSS properties and maps all gray colors to new brand values.
[_Created by Sourcegraph campaign `kstraut/product-sites-migrate-v3-gray-colors`._](https://sourcegraph.hashi-mktg.com/users/kstraut/campaigns/product-sites-migrate-v3-gray-colors)
Due to old imports of `react-global-styles` within `react-components`, the proper gray values will not show until we update `react-components` later on because the old style sheets are taking precedent.
```
// v2 gray css properties to new v3 values
"--gray-3" --> "--gray-2" 
"--gray-4" --> "--gray-3" 
"--gray-5" --> "--gray-4" 
"--gray-6" --> "--gray-5" 
"--gray-7" --> "--gray-6" 
// Replace Deprecated Gray Value references
"DEPRECATED-gray-:[~1|2]" --> "gray-1" 
"DEPRECATED-gray-:[~3|4]" --> "gray-2" …
```
> website(style): Update gray brand colors

- internal/cli/init.go
Small PR to fix typo noticed after generating CLI docs
> Fix typo in from-project flag doc string

- .changelog/README.md
- .changelog/changelog.tmpl
- .changelog/note.tmpl
- .github/workflows/changelog-checker.yml
- Makefile
This commit adds some essential template files for working with
`go-changelog`. It also includes a basic readme for how to generate the
proper CHANGELOG entries so that they can be generated with the tool.
Finally, it introduces a github workflow for checking when pull requests
forget to include a changelog file, with the option of being ignored if
the proper label is applied to the PR.
> Introduce go-changelog to Waypoint

- .changelog/1198.txt
- builtin/docker/plugin.proto
- builtin/docker/pull/builder.go
- go.mod
- go.sum
- internal/core/app_build.go
- internal/core/app_build_test.go
The main motivation for this PR is to enable a workflow where Waypoint is using an externally built image (such as from CI) without requiring `docker` or any privileges/namespaces even in a Dockerless environment (i.e. with `img`). 
Since `img` still requires user namespaces and user namespaces aren't enabled by default on most hosted K8S platforms, this enables a working Waypoint experience if the above two conditions are met, guaranteed. 
To make this work, I've exposed a named variable `HasRegistry` that builders can opt-in for (via the typical argmapper DI stuff, see the Docker implementation in this PR) to determine if there is a registry configured.
For Docker, if the CEB injection is disabled AND there is no registry, we don't pull at all.
> Expose `HasRegistry` bool to builder plugins, Docker doesn't pull if it doesn't have to

- website/components/nested-node/index.jsx
- website/components/nested-node/style.module.css
- website/pages/docs/[[...page]].jsx
this adds the ability to wrap text in `<NestedNode>` which will color the first item in object syntax as gray. this should be a marginal improvement for documenting nested API parameters
> website: stub in <NestedNode> authoring component

- .changelog/1193.txt
- internal/server/singleprocess/prune.go
- internal/server/singleprocess/service.go
- internal/server/singleprocess/state/app_operation.go
- internal/server/singleprocess/state/deployment.go
- internal/server/singleprocess/state/deployment_test.go
- internal/server/singleprocess/state/job.go
- internal/server/singleprocess/state/job_test.go
- internal/server/singleprocess/state/prune.go
- internal/server/singleprocess/state/prune_test.go
- internal/server/singleprocess/state/state.go
This limits deployments and jobs to 10,000 records each. The code only prunes the data from the memory indexes, it leaves in the disk.
The pruning of data is done on a regular interval rather than inline during data inserts (ie, it's like a typical garbage collection process). The pruning logic is shared between app records and jobs as well.
Pruning the data from disk would come later.
> internal/server/singleprocess/state: Add ability to prune jobs and deployments

- internal/core/app_exec_test.go
This fixes a dropped test error in `internal/core`.
> internal/core: fix dropped test error

- ui/app/styles/app.scss
the way that the link underlines was applied changed from `text-decoration: underline` to using `border-bottom` in the latest version of the pds-addon, so our override wasn't applied anymore. This brings it back to normal. 
before: 
after:
> remove excessive border decoration on links

- internal/server/singleprocess/service_logs_test.go
This fixes a dropped error in `waypoint/internal/server/singleprocess`.
> waypoint/internal/server/singleprocess: fix dropped test error

- .changelog/1246.txt
- builtin/k8s/platform.go
If you have a project that takes more than 30 seconds to initialize, currently the only way to deploy it is by modifying the liveness initial delay seconds through kubectl. This adds the option to the kube hcl
> Add option for initial probe delay, timeout, and failure threshholds

- ui/README.md
- ui/package.json
This sets a fixed node.js version to 12, as well as updating the README for setting up a local dev environment.
> update package.json and README for ui dev set up

- .changelog/1254.txt
- internal/config/eval_context.go
- internal/core/app_deploy.go
- internal/core/app_release.go
This fixes two major bugs in core that have likely existed since 0.2.0:
First, when creating a _default releaser_, we need to ensure all the same HCL variables are available as during a `deploy {}` block render, since the deploy plugin is what gives us our default releaser.
Next, when setting up HCL variables, we wouldn't respect parent scopes and lose anything that wasn't in the innermost scope. This fixes our config parsing to properly respect all those scopes.
> Make all deploy variables available in the DefaultReleaser setup

- .changelog/1255.txt
- internal/cli/app_docs.go
- internal/config/eval_context.go
- internal/config/funcs/datetime.go
- internal/config/funcs/datetime_test.go
I'm trying to put a date into my docker registry tags with `formatdate`, but I couldn't find a way to get the current timestamp. This code was copied from Terraform.
> Added "timestamp" HCL function

- ui/app/components/app-form/project-settings.ts
Addresses #1264
- defaults field value to `HEAD`
- if ref is deleted and left empty, API query sets it to `HEAD` anyway
> Default git ref to HEAD

- internal/config/config.go
- internal/config/validate.go
- internal/runner/operation.go
- ui/app/templates/workspace/projects/new.hbs
- ui/translations/en-us.yaml
- website/content/docs/waypoint-hcl/index.mdx
I noticed the UI had this little note:
And I didn't like it! The behavior when the projects didn't match was weird (it'd just _create_ a new project of that name on run) and this requirement to have the UI field exactly match something in the waypoint.hcl just was a poor UX.
This PR makes it so that the project field is optional for remote operations. If it is specified, the project name that invoked the operation _always takes precedence_. So even if the waypoint.hcl says `project = "foo"`, if you create a project in the UI named `my-website`, the operations and such will be associated with `my-website` and "foo" will be totally ignored.
You must still specify a `project` attribute for local operations, local `waypoint init`, etc.
> Project name is optional for remote operations (and does not need to match, either)

- ui/app/routes/workspace/projects/project/settings.ts
Fixes https://github.com/hashicorp/waypoint/issues/1268
Previously, the model would cache on the route, and not update properly, this fixes it by refetching when entering the route.
> refetch model on route reentry

- website/package-lock.json
- website/package.json
Remove the badges from the HCP products on the HashiStackMenu, as they are no longer needed.
[🔍 Preview](https://waypoint-git-brstackmenu-hashicorp.vercel.app/)
> Update the StackMenu to the latest

- ui/app/styles/_page.scss
Fixes https://github.com/hashicorp/waypoint/issues/1277
> wrap log output to container width (for breakable content)

- ui/app/styles/_input.scss
- ui/app/styles/app.scss
Fixes https://github.com/hashicorp/waypoint/issues/1262 
We'll do a better fix with `pds-addon` later
> Quickfix for input contrast in dark mode

- builtin/aws/lambda/platform.go
If the role was just created, the user can hit a eventual consistency condition within AWS where IAM said it was there but the Lambda services say the role is not there. We just have to retry it that case.
> Retry lambda function creation

- website/content/docs/waypoint-hcl/runner.mdx
Update documentation to show correct values in the runner stanza.
```hcl
runner {
enabled = true
data_source "git" {
url  = "https://github.com/hashicorp/waypoint-examples.git"
path = "docker/node-js"
}
}
> Update runner stanza with 'enabled' instead of 'enable'

- .changelog/1300.txt
- builtin/nomad/platform.go
Prior to this commit, the namespace config option was not used when
configuring a job for deploy. This commit fixes that by honoring the
namespace config value and using it for the job alloc.
> Fixes #1295: Use namespace config option when deploying nomad job

- internal/client/project.go
- internal/serverclient/client.go
When a new context is created and `-server-tls` is set to true, but `-server-tls-skip-verify` is false (default configuration!), the TLS options are not added to the GRPC dial options, causing (in my case) the following error:
```
$ waypoint context verify
! Connecting with context "dev"...
! Error connecting with context "dev": grpc: no transport security set (use grpc.WithInsecure() explicitly or set
credentials)
```
With this PR, the behavior is fixed and we're now able to connect to a TLS backend without a problem:
```
___waypoint_context_verify context verify
+ Context "dev" connected successfully.
```
> Fix GRPC TLS connect

- internal/core/app_deploy.go
- internal/core/app_deploy_destroy.go
- internal/core/app_release_destroy.go
This builds on #1254 which wasn't quite complete it turns out...
We need to also ensure that we render all the variables for workspace
destruction and "destroy all" operations.
This also changes the behavior slightly so that we render the Waypoint
config using variables based on the _latest_ deploy or release.
Previously, we'd use the deploy/release we were destroying. The issue is
that the configuration we have at the moment is only the current config,
so you could get waypoint.hcl parse errors if they used variables that
didn't exist at one point or another.
Practically, I'd like to update the SDK docs to note that during a
destroy operation you only have the config for the current config rather
than a point-in-time configuration. You should persist all state you
need onto your …
> internal/core: render all output variables for destroy phases

- .changelog/1320.txt
- internal/cli/server_bootstrap.go
Fixes #1314
The local runner requires an auth token to spin up so if we're
bootstrapping we should not do this on the bootstrap commands.
> internal/cli: server bootstrap should not spin up local runner

- .changelog/1330.txt
- cmd/waypoint-entrypoint/main.go
- internal/ceb/ceb.go
- internal/ceb/config.go
- internal/ceb/config_test.go
- internal/ceb/log.go
- internal/ceb/testing.go
- website/content/docs/entrypoint/index.mdx
- website/content/docs/troubleshooting.mdx
Fixes #1164
This changes the default log level to DEBUG, which is considerably more
quiet than TRACE but still provides ample debugging help for now while
the project is early.
The WAYPOINT_LOG_LEVEL environment variable can be set (even with
`waypoint config set`) to change this behavior at anytime.
> cmd/waypoint-entrypoint: default log level to DEBUG, env var to change

- Makefile
This also makes the command for generating the server proto more
discoverable.
> Makefile: Add target for generating server proto

- website/data/commands-nav-data.json
This is done so `fmt` and `docs` documentation pages show up on the website
> add docs and fmt to commands nav data

- internal/server/singleprocess/service_job.go
This improves the error message when a user tries to do a remote build
without a data source set, i.e. `waypoint build <project>/<app>`. This
is more common and I've seen two people hit it now that we support
runners.
> internal: update error message for data source not set

- builtin/nomad/platform.go
Since we have to pass through namespace as a ptr, if namespace is unset
then it gets dereferenced as empty string rather than nil, which means
the Nomad job api `Canonicalize()` doesn't end up setting a default
namespace. This commit fixes that by ensuring the namespace Waypoint
provides is set to a default.
> plugin/nomad: Ensure Namespace is set if not set by user

- .changelog/1299.txt
- builtin/nomad/jobspec/platform.go
- builtin/nomad/jobspec/plugin.go
- builtin/nomad/monitor.go
- builtin/nomad/platform.go
- internal/plugin/plugin.go
Builds on #1298. 
This introduces a plugin that can deploy to Nomad directly from a job specification file. This uses the mutable deployments functionality introduced in #1298. Example below:
```hcl
// The waypoint.hcl file
deploy {
use "nomad-jobspec" {
// Templated to perhaps bring in the artifact from a previous
// build/registry, entrypoint env vars, etc.
jobspec = templatefile("${path.app}/app.nomad.tpl")
}
}
// The app.nomad.tpl file
job "web" {
datacenters = ["dc1"]
group "app" {
task "app" {
driver = "docker"
config {
image = "${artifact.image}:${artifact.tag}"
// For local Nomad, you prob don't need this on a real deploy
network_mode = "host"
}
env {
%{ for k,v in entrypoint.env ~}
${k} = "${v}"
%{ endfor ~}
// For URL service
PORT = "3000"
}
}
}
}
```
> Nomad Jobspec Plugin

- .changelog/1318.txt
- builtin/nomad/platform.go
- internal/serverinstall/nomad.go
This commit introduces config options to use when defining a Server and
Runner nomad job config. If no option is specified, it will use the
configured defaults for Waypoint. This commit also increases the default
CPU in MHz to 200 and Memory in MB to 600 (double the default for Nomad
tasks)
It also introduces resources stanza for nomads deploy. Unlike the install for a server and runner, it sticks to the default resource size.
Fixes #1302
> {serverinstall/builtin}/nomad: Provide config values for memory and CPU

- .changelog/1364.txt
- internal/cli/base.go
- internal/cli/base_init.go
- internal/cli/init.go
- internal/cli/main.go
- internal/cli/version.go
- internal/client/project.go
- internal/client/server.go
- internal/serverclient/client.go
- internal/version/version.go
Fixes #1323 
This augments `waypoint version` to show the server version when available. This fails gracefully if the connection fails or there is no Waypoint server available. This command uses an arbitrary 2 second timeout so it doesn't block for a very long time if the connection is not working or taking a long time (unlike the CLI for other operations which will wait much longer).
> internal/cli: version shows Waypoint server version

- internal/cli/deployment_create.go
- internal/cli/releases_create.go
This commit fixes a bug where the release subcommand would print a
message about in place releases and generations. This is only true if
the deployment is mutable. It also looks to see if the geration id is
empty rather than if the whole struct is nil, since the value ends up
initialized but empty even with immutable deploys
> cli/{deploy,release}: Account for inplace deploys for release

- .changelog/1372.txt
- internal/cli/server_upgrade.go
Because `-auto-approve` and `-platform` are currently required flags for
using the server upgrade command, this commit modifies how we let the
user know about missing flags to prevent them from including one,
running the command, and seeing another is required. Doing both up front
should reduce the back and forth for when someone wants to run the
upgrade command. If neither are included, we also print the help text
for the upgrade command.
Fixes #1371
> cli/upgrade: Check for required upgrade flags and print better message 

- .github/workflows/check-unlinked-content.js
- .github/workflows/check-unlinked-content.yml
This PR adds a check for unlinked content. This check helps ensure that all files in `website/content` are included in `nav-data` and published as expected.
> website: add check for unlinked content

- .changelog/1401.txt
- builtin/aws/ecs/platform.go
- builtin/aws/ecs/platform_test.go
- builtin/aws/utils/validations.go
Since we've got a more complex relationship between the values that can be modeled in HCL tags, this introduces using ozzo to validate parts of the config struct.
> Properly validate the ECS ALB options. Fixes #1070

- .changelog/1403.txt
- builtin/aws/ecs/platform.go
- builtin/aws/ecs/platform_test.go
This PR adds the ability to request that a created ALB for ECS is internal scheme.
Closes #652.
> Add ability to request an internal ALB for ECS

- .changelog/1404.txt
- builtin/aws/alb/releaser.go
- builtin/aws/ami/builder.go
- builtin/aws/ec2/platform.go
- builtin/aws/ecr/registry.go
- builtin/aws/ecs/platform.go
- builtin/aws/ecs/releaser.go
- builtin/aws/lambda/ecs.go
- builtin/aws/lambda/platform.go
- builtin/aws/lambda/platform_logs.go
- builtin/aws/utils/session.go
I also considered setting aws's log function to be a proxy for hclog.Logger, but didn't because there are no levels on it, so it's best it shows up as just opaque output for the human to parse visually.
> Change the AWS log level to match the waypoint log level. Fixes #1319

- internal/cli/context_create.go
- internal/cli/context_delete.go
- internal/cli/context_rename.go
- internal/cli/context_verify.go
Previous output left the user confused as to what the actual problem was:
```
$ waypoint context create -server-addr=xxxxxx
! Global Options:
-app=<string>
...
```
Updated:
```
$ waypoint context create
! Usage: waypoint context create [options] NAME
Creates a new context.
Global Options:
...
```
> cli: give helpful error msg on context commands

- .changelog/1415.txt
- builtin/aws/ecs/platform.go
- builtin/aws/ecs/platform_test.go
- builtin/aws/utils/values.go
Closes #1163
This also enforces the memory and memory_reservation settings on the additional containers.
> plugin/ecs: Allow memory_reservation to be set on the main container

- .changelog/1317.txt
- builtin/k8s/deployment.go
- builtin/k8s/platform.go
This PR adds multiple new configuration options to the Kubernetes plugin, namely:
This commit adds the support for multiple scratch_paths:
```hcl
deploy {
use "kubernetes" {
image_secret = "regcred"
scratch_path = [
"/tmp",
"/var/cache"
]
}
}
```
and additionally adds support for pod configurations (for now
only limited to `security_context`):
```hcl
deploy {
use "kubernetes" {
pod {
security_context {
run_as_user = 1000
run_as_non_root = true
}
}
}
}
```
---
This commit adds the possibility to specify new config elements in the HCL file. With these additions is now possible to define a `container` block that can be used to specify:
- `command`
- `args`
In addition to this change, PodSecurityContext now supports the `fs_group` option.
This commit additionally adds a (maybe controversial?) …
> feat(builtin/k8s): Kubernetes improvements

- Makefile
Since https://github.com/hashicorp/waypoint/pull/1385 might be contentious or the wrong change entirely, I am opening a new PR for now to include the makefile target for generating plugin protos.
> Makefile: Add target for generating plugin protos

- .changelog/1426.txt
- internal/cli/runner_agent.go
This prevents a crash that could happen since during the error case conn
is nil.
> internal/cli: don't use conn if error during accept

- .changelog/1389.txt
- builtin/vault/internal/auth/gcp/gcp.go
Updates Waypoints' internal GCP auth to use GCP's IAM Service Account Credential endpoint for signing JWTs, as the IAM endpoint versions are deprecated and being turned off (not totally sure when but speculation/inference is around July 1, 2021). See https://cloud.google.com/iam/docs/migrating-to-credentials-api for more information on the deprecation and migration. 
I'm honestly not sure where this is used and there isn't a directly related test file associated with this, so I have not tested other than to ensure the project still compiles.
See also for more backstory:
- https://github.com/hashicorp/vault-plugin-auth-gcp/issues/100
- https://github.com/hashicorp/go-gcp-common/pull/4
- https://github.com/hashicorp/vault-plugin-auth-gcp/pull/108
- …
> Update internal GCP Auth to use new SignJWT endpoint

- .changelog/1346.txt
- builtin/docker/builder.go
- builtin/docker/img.go
This commit adds the support build args:
``` build {
use "docker" {
dockerfile="./simple_project/Dockerfile"
build_args=["TEST_PATH=.", "BIN_PATH_2=./.bin/app"]
}
}
```
> docker: support build args

- .changelog/1414.txt
- builtin/docker/platform.go
Addressing issue https://github.com/hashicorp/waypoint/issues/1390
- Added "extra_ports" following the same pattern used in `ec2`
builtin
QA:
- built waypoint binary
- added `extra_ports` to deploy paramater of a docker waypoint project.
- ran 'waypoint up' and confirm with `docker ps` that additional ports
are exposed in "PORTS" and then check that the ports are accesible
from the host.
$ docker ps
CONTAINER ID   IMAGE                                  COMMAND                  CREATED         STATUS         PORTS                                              NAMES
0391224e473d   waypoint.local/example-python:latest   "/waypoint-entrypoin…"   5 seconds ago   Up 3 seconds   0.0.0.0:32780->8080/tcp, 0.0.0.0:32779->8081/tcp   example-python-01F4WE89J68A9RTQR4D2AKNX3X
$ curl -I 0.0.0.0:32780 …
> Add ability to expose additinal ports for Docker

- .changelog/1393.txt
- builtin/k8s/releaser.go
I was looking to apply a AWS EKS load balancer configuration to the Service as described here, and implemented this change to support that: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/service/annotations/
> builtin/k8s: Allow to configure Service annotations

- .changelog/1443.txt
- internal/cli/server_config_set.go
Users are not clear that each flag to `server config-set` represents an individual value of a set, and that the set is what is sent to the server.
This PR improves the docs and UI to more clearly communicate to users what is happening.
> Be more explicit about what settings are being set. Fixes #686

- internal/cli/up.go
This commit fixes a UI output bug where Waypoint would declare the
deployment was mutable and deployed in place for immutable deploys due
to the inplace check not looking for generation id existing.
I apparently missed the up cli fix. For reference this was already fixed in deploy/release https://github.com/hashicorp/waypoint/pull/1366
> cli/up: Only print inplace deploy message if generation id exists

- .changelog/1123.txt
- builtin/google/cloudrun/platform.go
- builtin/google/cloudrun/validation.go
- builtin/google/cloudrun/validation_test.go
- website/content/partials/components/platform-google-cloud-run.mdx
Add additional configuration for Google Cloud Run.
Specifically, add options to specify connectible
CloudSQL instances, VPC Access Connector and the
type of the connector.
Reference: https://cloud.google.com/run/docs/reference/rest/v1/RevisionTemplate
> feat: Additional configuration for Google Cloud Run

- .changelog/1453.txt
- builtin/pack/builder.go
- go.mod
- go.sum
Utilizes the same code as the `pack` command line tool to provide a way to ignore files.
/cc @nateberkopec
> Add ignore field to pack. Fixes #1258

- .changelog/1458.txt
- internal/cli/base.go
- internal/cli/context_help.go
- internal/cli/context_inspect.go
- internal/cli/main.go
- internal/serverconfig/config.go
This adds a new `context inspect` command that helps users discover what the context actually is.
Additionally, it enhances the help text for `waypoint context` to include the main config path, since it's common that a user is going to be interested in that value if they're looking at the context help.
Fixes #1107
> Add context inspect (and better context help)

- internal/cli/main.go
Before
```
$ waypoint help
Welcome to Waypoint
...
Other commands
...
logs            Show log output from the current application deployment
project         
runner          Runner management
...
```
```
$ waypoint project -h
This command is accessed by using one of the subcommands below.
Subcommands:
apply    Create or update a project.
list     List all registered projects.
```
After
```
$ waypoint help
Welcome to Waypoint
...
Other commands
...
logs            Show log output from the current application deployment
project         Project management
runner          Runner management
...
```
```
$ waypoint project -h
Usage: waypoint project SUBCOMMAND
Project management.
Projects are comprised of one or more applications. A project maps 
to a VCS repository (if one exists). …
```
> internal/cli: add project help text

- Dockerfile
Currently `make docker/server` fails on arm64 (specifically an M1 Mac) because there isn’t an arm64 version of `img` available on the Alpine registry yet.
```
❯ make docker/server
DOCKER_BUILDKIT=1 docker build \
--ssh default \
--secret id=ssh.config,src="/Users/jamie/.ssh/config" \
--secret id=ssh.key,src="/Users/jamie/.ssh/config" \
-t waypoint:dev \
.
[+] Building 6.8s (10/41)                                                                                                                                            
=> [internal] load build definition from Dockerfile                                                                                                            0.0s
=> => transferring dockerfile: 4.36kB …
```
> Dockerfile: Remove `img` from `apk add` in `imgbase` stage

- go.mod
- go.sum
- internal/server/gen/server.pb.go
- internal/server/gen/server.pb.json.go
- nix/default.nix
- shell.nix
I noticed we were running generations with a different version than in the go.mod so this is an attempt to sync everything up.
> proto: update protobufs to latest versions

- .github/workflows/backport.yml
This PR adds a small backport-assistant configuration to backport any `backport/website` changes to the latest release branch. Previously, website changes were backported to `stable-website` if the `backport/website` label was applied but if it was not backported to the latest release branch, when the release was cut, it wouldn't contain those changes and would essentially 'revert' them. This will make sure that any docs changes that are picked with `backport/website` will also make it into the next release force-push from the release branch -> `stable-website`.
> ci: add backporting of docs to latest release branch

- Makefile
This is useful for me to be able to easily make exploratory changes and ship them to a linux server, and it seems only fair because we already have `make bin/windows`.
> Make command for a linux binary

- .github/workflows/backport.yml
We updated the `backport-assistant` image to include `curl` and `jq`. I also added a missing quote to close out the jq command I missed.
> ci: backporting fixes

- tools/tools.go
Without specifying a mockery package, nothing gets installed.
Without injecting the version via ldflags, mockery prepends the wrong version number (v1.0.0) to all of the mocks that it generates. I do not love hard-coding 1.1.2 in here, but this seems unlikely to change frequently and I don't see another path. Bash trickery inside `go:generate` seems to not work and would be a bit hacky anyway.
> Install the correct version of mockery.

- builtin/vault/internal/auth/aws/aws.go
- builtin/vault/internal/auth/gcp/gcp.go
- builtin/vault/internal/auth/kubernetes/kubernetes.go
`errwrap.Wrapf()` is deprecated, and recommends using `fmt.Errorf()`.
This PR replaces `errwrap.Wrapf()` throughout the subpackages of `builtin/vault/internal/auth`.
> builtin/vault/internal/auth: deprecate errwrap.Wrapf()

- .changelog/1538.txt
- internal/server/singleprocess/service_runner.go
Fixed the issue that caused these failures in CI:
- https://app.circleci.com/pipelines/github/hashicorp/waypoint/5710/workflows/1a5d72db-0c69-4873-b52b-9ba984ef6d03/jobs/43406
- https://app.circleci.com/pipelines/github/hashicorp/waypoint/4393/workflows/3c705bad-3280-4e46-91ab-9c22c1636ee5/jobs/31799
This was a tricky one to track down. From the failed tests, we can see that the client was receiving duplicate cancellation events. I was able to replicate the failed test by adding a sleep [here](https://github.com/hashicorp/waypoint/blob/35a9d6f2577957aeaa2c847fa6b2a53d295864d0/internal/server/singleprocess/service_runner.go#L281-L284).
Here’s what I think is happening:
There are three goroutines at play here.  One watching for DB changes and adding them to a channel …
> Fixes job cancellation bug hidden behind race condition

- ui/app/styles/_code.scss
- ui/app/styles/_page.scss
#1540 
**How the noted buggy icons look now with the fixes**
> UI: Fixed misaligned icons

- builtin/k8s/platform.go
- builtin/k8s/release.go
- builtin/k8s/releaser.go
- builtin/k8s/status_report_util.go
- go.mod
- go.sum
This pull request introduces a status report forwarder for the k8s platform. It inspects the deployed Pods and its containers to determine the overall health of a deployment or release.
Relies on https://github.com/hashicorp/waypoint-plugin-sdk/pull/32
> plugin/k8s: Add StatusFunc to Deploy and Release

- builtin/nomad/platform.go
This PR updates the docs to match the auth block that was initially added as a map in #646 and later changed to a block in #656
> builtin/nomad: update docs for auth block

- internal/cli/deployment_list.go
This commit adds a new column Health, in which we display the latest
generated status report for a given deployment. If no report is
available, either from old deployments or something else, we will just
display an Unknown status message.
> cli: Show last status report on latest deployment for list

- .changelog/1490.txt
- builtin/docker/builder.go
This commit adds the context support:
``` 
build {
use "docker" {
dockerfile = "../../projects/hamster/Dockerfile"
build_args = ["PROJECT_PATH=./projects/hamster"]
context = "../../"
}
}
```
> docker: support build context

- internal/server/singleprocess/service_exec_test.go
Fixes #1562
A 0.1 second delta is too tight for multi-tenant CI systems. For the
test logic itself, even a 1 second tolerance is absolutely semantically
fine. We just want to ensure the job is started expediently.
> internal/server: increase test delta tolerance to 1 second from 0.1

- builtin/docker/platform.go
- builtin/k8s/platform.go
- builtin/k8s/releaser.go
- builtin/nomad/platform.go
This commit adds some additional wordage in the case where a deployment
or release report was generated and its health is anything other than
READY. In some cases, a report that was generated immediately after the
deployment or release will be unhealthy given slow startup times, so this
warning adds some extra context for what the report means.
As an aside, this is one of the reasons why https://github.com/hashicorp/waypoint/issues/1497 will be very useful! This status output based on a StatusFuncs returned report could live in a single spot rather than duplicated across all plugins.
> builtin/{docker/k8s/nomad}: Add advisory message on non-ready reports

- internal/core/app_status_report.go
- internal/core/app_status_report_test.go
I don't think this is the *right* way to wire this information through, but it seems to work for now.
> Bug: adding release or deployment ID to the status report

- builtin/pack/builder.go
Buildpacks support multiple types of processes beyond the default, which is `web`.
Today the Waypoint `pack` plugin does not support that.
Fixes #598
> Pack Plugin support for non-default process types.

- internal/server/singleprocess/state/status_report.go
The max record value was global, not per deployment or release. So
foreach deployment or release, status reports were getting pruned. This
commit increases the limit to match deployment state limits.
> state/status_report: Increase max records for status reports

- .changelog/1596.txt
- internal/cli/deployment_list.go
Fixes #1595
CLI: built off branch
Server: 0.3.2
Before fix:
```
$ waypoint deployment list
! unknown method GetLatestStatusReport for service hashicorp.waypoint.Waypoint
```
After fix:
```
$ waypoint deployment list
| ID | PLATFORM |  DETAILS   |    STARTED     |   COMPLETED    |     HEALTH      
-----+----+----------+------------+----------------+----------------+-----------------
🚀 |  2 | docker   | artifact:2 | 48 seconds ago | 47 seconds ago | Unknown status  
✔  |  1 | docker   | artifact:1 | 54 seconds ago | 52 seconds ago | Unknown status  
```
> cli: ignore error if server doesn't have health checks

- website/data/alert-banner.js
---
Updates the alert banner data for HashiConf europe going live.
> chore: updates alert-banner — hashiconf eu

- .gitmodules
- Makefile
- internal/server/server.go
If there is a `vendor` folder at the project root, the Goland IDE ignores go modules and downloads all dependencies into that vendor folder. Until now, I've been working around this by deleting the vendor folder until I need to regenerate protobufs. Renaming `vendor` to `3rdparty` also makes us more consistent with waypoint-plugin-sdk.
I also added tests to the `make gen` commands to verify that the submodule has been initialized, and instructs you to do so if not.
> Enhancement: moving api-common-protos from vendor to 3rdparty

- internal/server/singleprocess/poll.go
- internal/server/singleprocess/poll_project.go
- internal/server/singleprocess/service.go
This commit refactors how the server queues poll operations. Initially,
we would only poll on projects. This commit refactors that behavior to
include an interface named pollHandler, which allows for more kinds of
items to queue poll jobs on.
One of the motivating factors for this work is to make the poller support different kinds of operations so that status reports (and other things) can be generated on an interval.
> internal/server: Refactor how server queues poll jobs

- .changelog/1628.txt
- internal/cli/hostname_list.go
Currently:
```
$ waypoint hostname list -h
Usage: waypoint hostname delete HOSTNAME
```
Fix:
```
$ waypoint hostname list -h
Usage: waypoint hostname list
```
Also
```
$ waypoint hostname -h
...
list        List all registered hostname.
```
Change `registered hostname` => `registered hostnames`.
> cli: Fix incorrect command help output

- .changelog/1631.txt
- go.mod
- go.sum
- internal/cli/server_run.go
- internal/client/server.go
- internal/server/singleprocess/service.go
- internal/server/singleprocess/state/app_operation.go
- internal/server/singleprocess/state/application.go
- internal/server/singleprocess/state/config.go
- internal/server/singleprocess/state/config_source.go
- internal/server/singleprocess/state/db.go
- internal/server/singleprocess/state/hmac.go
- internal/server/singleprocess/state/job.go
- internal/server/singleprocess/state/project.go
- internal/server/singleprocess/state/server_config.go
- internal/server/singleprocess/state/server_id.go
- internal/server/singleprocess/state/server_urltoken.go
- internal/server/singleprocess/state/snapshot.go
- internal/server/singleprocess/state/state.go
- internal/server/singleprocess/state/testing.go
- internal/server/singleprocess/state/workspace.go
- internal/server/singleprocess/testing.go
[Boltdb](https://github.com/boltdb/bolt) is no longer maintained, and causes intermittent test failures. Bolt also causes a runtime crash when attempting to run `go test` with the `-race` flag.
Etcd's bbolt is api-compatible with boltdb, and it's database file appears to be structurally compatible too. I've tested reading builds, config, deployments, jobs, projects, status reports, and releases created by `bolt`, and writing and reading new values with `bbolt`, and it all works as expected. 
There are no documented structural incompatibilities or related issues that I've found, and there are examples of [other](https://github.com/influxdata/kapacitor/commit/91b7bd7d29db8ece58bc557a2a8c49ad16338ae0) [projects](https://github.com/wakatime/wakatime-cli/commit/175ec848d36d3d29fd4aa1c144edddd5f …
> Upgrade bolt to bbolt

- ui/app/components/app-form/project-settings.ts
- ui/tests/integration/components/app-form/project-settings-test.ts
Fixes bug introduced with PR #1623 
- When a project is created with the CLI (`waypoint init`), you could not edit the project settings on the UI (received an error)
> ui: Added coverage of cli-generated project editing on dashboard

- .changelog/1650.txt
- builtin/k8s/platform.go
Looks like **0.4.0** release broke multi-port K8S configuration by setting `ServicePort = 3000` if it is not specified in the config. By forcing `ServicePort` to always defined, a multi-port configuration using `Ports` always fails the mutual-exclusivity check with the following error:
```
* Cannot define both 'service_port' and 'ports'. Use 'ports' for configuring multiple container ports.
```
This PR ensures the default port is used only if neither `service_port` nor `ports` is configured.
> builtin/k8s: Fix ‘ports’ configurability

- builtin/aws/alb/releaser.go
This was missing in the initial implementation of aws ALB status reports.
Also note: it looks like `ptypes.TimestampNow` has been [deprecated](https://github.com/golang/protobuf/blob/v1.5.2/ptypes/timestamp.go#L52) in favor of `timestamppb.Now`, so I'm using that here instead.
> plugin/aws/alb bug: adding generated time to ALB releaser status report

- Dockerfile
This is solving a current build crash when compiling shadow.
> Pinning alpine versions when docker building.

- .circleci/config.yml
- Dockerfile
- Makefile
This commit removes the injected ssh keys from the build process as well
as the various circle-ci jobs. It was originally added due to Waypoint
being a private repo and needing access to push the built container to
the alpha releases on github. Waypoint is no longer private, and now circle-ci
should still be able to push packages to github using the docker login step
instead.
We should probably backport this, but I'd like to wait until after this has merged and gone through the CI process. Just in case we have to revert. Our backport system can be applied most-merge now so waiting on applying the label isn't a huge deal.
> Dockerfile: Remove SSH key injection from circle-ci and dockerfile build

- .changelog/1669.txt
- internal/pkg/flag/flag_string_slice.go
- internal/pkg/flag/flag_string_slice_test.go
The flagset type of `StringSliceVar` does not correctly parse a comma separated string from input in the CLI.
Example:
```
$ waypoint server install -accept-tos -platform=ecs -ecs-subnets=subnet-f123,subnet-b456
```
Produced a value of: `[]string{"subnet-f123,subnet-b456"}` instead of the expected `[]string{"subnet-f123","subnet-b456"}`
Fixes https://github.com/hashicorp/waypoint/issues/1651
> Fix issue with parsing string slices from command line input

- ui/tests/helpers/a11y.ts
This is a confusing aspect of ember-a11y-testing. Right now, if you specify `exclude` you *must* specify `include` too. The library does not automatically set `include`, rather it assumes that you are now totally in control of the aXe context settings. Whether this is desirable or not is a question for the maintainers of the repo.
> ui/tests: specify `include` in global a11y setup

- ui/tests/helpers/a11y.ts
Thanks to #1672, we no longer need to exclusion.
> ui/tests: permit aXe to check iframes

- .changelog/1679.txt
- internal/config/funcs/template.go
- internal/config/funcs/template_test.go
The template functions are all defined with a variadic parameter to collect zero or more `vars` maps, but that means we need to be careful to handle the case where there are no `vars` maps at all.
This code seems to have originally been derived from Terraform's `templatefile` which has a non-variadic `vars, and so Terraform was correct to assume that argument 1 would always be present. Since Waypoint's version allows omitting it, we'll handle that situation by putting the "blame" on the template argument instead, to suggest that it's invalid to refer to any variables inside a template call that doesn't have any variables.
The previous incorrect result was originally a panic due to violating the contract HCL expects for `function.ArgError`, although hashicorp/hcl#472 addressed that by just …
> config/funcs: template functions to return valid ArgError values

- go.mod
- go.sum
This moves us to an unreleased version but this fixes a panic that
people are hitting today: https://github.com/hashicorp/waypoint/issues/1675
No changelog since we already added one for #1679 and this is part of the same fix (two diff bugs, but same look to users).
> Upgrade HCL to fix panic.

- builtin/docker/builder.go
- builtin/docker/img.go
We were previously constructing a string, but `exec/cmd` takes a LIST of
arguments that it passes directly to the exec syscall. The easiest way
to do this is to pass the build args config to buildWithimg and let that
func do its own data formatting to call it correctly.
No changelog because #1685 covers this.
> builtin/docker: pass build args into img in correct format

- .changelog/1690.txt
- internal/cli/init.go
- internal/server/singleprocess/state/project.go
The poll interval is not required and should default to 30s if not specified. This is handled on the `project apply` side by setting a default for the flag value. But if a user sets their runner config directly in the waypoint.hcl, then currently no default is set. This results in an error from `time`: `! time: invalid duration ""`.
This fix adds the default time duration in lieu of an empty string if the interval is not specified.
> cli: set default to 30s for runner polling

- website/content/partials/components/platform-exec.mdx
- website/package-lock.json
- website/package.json
- website/pages/style.css
👀 [Preview](https://waypoint-git-fork-zchsh-zsupgrade-code-block-hashicorp.vercel.app/docs)
This PR upgrades all MDX code snippets to use [our latest `code-block` component](https://github.com/hashicorp/react-components/pull/205), which contains a number of new features detailed in [[MKTG-035] Improvements to our Code Blocks](https://docs.google.com/document/d/1b2ROeAoy708dSqpJZjZRvuhJm9FB86skKEeQC3ZkLMY/edit?ts=5fadaaee).
We've also converted our `code-block` component to use CSS modules, which removes the need for global code-block related style imports.
> website: upgrade code-block

- builtin/docker/builder.go
- website/content/commands/hostname-list.mdx
- website/content/commands/server-upgrade.mdx
- website/content/partials/components/builder-docker.mdx
This commit removes a mistakenly added doc option `buildargs`. The actual option is `build_args`, and it's not required.
> Docs: Remove `buildargs` required parameter

- builtin/docker/builder.go
- website/content/commands/hostname-list.mdx
- website/content/commands/server-upgrade.mdx
- website/content/partials/components/builder-docker.mdx
The backporter [failed to cherry-pick](https://github.com/hashicorp/waypoint/pull/1703) these commits from [this PR](https://github.com/hashicorp/waypoint/pull/1703) so I am doing it now manually.
> Backport/docs/remove old doc with wrong info/release 04x

- .changelog/1708.txt
- internal/cli/runner_agent.go
- website/content/commands/runner-agent.mdx
From my reading, the Operation flags are not applicable to runner-agent.
Closes #1704
> Bug: remove Operation flags from runner-agent command.

- website/package-lock.json
- website/package.json
- website/pages/_app.js
- website/pages/_document.js
- website/pages/downloads/index.jsx
[Preview](https://waypoint-mhpjhd5uu-hashicorp.vercel.app/)
Upgrading `react-head` and dependencies to set the new Safari theme-color feature.
[_Created by Sourcegraph campaign `kstraut/upgrade-react-head`._](https://sourcegraph.hashi-mktg.com/users/kstraut/campaigns/upgrade-react-head)
**Before**
**After**
> website: upgrade react-head

- .changelog/1730.txt
- internal/serverinstall/k8s.go
Installing the waypoint server into a Kube cluster takes a flag `k8s-namespace` to install the server, however `uninstall` doesn't offer the same flag. As a result the uninstall process doesn't find the installation and instead gives a false positive successful destroy message. 
Here we accept `k8s-namespace` in `uninstall` and actually delete everything. 
Example before/after output in the details below
<details>
Before:
```console
$ waypoint version
CLI: v0.4.0 (3b3dd831)
Server: v0.4.0
$ waypoint server uninstall --platform=kubernetes -auto-approve -k8s-namespace waypoint
! flag provided but not defined: -k8s-namespace
$ waypoint server uninstall --platform=kubernetes -auto-approve
Uninstalling Waypoint server with context "install-1624910915"
✓ Snapshot …
```
> Allow users to provide k8s namespace for uninstall

- .changelog/1699.txt
- internal/ceb/ceb.go
- internal/cli/main.go
- internal/env/env.go
- internal/env/env_test.go
- internal/serverclient/client.go
- internal/util/env.go
- website/content/docs/automating-execution/index.mdx
- website/content/docs/entrypoint/disable.mdx
- website/content/docs/runner/run-manual.mdx
Previously, we were taking any value for boolean env vars to mean "true". If someone specified `WAYPOINT_SERVER_TLS=false`, we would take that to mean true. This fixes that.
Note on the implementation - I hate to be the person to introduce a generic "util" package. If anyone has any better ideas for where to put this little function, or feels like we should just strconv in-line every time, I am open to those ideas.
> Inspecting boolean env var values.

- .changelog/1710.txt
- internal/config/config.go
This addresses the panic within https://github.com/hashicorp/waypoint/issues/1704.
The problem here is that, if we embed a pointer to a private struct, and the private struct is nil, the caller has no way to determine if the embedded struct's values are safe to access.
This manifests here: https://github.com/hashicorp/waypoint/blob/124f4555ae306fb528adfaa65d39dfc72d41c075/internal/cli/base.go#L253
There is no way to determine of `c.cfg.Runner` is safe to access. `c.cfg` can be non-nil on its own, but it will _become_ nil when inspecting `c.cfg.Runner` if the embedded `*hclConfig` is nil.
A simplified example of the problem:
https://play.golang.org/p/sbAPT2HGJqW
If hclConfig is not a pointer, we won't get a nil pointer deference when looking at its fields.
I believe so - we don't have any …
> Not embedding hclConfig as a pointer.

- .changelog/1732.txt
- internal/cli/runner_agent.go
Gracefully quit the liveness listener if accepting a job errors and the context gets cancelled. Before this change, the liveness server would continue to operate and spew errors in the logs.
Example based off my findings from debugging  https://github.com/hashicorp/waypoint/issues/1398:
<details>
Before:
```
2021-06-24T17:58:03.538Z [INFO]  waypoint.runner.agent: initializing the runner
2021-06-24T17:58:03.538Z [INFO]  waypoint.runner.agent: starting runner
2021-06-24T17:58:03.538Z [DEBUG] waypoint.runner.agent.runner: registering runner
2021-06-24T17:58:03.539Z [TRACE] waypoint.runner.agent.runner: runner connected, waiting for initial config
2021-06-24T17:58:03.541Z [INFO]  waypoint.runner.agent.runner: runner registered with server
2021-06-24T17:58:03.541Z [DEBUG] …
```
> Runner: Listen for context cancellation and exit liveness listener

- .changelog/1735.txt
- internal/server/grpc.go
- internal/serverclient/client.go
Depending on the environment, certain network load balancers et. al. may terminate idle connections if no activity is detected after some time. EKS specifically uses a classic load balancer for the Waypoint server service and will by default terminate connections after 60s of inactivity. This results in the waypoint runner crash loop shown in #1398.
In this PR we configure [keepalive][grpc-keepalive] properties on both the server and the client, to maintain the connection even if there is no activity in the stream. I believe these are the only 2 locations where the client is created, but please let me know if I missed on. 
*Note: the numbers used here are fairly arbitrary and worked for AWS EKS. The client `Time` has a minimum of 10s. From my testing it needs to be greater than the server …
> Server/client: Add keepalive to RPC connections

- .changelog/1709.txt
- internal/config/app.go
- internal/config/eval_context.go
This commit adds the ${app.name} variable, so that can have
use for generation strings for anything, for example
```
project = "nutcorp"
app "hamster" {
config {
env = {
APP_NAME = "${app.name}"
ENV = "dev"
}
}
build {
use "docker" {
dockerfile = "../../../projects/${app.name}/Dockerfile"
build_args = {
PROJECT_PATH="./projects/${app.name}"
}
context    = "../../../"
}
registry {
use "aws-ecr" {
region     = "us-east-2"
repository = "nutcorp-${app.name}"
tag        = "latest"
}
}
}
}
app "vole" {
config {
env = {
APP_NAME = "${app.name}"
ENV = "dev"
}
}
build {
use "docker" {
dockerfile = "../../../projects/${app.name}/Dockerfile"
build_args = {
PROJECT_PATH="./projects/${app.name}"
}
context    = "../../../"
}
registry {
use "aws-ecr" {
region     = "us-east-2"
repository = …
```
> add app name variable

- .changelog/1723.txt
- builtin/nomad/platform.go
This fixes a dropped `err` variable in `builtin/nomad`.
> builtin/nomad: fix dropped error

- .changelog/1713.txt
- ui/app/components/actions/deploy.hbs
- ui/app/components/actions/release.hbs
- ui/app/components/app-card/build.hbs
- ui/app/components/app-card/deployment.hbs
- ui/app/components/app-card/release.hbs
- ui/app/components/app-item/build.hbs
- ui/app/components/app-item/deployment.hbs
- ui/app/components/app-item/release.hbs
- ui/app/templates/workspace/projects/project/app/build.hbs
- ui/app/templates/workspace/projects/project/app/deployment.hbs
- ui/app/templates/workspace/projects/project/app/release.hbs
Addresses #1513 
- Removed the instances of the build/deployment/release ID hash in the UI
- Updated the CLI hints to utilize sequence numbers instead of ID (see last screenshot)
- Updating the URL of individual build/deployment/release to use sequence number
- Creating a tooltip/UI for displaying the ID and allowing users to copy to clipboard
> Removed references to id in favor of seq #

- .changelog/1761.txt
- go.mod
- internal/server/grpc.go
- internal/server/http.go
- internal/server/server.go
This addresses the panic described in https://github.com/hashicorp/waypoint/issues/1476.
We need to create the grpc server first, but close the http server first, which run groups do not allow for. This removes the run groups and manages grpc and http server struct lifecycles directly.
Closes #1476
> Managing grpc and http server agents manually

- internal/server/singleprocess/service_logs_test.go
This test has failed multiple times today due to a timeout. This commit
bumps the timeout to decrease test flake failures in CI.
From circle:
> TestServiceGetLogStream_depPlugin - github.com/hashicorp/waypoint/internal/server/singleprocess
```
=== RUN   TestServiceGetLogStream_depPlugin
2021-07-07T21:55:16.142Z [INFO]  poll_queuer.project: starting
2021-07-07T21:55:16.142Z [INFO]  poll_queuer.application_statusreport: starting
2021-07-07T21:55:16.142Z [INFO]  prune: starting
2021-07-07T21:55:16.142Z [INFO]  http: HTTP listener not specified, HTTP API is disabled
2021-07-07T21:55:16.142Z [INFO]  grpc: starting gRPC server: addr=127.0.0.1:40895
2021-07-07T21:55:16.143Z [INFO]  grpc: /hashicorp.waypoint.Waypoint/BootstrapToken request
2021-07-07T21:55:16.143Z [INFO]  grpc: …
```
> test: Increase timeout due to slow circle-ci

- builtin/exec/platform.go
- builtin/pack/builder.go
- website/content/commands/index.mdx
- website/content/partials/components/builder-pack.mdx
For the last few releases, we've been massaging these mdx files by hand at the last minute, because our automation produced broken mdx files. With these changes, the automation produces good mdx files.
Here's what the pack/builder complex docs section looks like after this change:
index.mdx also had some minor whitespace changes that i'm not going to question too much.
> Fix the exec/platform and pack/builder docs

- Makefile
Previously, our release docs called for us to generate the website-mdx and cli docs manually. These generate huge diffs, because we rely on a pre-commit hook to format them for us.
This simplifies website mdx generation to 1 command. It also runs the same formatter that the pre-commit uses, so you can inspect your changes before you commit, which would have been very useful over the last few releases.
Corresponding docs change: https://github.com/hashicorp/waypoint-releases/pull/39
> Adding make command to generate and format website mdx files

- internal/config/app_config.go
We allow `null` default values for input variables since a user may want to run a specific stage without setting values for all stages.
This leaves open the possibility for the config to attempt to evaluate null values. This fix captures one such panic.
Before:
```
$ waypoint deploy
» Deploying...panic: value is null
goroutine 22 [running]:
github.com/zclconf/go-cty/cty.Value.AsString(0x3239728, 0xc00012c24b, 0x0, 0x0, 0x3239728, 0xc00012c24b)
/home/rae/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/value_ops.go:1259 +0x185
...
```
After:
```
$ waypoint deploy
» Deploying...
! could not evaluate "SALE_PERCENT" in app config with `null` value
```
waypoint.hcl from `waypoint-examples/learn/static-application-configuration`:
```
project = "example-go"
app "example-go" {
labels = {
"service" …
```
> cli: friendlier error handling on input variable panic

- internal/config/variables/testdata/no_default.hcl
- internal/config/variables/variables.go
- internal/config/variables/variables_test.go
Writing docs is a great way to find bugs!
Before, we were checking if the key existed for a variable (which it always will at this point; error handling for missing keys is earlier). Now, we are actually checking if the value is nil or not.
Before:
```
$ waypoint init
⠙ Validating configuration file...panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xe17198]
goroutine 67 [running]:
github.com/hashicorp/waypoint/internal/config/variables.Values.values(0xc000964030, 0xc000b13b78)
/home/rae/waypoint-project/waypoint/internal/config/variables/variables.go:592 +0xb8
```
After _(note the links for [docs] is still WIP and is OK for now)_:
```
$ wdi
✓ Configuration file appears valid
✓ Connection to Waypoint …
```
> core: fix error handling to check for nil value

- ui/ember-cli-build.js
- removes duplicated svg paths for svgJar
- removes unused config for ember-inline-svg (unused since we removed it in https://github.com/hashicorp/waypoint/pull/1534)
I mistakenly added both the `/images` and `images/icons` paths to the `svgJar` configuration, mimicking the ones found for [the `svg` config](https://github.com/hashicorp/waypoint/blob/main/ui/ember-cli-build.js#L39) (previously used for ember-inline-svg) and those were causing build warnings:
> remove duplicate svg path used in svgJar

- .changelog/1822.txt
- internal/server/ptypes/job.go
- internal/server/ptypes/job_test.go
This adds more validation to ensure that the path specified for a git
repository is what we expect. There are no bugs I've seen related to
this and users seem to be using subpaths fine, but working on #1821 made
me realize the need to be confident our paths are normalized.
> internal/server: harden git path validation

- .changelog/1836.txt
- ui/app/components/app-card/deployment.hbs
- ui/app/components/app-card/release.hbs
- ui/app/components/app-item/deployment.hbs
- ui/app/components/app-item/release.hbs
- ui/app/components/latest-release-url/index.hbs
- ui/app/helpers/enforce-protocol.ts
- ui/app/templates/workspace/projects/project/app/deployment.hbs
- ui/tests/integration/helpers/enforce-protocol-test.ts
Fixes https://github.com/hashicorp/waypoint/issues/1834 
Following https://github.com/hashicorp/waypoint/issues/1827 it seems that URL formatting is not consistent and correctly enforced on the backend. This PR adds a `enforce-protocol` helper to make sure protocols are always added to URLs before displaying them as links. 
This is an interim fix, and as discussed with @briancain yesterday, the URLs should be consistent on the server, and we *should not* be using this helper. 
here's the plan:
> Add enforce-protocol helper

- .changelog/1849.txt
- internal/cli/base.go
- internal/cli/base_test.go
This introduces a heuristic for detecting flag usage after positional
arguments. This is an error for the stdlib flag package that we use.
This has come up many times before (see #1510) and I believe this will
make the experience smoother.
**Note:** I plan on writing tests for this check function, but want to gauge interest.
Example:
> internal/cli: detect flags after positional args and error

- internal/server/ptypes/user.go
- internal/server/singleprocess/state/user.go
This adds some restrictions to the username characters. I've somewhat arbitrarily chosen the same restrictions as GitHub.com usernames for now. It is easier to loosen restrictions over time than tighten them so this gives us something to start with.
> internal/server: restrict username valid characters

- .changelog/1848.txt
- internal/cli/login.go
This builds on `waypoint login` introduced in #1831 for OIDC to provide a much nicer token-based login experience.
Prior to this, users had to use `waypoint context create` and specifically had to use a _login_ token with that. If they had an _invite_ token, they first had to convert it using `waypoint token exchange`. This is all friction and not obvious to users (though the underlying machinery is important).
Users can now use `waypoint login` with just the server address and ANY token and the CLI automatically does the right thing. It checks if the token is an invite token and automatically exchanges it. It also infers all the TLS and server connection settings based on the hostname (same as OIDC).
https://user-images.githubusercontent.com/1299/125501910-bd673d5f-7221-43a3-a732-057e2210 …
> internal/cli: waypoint login supports tokens

- .circleci/config.yml
- internal/cli/app_docs.go
- internal/cli/docs.go
- internal/cli/install.go
- internal/cli/server_upgrade.go
- internal/cli/uninstall.go
- website/content/commands/artifact-build.mdx
- website/content/commands/artifact-push.mdx
- website/content/commands/auth-method-delete.mdx
- website/content/commands/auth-method-inspect.mdx
- website/content/commands/auth-method-list.mdx
- website/content/commands/auth-method-set-oidc.mdx
- website/content/commands/build.mdx
- website/content/commands/deploy.mdx
- website/content/commands/deployment-deploy.mdx
- website/content/commands/deployment-destroy.mdx
- website/content/commands/deployment-list.mdx
- website/content/commands/destroy.mdx
- website/content/commands/docs.mdx
- website/content/commands/install.mdx
- website/content/commands/login.mdx
- website/content/commands/plugin.mdx
- website/content/commands/release.mdx
- website/content/commands/server-install.mdx
- website/content/commands/server-uninstall.mdx
- website/content/commands/server-upgrade.mdx
- website/content/commands/up.mdx
- website/data/commands-nav-data.json
This PR introduces a new circleCI workflow which runs `make gen/website-mdx` and verifies there were no changes.
In practice, this means that after making a change to our docs strings, we will need to generate mdx files and validate that the website pages look acceptable before CI will pass. It will prevent us from having to perform this step at release-time.
**NOTE**: The circleCI check here is intentionally failing on the new gen/website-mdx check, so that you all can see what it looks like. If we approve this PR, I'll run `make gen/website-mdx` and commit to clear the check.
This also includes a few related changes:
Our platform options were randomly ordered before, which would have made this check unreliable. Changes to `cli/install.go`, `cli/server-upgrade.go`, and …
> Verify no mdx changes during circleCI runs

- .changelog/1864.txt
- internal/cli/main.go
- internal/cli/token.go
- internal/cli/user_inspect.go
- internal/cli/user_invite.go
- internal/cli/user_modify.go
- internal/cli/user_token.go
This introduces a "waypoint user" CLI that is more user-oriented. This deprecates `waypoint token`. I kept the `waypoint token` command around so it works still but it is now hidden.
This exposes the user system introduced in #1752 and available as part of #1831.
> "waypoint user" CLI

- internal/clicontext/config.go
- internal/clicontext/config_test.go
We use net/url.parse which requires a valid URL. We do some sniffing to
try to turn common values into valid URLs. This is backed up by tests.
> internal/clicontext: parse 127.0.0.1:1234 correctly for server addr

- .changelog/1868.txt
- internal/server/singleprocess/service_logs.go
We were creating a new "ws" variable meaning that we'd enter an infinite
loop since the last watchset would constantly refire. This is super
subtle not sure how to make it safer.
I added a bunch more logging as well so that if this doesn't fix it we can
better trace what's going on.
> Add logging for log streaming, potentially fix infinite loop case.

- .changelog/1886.txt
- internal/serverinstall/k8s.go
Fixes #1795
If a user does not specify a `-k8s-server-image` or `-k8s-pull-policy` on the initial install, then we default to K8S defaults, which is to use an imagePullPolicy of `Always` for images tagged `latest`. Rather than force a restart of the pod during a `waypoint upgrade`, we are adding a note in the CLI output to alert users to these settings so they can take appropriate action per their cluster settings and needs.
```
$ waypoint server upgrade -platform=kubernetes -auto-approve
✓ Context "install-1626724718" validated and connected successfully.
✓ Snapshot of server written to: 'waypoint-server-snapshot-1626728262'
» Upgrading...
Waypoint server will now upgrade from version "v0.4.0-663-g4bc86276"
✓ Gathering information about the Kubernetes cluster...
⚠️ Update Strategy is …
```
> serverinstall/k8s: update log msg and add terminal warn for RollingUpdate

- .changelog/1895.txt
- internal/serverinstall/nomad.go
We had the wrong target for the nomad memory flags - it was overwriting CPU config.
> Bug: allow nomad runner and server memory to be configurable

- .changelog/1872.txt
- builtin/aws/ecs/platform.go
- builtin/aws/utils/validations.go
- builtin/aws/utils/validations_test.go
- internal/serverinstall/ecs.go
AWS ECS / Fargate require the memory and cpu values for containers to be agreeable, and will error when trying to create a container or task definition if they do not match the prescribed values. See this article for more information:
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
The Waypoint ECS deployment already validated these to a point, but the ECS Server install did not. This PR refactors that validation into a shared utility and uses it for both the platform and server install.
UX for using bad memory value in an ECS deploy:
UX for using bad memory / cpu values for server install:
> AWS ECS: validate memory + cpu pairs

- internal/server/singleprocess/auth.go
- internal/server/singleprocess/state/user.go
- internal/server/singleprocess/state/user_test.go
Runners and deployments currently use the default user for API calls
(Runner or Entrypoint API). We need to support the concept of a "service
account" for each of these that we don't currently support today.
For now, we'll prevent deleting this user. You can update the user if
you want cause all that matters is the ID and the ID is immutable.
> internal/server: disallow deleting the default user

- internal/plugin/plugin.go
`ssm` and `vault` were being imported twice each in `internal/plugin`. This fixes that.
Could someone add a "no-changelog" label?
> internal/plugin: fix muliple imports

- internal/server/singleprocess/service_job.go
- internal/server/singleprocess/state/job.go
- internal/server/singleprocess/state/job_test.go
This exposes `queueJobMulti` in `internal/server/singleprocess` and modifies the state store to support queueing multiple jobs transactionally: either all queue, or all do not queue. This is useful in @briancain's queueing work and probably useful in the future as well.
I chose to not expose this publicly as an RPC API since we don't need it right now, but all the primitives are there for when we do.
> Internal function to queue multiple jobs transactionally

- .changelog/1937.txt
- builtin/docker/builder.go
- go.mod
- go.sum
Fixes #1056
We observed that we could replicate #1056 on most of the example repos by enabling buildkit. The failure seems to be governed by the FROM image, but isn't consistent - on my machine, `FROM nginx:stable` would be fine, but wouldn't work for @xiaolin-ninja. In any case, the error mentions not having a session, and this change fixes it.
The docker CLI's usage of moby sessions is _much_ more sophisticated than this. If you're curious, [here](https://github.com/docker/cli/blob/13e4a097ea4cd6df652c5f57f68771fe526fcb1d/cli/command/image/build_buildkit.go#L50)'s where to start reading. Things they are doing that we are not include:
- Generating a session name based on the build context dir, not statically: https://github.com/docker/cli/blob/13e4a097ea4cd6df652c5f57f68771fe526fcb1d/cli/ …
> plugin/docker: Adding a session when building with buildkit

- internal/cli/auth_method_set_oidc.go
- internal/cli/project_apply.go
- website/content/docs/server/auth.mdx
Our other commands that include a `NAME` after `[options]` capitalize it (e.g. `waypoint context delete [options] NAME`)
Note: related bug #1976
> docs: broken link and caitalization consistency

- internal/server/singleprocess/service.go
Prior to this commit, the TOS for using the URL service in Waypoint
would always be true, regardless of the request. This commit fixes that
by respecting the argument passed through.
Note that the CLI server_run would error out before this reuqest if the flag
was false, so we were not auto-accepting despite the function always setting
the terms to true.
Fixes #1843
> internal/server: Respect TOS flag for using URL service

- ui/README.md
This small, but important step after running `make gen/ts` was missing, and causing some mistakes.
> Add further instructions to readme

- .changelog/1984.txt
- internal/serverinstall/ecs.go
Improve ECS Server uninstall by getting the full list of tagged resources, and handling "not found" type errors when destroying resources. This PR also removes the code that was used to tag ELB Listeners and EFS Access Points. The purpose of the tags is for use in AWS Resource Manager queries to find all the tagged resources, and at this time those 2 resource types [are not currently supported][awsrm]. This is deemed safe because the resource identifiers that would be associated with those tags are not used themselves during server uninstall; they are cleaned up during the process of cleaning up their parent resources (Network load balancer and EFS file system, respectively). 
- Check full paginated list of tag based search results
- Bump the time allowed for the security group to be free …
> Improve ECS Server uninstall

- builtin/k8s/releaser.go
- go.mod
- go.sum
- internal/core/app_release.go
Depends on https://github.com/hashicorp/waypoint-plugin-sdk/pull/49
Releases can declare resources too! Now that we've proved out the pattern with deployments, this makes the declared resources component outparam available to release functions.
It also updates the k8s releaser to use the new declared resources
Run a kubernetes deployment (i.e. run `waypoint up` from within https://github.com/hashicorp/waypoint-examples/tree/main/kubernetes/nodejs), then use grpcurl to view the api response for the releases like so:
```
SEQ_NUM=1; grpcurl -d '{"ref": {"sequence": { "application": {"application": "example-nodejs", "project": "example-nodejs"}, "number": '$SEQ_NUM' }}, "load_details": "0"}' --insecure -H "client-api-protocol: 1,1" -H "Authorization: `waypoint token new`" localhost:9701 …
```
> Wiring declared resources into release functions, with k8s reference impl

- internal/server/singleprocess/service_status_report.go
- internal/server/singleprocess/service_status_report_test.go
Prior to this commit, if a caller requests a status report job but
doesn't specify a workspace, the server would panic on the Workspace ref
being unset when it attempted to build the job. This commit fixes it by
defaulting to the default workspace if the caller does not specify which
workspace the report should run in.
> internal/server: Ensure ExpediteStatusReport sets a default workspace

- .changelog/1949.txt
- builtin/docker/builder.go
- website/content/partials/components/builder-docker.mdx
Fixes https://github.com/hashicorp/waypoint/issues/1881. Enables a platform HCL arg that is equivalent to `docker build --platform` flag. This only works with buildkit on (will fail with error).
Usage:
Add platform in `waypoint.hcl`
```project = "nginx-project"
app "web" {
build {
use "docker" {
platform = "linux/arm64/v8"
}
}
deploy {
use "docker" {
}
}
}
```
How to verify this works:
`waypoint build`
`docker inspect <docker image>` output should contain
``` 
"Architecture": "arm64",
"Variant": "v8",
"Os": "linux",
```
Merge after https://github.com/hashicorp/waypoint/pull/1937.
[Issue filed with Docker/Moby ](https://github.com/moby/moby/issues/42689)so that it may work without buildkit in the future.
🍐 with @izaaklauer thanks!
> Improvement: Plugin/Docker: Enables image build for specified platform

- internal/cli/project_apply.go
This commit adds some extra error messaging if a user requests to enable
project or app status polling without specifying the data source of the
project. Being explicit here ensures that app polling is only turned on
with the projects data source is git since neither of these polling
features work with local data sources.
> cli/project_apply: Return error if polling requested but no data source

- website/content/docs/waypoint-hcl/variables/input.mdx
Found a fixup needed as I ran through the input vars docs.
> website: quote input var label example with docker

- .changelog/2025.txt
- ui/app/components/app-card/build.hbs
- ui/app/components/app-card/deployment.hbs
- ui/app/components/app-card/release.hbs
- ui/app/components/git-commit.hbs
- ui/app/helpers/truncate-commit.ts
- ui/app/styles/app.scss
- ui/app/styles/components/git-commit.scss
- ui/app/styles/mixins/_index.scss
- ui/app/styles/mixins/button-reset.scss
- ui/app/templates/workspace/projects/project/app/build.hbs
- ui/app/templates/workspace/projects/project/app/deployment.hbs
- ui/app/templates/workspace/projects/project/app/release.hbs
Fixes: https://github.com/hashicorp/waypoint/issues/1508
> Display commit information if available

- internal/server/singleprocess/service_status_report_test.go
This test would occasionally flake if the ListStatusReports endpoint returned reports out of order. Order is not guaranteed so this fixes that by checking the report Ids against the right reports returned.
> tests: Ensure ListStatusReports checks id against proper target report

- website/content/docs/server/auth/oidc.mdx
Found this during my 0.5 dry runs, this is an important setting that isn't well documented (until now).
> website: document redirect URL for OIDC config

- go.mod
- go.sum
Also upgrades waypoint-plugin-sdk to the new version that uses argmapper v0.2.1
Depends on https://github.com/hashicorp/waypoint-plugin-sdk/pull/50
> Upgrade argmapper to v0.2.1

- builtin/docker/platform.go
This commit closes the UI loop for when the docker platform is
generating status reports for its resources. Before this commit, the UX
would just say it was still generating a report with trailing '...'.
This commit closes that UX loop to say Waypoint finished building these
reports.
This should be backported once we're ready.
> builtin/docker: Close UX loop for generating status reports

- .changelog/2039.txt
- internal/server/singleprocess/poll.go
- internal/server/singleprocess/poll_application.go
- internal/server/singleprocess/poll_test.go
- internal/server/singleprocess/state/app_operation.go
- internal/server/singleprocess/state/application.go
Previously, if a release was present, we would stop polling on the latest deployment. This means we would stop looking at the statuses of instances, which are managed (and polled) by the deployments, and are most likely to have status that changes over time.
- Make a k8s project with a releaser (e.x.: https://github.com/hashicorp/waypoint-examples/tree/main/kubernetes/java)
- Init the project
- Set app polling on the project (e.x. `waypoint project apply -app-status-poll-interval=10s -data-source=git -git-url=https://github.com/hashicorp/waypoint-examples -git-path=kubernetes/java -app-status-poll example-java`)
- Run a `waypoint up`
- Watch the status reports for 30 seconds or so. You should notice the latest deployment _and_ the latest release reports update every 10 seconds:
> Build poll jobs for the latest deployment and release

- .changelog/2047.txt
- internal/cli/status.go
If a status report is returned without `GeneratedTime` set, the CLI will fail to parse it:
```
$ waypoint status -app=nginx-example
Current status for application "nginx-example" in project "example-nginx-ami" in server context "waypoint-server-nlb-774e79e21a01ca87.elb.us-west-2.amazonaws.com:9701".
! CLI failed to format app status:timestamp: nil Timestamp
```
In this PR we check for a valid time. If it's not valid, we insert `(unknown)` as a placeholder
> cli/status: fix broken output when no generated time is set

- .changelog/2048.txt
- builtin/aws/alb/releaser.go
The ALB `Status` method did not set the `GeneratedTime`. This PR fixes that.
> plugin/aws/alb: Set generated time for the Releaser status report

- .changelog/2036.txt
- ui/app/components/status-report-bar/index.hbs
- ui/app/styles/_layout.scss
Some minor changes to fix alignment and type rhythm of the `status-row`. This PR makes the `status-indicator` text the same size as the supporting text on this screen and also moves the status text next to the indicator to avoid uneven whitespace.
Before:
After:
> UI: Change layout of status-row

- .changelog/2052.txt
- internal/cli/install.go
- internal/cli/uninstall.go
- website/content/commands/install.mdx
- website/content/commands/server-install.mdx
- website/content/commands/server-uninstall.mdx
Prior to this commit, the CLI uninstall command assumed that the
platform requested matched the server platform. This could be confusing
if a user has both a docker platform server and a local server from
`waypoint server run`. This commit adds some extra validation with the
platform requested by loading the server platform and taking into
account what platform was requested.
This commit also changes the hard requirement that the uninstall
command needs a platform flag. If a server context has a platform set,
and no platform flag was requested, use that platform instead. Note
that the platform flag, if requested, always overrides what the server
context has. This is because some early versions of Waypoint do
not set the Platform context. If the flag and server platform conflict,
we'll …
> cli/uninstall: Add more validation to requested platform for uninstall

- .changelog/2054.txt
- builtin/aws/ecs/platform.go
This commit fix destroy non-latest deployments in ECS
[![asciicast](https://asciinema.org/a/wibXMNZJqY0R03QGW8AQcuwdK.svg)](https://asciinema.org/a/wibXMNZJqY0R03QGW8AQcuwdK)
> fix destroy non-latest deployments in ECS

- contrib/serverinstall/kind-k8s/README.md
- contrib/serverinstall/kind-k8s/configs/cluster-ingress-config.yaml
- contrib/serverinstall/kind-k8s/setup-k8s.sh
This commit updates the contrib bash helper for setting up k8s to
optionally include an ingress controller config. It also updates to use
a newer version of `metallb` and now automatically picks an IP to use
rather than asking for user input.
> contrib/severinstall/kind-k8s: Include optional support for k8s ingress

- website/content/docs/waypoint-hcl/variables/input.mdx
Fix link to Input variables tutorial
> Fix link to Input variables tutorial

- website/content/docs/projects/git.mdx
- website/content/docs/waypoint-hcl/runner.mdx
The data source path in the [waypoint-examples repo][repo] is `docker/nodejs` not `docker/node-js`
[repo]: https://github.com/hashicorp/waypoint-examples/tree/main/docker/nodejs
> Small doc update to fix data source paths

- builtin/google/cloudrun/platform.go
- website/content/partials/components/platform-google-cloud-run.mdx
`vpc_access` was marked as required even though it's optional, which  caused confusion.
example:
https://github.com/hashicorp/waypoint/issues/1942
Moved nested fields to generate as optional nested fields in the documentation. Will open another issue to change how we parse optional blocks (there is currently no way to make the block optional, only the nested fields.)
> docs/plugin Update GCP documentation

- .changelog/2093.txt
- builtin/nomad/platform.go
Closes #2069
1. Check out the branch
2. Deploy a nomad project
3. Check the UI
4. Verify that the nomad deployment status shows up as expected
> plugin/nomad: only use non-empty `job.StatusDescription` for `HealthMessage`

- internal/cli/ondemand_runner_apply.go
- internal/cli/runner_agent.go
- website/content/commands/runner-agent.mdx
- website/content/commands/runner-on-demand-set.mdx
This pull request fixes the panic when a non-existence runner id is requested but not found for setting a runner config. It also fixes up usages of "ondemand" and replaces it with "on-demand", and returns an error about `-plugin-type` not being set prior to the upsert to give a better user-facing message for a missing flag.
Fixes #2176
> cli/odr: Fix panic if requested runner id not found

- ui/app/components/app-form/project-repository-settings.hbs
- ui/app/components/operation-logs/index.ts
- ui/app/components/project-input-variables/list-item.ts
- ui/app/components/project-input-variables/list.ts
~~Notably had to update `Ref.Component`'s namespace to include `Type` in the `ui/lib/waypoint-pb/server_pb.d.ts` file. Type existed in the `Component` namespace, but for some reason did not carry over when under the `Ref` namespace. This was causing some linting errors~~
_See comments from @jgwhite below_
> ui: Fixed linting errors and updated API definitions

- website/content/docs/upgrading/index.mdx
As the title suggests :)
Though in the process of investigating this, we uncovered that the `-runner` flag is mentioned in the documentation, but missing from the flag list. Another PR coming to fix that.
Follow-up to https://github.com/hashicorp/waypoint/issues/2113
> docs: add details about remote runners on server upgrade

- website/content/docs/upgrading/index.mdx
This removes all the notes about the differences when upgrading from 0.2.0 and previous versions to 0.2.1 and later versions. This also adds a note about using server snapshots in the `Manual Upgrade` section.
> docs: Remove old upgrade info

- internal/server/singleprocess/state/job.go
- internal/server/singleprocess/state/job_test.go
This fixes a regression caused in #2186 where ODR would never get assigned a job.
> internal/server: peeking a job must close the memdb txn

- .changelog/2250.txt
- ui/app/components/app-form/project-repository-settings.ts
- ui/tests/integration/components/app-form/project-repository-settings-test.ts
Fixes: #2150
`populateExistingFields` was mutating the `DEFAULT_PROJECT_MODEL` properties, thus causing the values to be retained when the component was reused. 
This PR sets the `defaultProject` on the component as a static property, and then reads keys from that object in `populateExistingFields`.
> Fix overwriting default project model

- .changelog/2269.txt
- internal/server/ptypes/deployment.go
- internal/server/ptypes/ref.go
- internal/server/singleprocess/service_deploy.go
Prior to this commit, if a request left out a request body, the server
would panic and shut down. This commit fixes that by adding a validation
step first to ensure the request is properly formed prior to handling
it.
Fixes #1682
With the new validation:
```
brian@localghost:static λ docker run -it --network host fullstorydev/grpcurl --insecure -H "client-api-protocol: 1,1" -H "Authorization: `waypoint user token`" localhost:9701 hashicorp.waypoint.Waypoint/GetDeployment
ERROR:
Code: InvalidArgument
Message: ref: cannot be blank.
Details:
1)    {"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"ref","description":"cannot be blank"}]}
```
Before, you would get this and the server would panic and exit:
```
brian@localghost:static λ docker run -it --network …
```
> internal/server: Add API validation for GetDeployment endpoint

- internal/cli/config_get.go
- internal/cli/config_set.go
- website/content/commands/config-get.mdx
- website/content/commands/config-set.mdx
This PR finishes up the coding part of #2169. This modifies the CLI to support all the new scoping options. 
I admit this isn't the cleanest UX possible. I'd love to challenge this a bit more with folks in the future and figure out how we can maybe make the `waypoint config` CLIs a little easier to use perhaps. Right now you gotta balance a bunch of flags.My counter argument is people probably won't use the CLI for more advanced config setting and will prefer to use the config file or UI (tbd). 
In terms of the bigger picture #2169, I need to work up docs still. But this should finish all the main coding parts.
> Set and get new config scopes from the CLI

- ui/app/styles/components/variables-list.scss
Fixes https://github.com/hashicorp/waypoint/issues/2191
> truncate display of long variable values

- .changelog/2277.txt
- internal/pkg/epinject/epinject.go
This makes it so that our entrypoint injection supports Docker hosts over SSH. We did this for `builtin/docker` but not for `internal/pkg/epinject`. I copy and pasted the function so we don't have to cross package boundaries (in case we ever extract our plugins).
> internal/pkg/epinject: support SSH DOCKER_HOST

- internal/server/singleprocess/state/job.go
- internal/server/singleprocess/state/job_test.go
We use Peek to check if there is any potential candidate jobs for a
runner, not a guarantee that it will immediately be assigned that job.
In the scenario where a job is blocked (defined below), peek would
return nil which broke the on-demand runner use case that used peek to
verify a job exists for a runner.
A job is "blocked" when another job is already assigned for the same
`(app, project, workspace)` tuple. This serializes operations for that
tuple to prevent concurrency issues but still allow concurrency across
projects/apps/workspaces.
> internal/server/state: peek should return blocked jobs

- ui/ember-cli-build.js
Uses `ember-auto-import`'s `skipBabel` feature to avoid transpiling the `lib/waypoint-pb/server_pb.js` file, which was not needed, and memory-intensive. This speeds up our builds and seems to get rid of [the error we were running into in CI](https://github.com/hashicorp/waypoint/issues/2260).
> skip babel for lib files

- internal/cli/ondemand_runner_apply.go
- website/content/commands/runner-on-demand-set.mdx
> internal/cli: plugin-config instead of project-config

- .changelog/2296.txt
- .gitignore
- builtin/k8s/platform.go
- go.mod
- go.sum
- internal/core/app_deploy.go
This PR adds support in waypoint core to pass the deployment sequence number to plugins, and also modifies the k8s plugin to use sequence number in k8s deployment resource names instead of the ID. 
I opted to entirely replace the Waypoint ID with Sequence # in the k8s deployment name because k8s already assigns several random strings to pods derived from deployments so having the Waypoint ID is noise in my opinion. After this change, deployment names become:
```
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
httpbin-v1        1/1     1            1           34m
httpbin-v2        1/1     1            1           7m1s
```
Where `httpbin` is the waypoint app name.
Pods therefore become:
```
NAME                          READY   STATUS    RESTARTS   AGE
httpbin-v1-7c6bb9f655-n4f6j …
```
> builtin/k8s - Use sequence # in k8s deploy name instead of ID

- .changelog/2320.txt
- internal/clicontext/config.go
- internal/clicontext/config_test.go
- internal/serverconfig/config.go
- internal/serverinstall/serverinstall.go
Before we would not set a port at all, and I'm not sure what port it was
trying to connect to. Given our installation method on all platforms
defaults our gRPC to port 9701, it makes sense to default to port 9701
if none is specified.
This makes the initial installation login experience smoother cause most
installations can just do:
$ waypoint login <IP or hostname>
And it'll just work, rather than looking up the port, which is most
likely 9701.
> internal/clicontext: default to gRPC port for login addr

- builtin/docker/kaniko.go
fixes a small typo I found while experimenting with Gitops setups
> negotiate, not "negoate"

- .changelog/2325.txt
- internal/cli/server_run.go
- internal/serverinstall/docker.go
- internal/serverinstall/ecs.go
- internal/serverinstall/k8s.go
- internal/serverinstall/nomad.go
Set default log level to debug rather than trace for the server during an install.
As part of the work for #1514, users will be able to set the log level to trace if desired (for example: `waypoint install -platform=docker -accept-tos -run-flags="-vvv"`)
> cli, server: set default log level to debug on server install

- internal/cli/k8s_bootstrap.go
- website/content/commands/k8s-bootstrap.mdx
This commit fixes up the spacing in the k8s bootstrap helptext so that
the ordered list doesn't render as a codeblock
Before:
With this fix:
> internal/cli: Adjust spacing in help text

- internal/cli/base_init.go
- internal/cli/k8s_bootstrap.go
- internal/cli/login.go
- internal/pkg/k8sauth/doc.go
- internal/pkg/k8sauth/k8sauth.go
- internal/serverclient/client.go
- website/content/commands/login.mdx
This introduces `waypoint login -from-kubernetes` that performs automatic authentication after a Helm-based install. This looks up the Waypoint service, gets the token from the Kubernetes secret, and completes the login.
> waypoint login -from-kubernetes

- .changelog/2328.txt
- internal/cli/install.go
- internal/cli/main.go
- internal/cli/server_run.go
- internal/cli/server_upgrade.go
- internal/cli/status.go
- internal/serverinstall/docker.go
- internal/serverinstall/ecs.go
- internal/serverinstall/k8s.go
- internal/serverinstall/nomad.go
- internal/serverinstall/serverinstall.go
- website/content/commands/install.mdx
- website/content/commands/server-install.mdx
- website/content/commands/server-run.mdx
- website/content/commands/server-upgrade.mdx
- website/content/docs/server/run/index.mdx
- website/content/docs/server/run/maintenance.mdx
- website/content/plugins/aws-ec2.mdx
This allows users to pass flags "through" the `install` command to the `server run` command that all server install platforms use. Included in `upgrade` as well for Nomad and Docker.
There are a couple typos and doc updates for various items as well that I saw while moving around the install/run docs.
Fixes #1514
Fixes #1491 
Augments #2325 by allowing the user to set their server log levels on an install.
**To test:**
Base case:
- On `main`, run `make`, then use the built binary to install the Waypoint server on docker. Check out the logs (`docker logs waypoint-server`) and observe that there are `INFO` and `DEBUG` logs only.
Test case:
- On this branch, run `make`, then use the built binary to install the Waypoint server on docker as follows: `waypoint install -platform=docker …
> cli: pass raw string of `server run` flags to install command

- internal/server/gen/server.pb.go
- internal/server/proto/server.proto
- internal/server/singleprocess/state/config_test.go
- internal/server/sort/config.go
The config resolution rules omitted workspace targeting. This ended up
in behavior that worked as "intended" in this broken case: sometimes
you'd get workspace-scoped prioritizing over non-workspace-scoped and
vice versa. It was undefined!
This clarifies the resolution to note that a variable with a workspace
set takes higher priority over one without a variable set, and encodes
this rule into the sort logic. This also adds tests for this.
> internal/server: config resolution needs to account for workspaces

- .changelog/2348.txt
- internal/server/http_log.go
The "kube-probe" user agent is sent for Kubernetes health checks. If the
user agent matches this, we still log but we do so at a lower level so
that our logs don't get flooded.
> internal/server: log kubeprobe http requests at trace level

- internal/cli/fmt.go
Tiny PR. 
This makes it behave more like `terraform fmt` and also solves an issue
where on success it output nothing, which made it unclear if it did
anything.
> internal/cli: fmt should output the name of the file it modified

- .changelog/2347.txt
- internal/cli/server_run.go
- internal/server/http.go
- internal/server/http_tls.go
- internal/server/http_tls_test.go
- internal/server/server.go
- internal/serverconfig/config.go
- website/content/commands/server-run.mdx
This adds a `-listen-http-insecure` flag to the Waypoint server to create an insecure (non-TLS) HTTP listener. 
This insecure HTTP listener behaves in two ways:
1. If there is an `X-Forwarded-Proto` of `https`, it routes the traffic.
2. Otherwise, it redirects to https.
The insecure HTTP listener is primarily to help with the Kubernetes use case where resources such as `Ingress` do not typically talk to their backends with TLS. Further, it helps the basic `LoadBalancer Service` case because port 80 will redirect to TLS versus not connecting today. 
This is opt-in functionality. If the flag isn't specified, an insecure listener is not created. 
There is no way to get this today with `waypoint install` (unless you specify a manual flag). The plan is to integrate this into the Waypoint Helm …
> Waypoint server: Support insecure HTTP listener 

- builtin/docker/kaniko.go
The Docker `reference` library doesn't give us the real registry host in
this special case, so we just set it manually.
If we find a better way to do this, we should do it.
> builtin/docker: if host is docker.io, use index.docker.io for registry

- .changelog/2362.txt
- internal/config/variables/testdata/valid.hcl
- internal/config/variables/variables.go
- internal/config/variables/variables_test.go
- internal/runner/operation.go
- website/content/docs/waypoint-hcl/variable.mdx
- website/content/docs/waypoint-hcl/variables/input.mdx
This lets input variables specify any named environment variable as a source for a default value. Example: 
```
variable "region" {
type    = string
env     = ["REGION"]
}
```
If the `REGION` env var is set, it will populate the default value of this variable (Note: `WP_VAR_region` takes priority always). If multiple env vars are specified, the first matching takes priority. If none of the defined env vars are set, the `default` value (if set) is used. If no default is specified, it is an error since the variable is required and unset.
The env vars specified here are loaded _only at the runner (config evaluation time)_ currently. I'm unsure if we want to expand this to load at CLI time but I would say no, we only want WP_VAR_ variables there, unless the CLI also happens to be the runner …
> Support specifying custom environment variables for input variable default values

- internal/core/app.go
- internal/core/project.go
A little PR that builds on top of recent SDK improvements.
This exposes the project and app name in the component.JobInfo structure
that is already passed to all plugin operations. This will allow plugins
to make use of project/app name as necessary for behavior.
I want to use this information for default release names for Helm.
> internal/core: add project/app to JobInfo

- website/data/commands-nav-data.json
I believe the current `context` and `context-inspect` are misplaced in the CLI nav. I've moved them lower with the other `context` commands, and also removed the `-` from `context-inspect`. Attached are before/after screen grabs.
**Before:**
**After:**
> Website: move context and context inspect lower in CLI navigation

- internal/cli/base_init.go
- internal/cli/deployment_list.go
- internal/cli/status.go
- website/content/commands/deployment-list.mdx
1. Provide better output about a missing config when a remote operation could be used.
2. Indicate that a remote operation is possible in the `deployment list` help.
3. Output fewer blank lines in status report output.
> Minor CLI papercuts

- .changelog/2399.txt
- builtin/k8s/platform.go
- builtin/k8s/releaser.go
1. This scales the wait time back so that bad deploys fail much faster.
Previously we had it hardcoded to 10 minutes, now it's dynamic.
2. When a deployment fails, print out non Info events from the pods to
help the user diagonise what happened.
3. Provide some small grace period on pod cleanup to allow for the
potential of debugging the failed pods directly.
4. Handle not being able to search for metric pods
5. Handle destroying an old deployment that didn't have autoscaling
defined yet.
6. Setup the kubernetes service with the workspace name if the workspace
is not the default workspace
> Fix a few minor kubernetes papercuts

- .changelog/2353.txt
- internal/cli/base.go
- internal/cli/base_test.go
- internal/cli/context_create.go
- internal/cli/context_inspect.go
- internal/cli/context_set.go
- internal/cli/main.go
- internal/cli/status.go
- internal/clicontext/config.go
- internal/runner/operation_up.go
- website/content/commands/context-set.mdx
- website/data/commands-nav-data.json
This PR adds a subcommand `set` to the `context` command, allowing users to set a property of the current context. The only supported property at this time is `-workspace`. This enables users to set the workspace once, and avoid having to repeatedly set the `-workspace` with every CLI invocation. 
Additionally this all introduces support for reading the desired workspace from the environment, using the environment variable `WP_WORKSPACE`. I considered `WAYPOINT_WORKSPACE` and can go either way.
The CLI flag `-workspace` is still supported however it itself no longer has a default value; the value is now derived from either the flag, the environment, the stored value in the context storage, or the default value of `"default"`, in that order, with the first non-empty value being used.
TODO:
> Add `context set` subcommand

- .changelog/2385.txt
- internal/cli/main.go
- internal/cli/workspace_inspect.go
- internal/cli/workspace_list.go
- website/content/commands/workspace-inspect.mdx
- website/content/commands/workspace-list.mdx
- website/data/commands-nav-data.json
This PR introduces a top level command tree `workspace` that is scoped to the current context, with two subcommands:
- `list`: list all workspaces in this context
- `inspect <name>`: inspect the workspace `<name>`, or the current workspace
~This PR builds off of https://github.com/hashicorp/waypoint/pull/2353 so I'm opening it as a draft until 2353 is approved and merged. Until then this PR will appear to be larger than it actually is.~ #2353 has been merged 
UX:
<details>
**List:**
```
$ waypoint workspace list                  
NAME   |        PROJECTS
----------+--------------------------
default | example-go,example-ruby
dev     | example-go
lab     | example-ruby,example-go
```
**Inspect the default workspace:**
```
$ waypoint workspace inspect               
» Workspace Info:
Name: …
```
> Add workspace CLI command, list/inspect subcommands

- .changelog/2416.txt
- builtin/vault/config_sourcer.go
- internal/appconfig/watcher.go
- internal/appconfig/watcher_test.go
Prior to this, it appears that dynamic config targeting files did not work - our logic was treating all dynamic config as env vars, and not respecting [`name_is_path` ](https://github.com/hashicorp/waypoint/blob/33fa916c8fa2e295e8913efba91de7e086760cd6/internal/server/proto/server.proto#L3433).
This enables stanzas like this to work:
```
config {
file = {
"/shared-config/nginx.conf" = configdynamic("vault", {
path = "secret/data/apps/sample-app"
key = "data/nginx.conf"
})
}
}
```
I can't claim to have deeply understood all of the surrounding logic, so if there's a better place or way to do this, I'm open to feedback.
This also incidentally adds some better error messages to the vault config-sourcer plugin.
> Enabling dynamic config files

- .changelog/2426.txt
- internal/cli/release_create.go
- internal/cli/release_list.go
- website/content/commands/release.mdx
Things done:
* removed the `[id]` arg that isn't used
* amend the deployment ID returned in the CLI message to match the type of ID we use in `deployment list`
* fix the logic on whether or not a 🚀 shows in `release list`
> cli: release cmd tuneups

- builtin/docker/kaniko.go
Follow up on #1969, adds the same targeting support when building under Kaniko.
> docker: Support multi-target builds under kaniko/ODR

- go.mod
- internal/serverinstall/serverinstall.go
- internal/serverinstall/serverinstall_test.go
Previously, running `waypoint server install -platform=docker -accept-tos -docker-server-image=my.registry:5000/waypoint` would have parsed `:5000/waypoint` as a tag, and made the ODR image `my.registry-odr:5000/waypoint`.
This is such a narrow rare bug, but I noticed it and now here we are. Probably wasn't worth the 20 minutes to fix.
> Correctly parse ODR images when using a registry with a port

- website/content/docs/kubernetes/container-build.mdx
- website/content/docs/kubernetes/external-build.mdx
- website/content/docs/kubernetes/helm-deploy.mdx
- website/content/docs/kubernetes/install.mdx
- website/data/docs-nav-data.json
This starts the Kubernetes focused docs section.
The goal is to focus more on Kubernetes use cases and being opinionated more towards K8S users needs and challenges.
Note this is missing real runnable example projects. My plan is to fill in various sections with waypoint-examples links where it makes sense, but I wanted to get some content down first.
> website: starting Kuberenetes-focused docs section

- internal/cli/runner_profile_inspect.go
- internal/server/singleprocess/state/ondemand_runner.go
- internal/server/singleprocess/state/ondemand_runner_test.go
Merge after https://github.com/hashicorp/waypoint/pull/2403
Previously, `waypoint runner profile inspect foo` would panic if no profile with a name or ID of foo existed. Panic:
```
» Runner profile:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x723e9ac]
github.com/hashicorp/waypoint/internal/cli.(*RunnerProfileInspectCommand).Run(0xc000406fe0, 0xc0004356c0, 0x1, 0x4, 0xc000406c30)
/Users/izaak/dev/waypoint/internal/cli/runner_profile_inspect.go:79 +0x62c
github.com/mitchellh/cli.(*CLI).Run(0xc0009c8000, 0xc000d3fee8, 0x86a8f18, 0xc000435700)
/Users/izaak/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
github.com/hashicorp/waypoint/internal/cli.Main(0xc000435680, …
```
> Fix a panic in `waypoint runner profile inspect`

- builtin/k8s/releaser.go
The previous fix for ingress annotations would accidentally preserve any
old annotations that might of been set in a waypoint.hcl. So if a user
decided to update and remove some old values, they would continue to be
present in the next release. This commit fixes that by setting the
ingress resource annotations to whats exactly set in a waypoint.hcl.
> builtin/k8s: Do not preserve old annotations

- .changelog/2489.txt
- internal/cli/project_apply.go
- internal/cli/project_inspect.go
- website/content/commands/project-apply.mdx
This also fixes a bug where we could only set a runner profile with an ID that isn't visible in the CLI anymore.
> Update `project` commands to use `runner profiles` instead of `odr configs`

- internal/server/singleprocess/service_entrypoint.go
- internal/server/singleprocess/service_logs.go
- internal/server/singleprocess/service_logs_test.go
The issue here is that we can't force a flush and wait for a recv on the
client/server. Instead of sleeping 100ms and hoping for the best, we use
Eventually with a timeout to accumulate log entries. This should make
this deterministic in even the slowest practical cases.
> internal/server: fix flaky test TestServiceGetLogStream_depPlugin

- internal/core/project.go
Add a debug-level log that shows up in runners that shows where variables are sourced by job. This can be used by callers to more easily debug Waypoint configurations. I think we can make this even easier later but this is a bandaid for now to have SOMETHING to let us know.
> internal/core: log variable value source

- internal/cli/install.go
Use the capitalized form of the platform in the install message.
> Use the platform name in the installation message

- website/content/docs/server/install.mdx
- website/content/docs/server/run/index.mdx
- website/data/docs-nav-data.json
This pull request adds some basic docs for the `waypoint install` command for the website. It's not the full CLI command docs, which are found under the CLI section. This is more a higher level introduction to what the CLI helper provides since we already cover running the server manually with `server run`.
Fixes https://github.com/hashicorp/waypoint/issues/2631
> website: Add docs for waypoint install command

- .changelog/2673.txt
- internal/cli/project_apply.go
- internal/pkg/flag/flag_bool_ptr.go
- internal/pkg/flag/flag_bool_ptr_test.go
Currently with `waypoint project apply`, users [need to provide several flags][flags] in order to enable git or app status polling. Two flags are problematic (`flagPoll` and `flagAppStatusPoll`) because they are declared as `bool` values, and our flag parsing package cannot discern between a `false` boolean value supplied versus the zero value `false` if either flag is simply omitted. That, coupled with a [logical truthy check][check], currently prevent users from turning either polling or app status polling off with the CLI once they are enabled (users can still disable git polling from the UI).
This PR adds a new flag value `BoolPtrVar`, for boolean values that need to discern between `true`,`false`, and omitted. `BoolPtrVar` is a `*bool` value which contains a pointer to `true`, …
> Fix issue where you can't disable Project polling

- .changelog/2654.txt
- internal/serverinstall/k8s.go
Fixes https://github.com/hashicorp/waypoint/issues/2452
Fixes https://github.com/hashicorp/waypoint/issues/2647
It's not beautiful - could be dryer, and it would be better long-term if we discovered what rbac resources we were managing based on tags instead of names I think. This is good enough though, especially seeing as we're likely replacing the this functionality with the helm chart eventually.
> Do not error on existing cluster roles, and clean up rbac on uninstall

- website/content/docs/app-config/scope.mdx
- website/content/docs/waypoint-hcl/config.mdx
- website/data/docs-nav-data.json
This adds documentation for workspace and label scopes for application configuration that was introduced in Waypoint 0.6.
> website: document workspace/label scoping for app config

- .changelog/2692.txt
- .gitignore
- Makefile
- builtin/docker/builder.go
- builtin/docker/kaniko.go
- builtin/pack/builder.go
- internal/assets/.gitignore
- internal/assets/ceb.go
This adds a `linux/arm64` entrypoint asset to our Waypoint binary. This
increases binary size by ~30% but I think this is worthwhile as more of
the world's dev and deployment machines move to arm64.
This makes it so that Docker entrypoint injection injects the entrypoint
binary that matches the architecture and errors if it detects an
unsupported architecture.
This also adds detection for cloud native buildpacks to warn if the
Docker daemon isn't x86_64 since Buildpacks currently have issues with
arm64.
This also changes the Docker build to output the image architecture
since @jgwhite has built and deployed mismatching architecutures
many times.
Going to target this for backporting.
> support arm64 for the entrypoint, inject properly

- .changelog/2696.txt
- ui/app/routes/application.ts
- ui/tests/acceptance/auth-test.ts
Fixes: https://github.com/hashicorp/waypoint/issues/2695 
In summary: 
- the error message on an unauthenticated request changed to `Authorization token is not supplied`
- the error handler that would invalidate the session wasn't firing
This PR also adds an auth acceptance test, just cause that's nice to have
> Handle both unauthenticated error messages

- .changelog/2699.txt
- internal/config/app.go
- internal/config/app_test.go
- internal/config/plugin.go
- internal/config/stages.go
- internal/config/testdata/compare/build_registry_scoped.hcl
- internal/config/testdata/compare/build_scoped.hcl
- internal/config/testdata/validate/build_no_use.hcl
- internal/config/testdata/validate/build_scoped.hcl
- internal/config/validate.go
- internal/config/validate_test.go
- internal/core/app_build.go
- internal/core/component_creator.go
- website/content/docs/lifecycle/scope.mdx
- website/data/docs-nav-data.json
This PR introduces a new feature that lets workspace or label-specific configurations for build, deploy, release, etc. The docs are fully updated in this PR so please take a look at those for more details!
Example:
```hcl
app "my-app" {
deploy {
use "kubernetes" {}
workspace "production" {
use "kubernetes" {
namespace = "production"
}
}
workspace "new-platform" {
use "nomad" {
// nomad configuration here
}
}
}
}
```
> Introduce workspace and label scoping into the waypoint.hcl file

- .changelog/2698.txt
- builtin/pack/builder.go
- internal/serverinstall/nomad.go
Prior to this commit, the server install command would look for the very
first instance for when an allocation was considered running. This is
generally ok, however if the Nomad job fails to get started a moment
later (like a static runner failing to connect back to Waypoint Server),
the runner allocation would exit later but the server install command
would consider the installation successful.
This is especially important when users are configuring Consul DNS
with Waypoint Server installed to Nomad. The static runner might
fail to properly make a connection through the Consul DNS hostname
and fail, leaving the installation without a static runner but the CLI claiming
the install succeeded.
This commit fixes that by doing a few retries for a few seconds on the scheduled
allocation once …
> serverinstall/nomad: Spend more time looking at waypoint-runner allocation on install to ensure start up

- .changelog/2713.txt
- internal/serverinstall/nomad.go
- website/content/docs/runner/profiles.mdx
We support ODR in all builting install platforms now,
so our documentation should reflect that.
Also updates the Nomad ODR config to list the Name as the platform name, matching our other builtin install platforms.
> docs, serverinstall: updates to docs & naming of runner install

- Makefile
What it's actually doing is skipping embedding the ceb. The image it produces can be used as a cli, runner, or server.
> Rename `make bin/cli-only` to `make bin/no-ceb`

- website/content/docs/roadmap.mdx
We've implemented this feature, so it's no longer a future TODO on the
Waypoint roadmap
> docs: Remove section about resource and health tracking

- internal/serverstate/statetest/statetest.go
- internal/serverstate/statetest/test_project.go
This gives the watchset implementor a little more latitude about how quickly it detects the new data.
> statetest: Make the timing of the watchset tests more forgiving

- internal/cli/base.go
- internal/cli/base_test.go
- internal/server/gen/server.pb.go
- internal/server/server_test.go
- internal/server/testing.go
This introduces the logic for automatic detection of local vs remote operations. It isn't used anywhere yet. 
I had some fun building tests that mocked the server - there are enough permutations that I didn't build a case for each one, but this covers the highlights.
> Auto local/remote detection

- ui/app/styles/pages/_index.scss
- ui/app/styles/pages/projects/new.scss
- ui/app/templates/workspace/projects/new.hbs
Co-authored-by: Jamie White <jamie@jgwhite.co.uk>
If merged, this PR resolves an issue where a checkbox had multiple labels. To fix, one of the labels was converted to fill the aria-describedby role for the checkbox. 
Accessibility tree shows that it works as intended.
> Resolved issue where checkbox had two labels.

- .changelog/2771.txt
- internal/cli/base.go
- website/content/commands/artifact-build.mdx
- website/content/commands/artifact-push.mdx
- website/content/commands/build.mdx
- website/content/commands/deploy.mdx
- website/content/commands/deployment-deploy.mdx
- website/content/commands/deployment-destroy.mdx
- website/content/commands/destroy.mdx
- website/content/commands/docs.mdx
- website/content/commands/release.mdx
- website/content/commands/status.mdx
- website/content/commands/up.mdx
Merge after https://github.com/hashicorp/waypoint/pull/2760/files
Replaces the -remote flag with the -local flag. Nice deprecation warning for -remote.
The impetus for this change is that shortly, waypoint will automatically default operations to happen remotely if they're likely to succeed remotely, and locally if otherwise. With that change in place, it will be much more likely that users will want to override an operation to happen locally, and adding `-local` is more friendly than adding `-remote=false`.
Flag usage
```
$ waypoint artifact build -local
» Building web...
✓ Initializing Docker client...
✓ Building image...
│ Step 1/3 : FROM nginx:stable
│  ---> c8d03f6b8b91
│ Step 2/3 : COPY ./public/ /var/www
│  ---> Using cache
│  ---> 61409f8fbdaf
│ Step 3/3 : COPY ./nginx.conf …
```
> Replace -remote flag with -local

- Makefile
In case you do a fresh checkout and you have never compiled a go project "make install" will fail because the go bin directory does not exist. 
This might be a rare problem for a developer machine, but might cause issues in CI builds and it looks to me it is easy to fix.
> make install: make sure go/bin directory exists

- internal/server/singleprocess/service_job.go
- internal/server/singleprocess/service_job_test.go
- internal/server/singleprocess/state/job.go
- internal/server/singleprocess/state/job_test.go
We had this field, but weren't using it! I'd like to use it to give the CLI more context as to where a job is running.
> Set the assigned runner ID on the job

- telemetry/README.md
This PR fixes small typo in telemetry readme file: `Jeager` -> `Jaeger`.
p.s.: I didn't change image name `jeager-traces.png`, I guess it's overkill in this case :).
> docs(telemetry): fix typo in telemetry readme file

- builtin/aws/lambda/platform_logs.go
- internal/cli/artifact_build.go
- internal/cli/artifact_push.go
- internal/cli/base.go
- internal/cli/base_init.go
- internal/cli/base_test.go
- internal/cli/deployment_create.go
- internal/cli/deployment_destroy.go
- internal/cli/deployment_list.go
- internal/cli/destroy.go
- internal/cli/exec.go
- internal/cli/logs.go
- internal/cli/option.go
- internal/cli/release_create.go
- internal/cli/status.go
- internal/cli/up.go
- internal/client/job.go
- internal/client/job_test.go
- internal/client/operation.go
- internal/client/project.go
- internal/client/runner.go
- internal/client/runner_test.go
- internal/client/testing.go
- internal/server/grpcmetadata/grpc.go
- website/content/commands/exec.mdx
- website/content/commands/logs.mdx
This PR primarily moves the local runner trigger logic out of the CLI and into the project client. Rather than rely on each command to declare ahead of time if they require a runner, and start the runner before the command can run, now we wait until a CLI command actually attempts to spawn a job, and start the runner there.
Upsides to doing this:
- CLI commands don't need to explicitly declare if they need a runner. This is a big win for the `status` command, which only needs a runner conditionally (if `-refresh` is present). 
- The client package seems like the "right" place for this logic to live - as the primary internal interface to the waypoint APIs, it seems like it should be responsible for abstracting these details. With this change, all of the logic around handling the local …
> Refactor: moving job initialization work into the client package

- .changelog/2799.txt
- internal/cli/base.go
- internal/cli/base_init.go
- internal/client/job.go
- internal/client/project.go
- internal/config/config.go
- internal/pkg/gitdirty/gitdirty.go
Merge after https://github.com/hashicorp/waypoint/pull/2779
This change wires in the vcs detection library introduced in https://github.com/hashicorp/waypoint/pull/2772.
Now that waypoint runs operations remotely wherever possible, users who were previously used to local operations will be exposed to remote ops. They may be used to modifying their `waypoint.hcl` file, running something like `waypoint up`, and expecting the runner to take the change. The remote runner will run off a fresh clone of their repo though, and won't see the change.
We can't _just_ look at the waypoint.hcl file though, because they may have template file directives in there, and some plugins read other files (e.x. docker reads the Dockerfile). There's no good way to detect which files we need to be clean to run a …
> CLI: emit dirty vcs warning for remote operations.

- .changelog/2797.txt
- internal/cli/main.go
- internal/cli/workspace_create.go
- website/content/commands/workspace-create.mdx
- website/data/commands-nav-data.json
This PR adds a simple `workspace create <name>` CLI command for creating workspaces with the `UpsertWorkspace` endpoint. 
Workspaces are a bit limited at the moment, so there really isn't much to do here. The `Upsert` API call does not currently indicate if the workspace already existed or not, so we simply display the same generic "registered with server" response.
> Add Workspace Create command

- internal/server/ptypes/workspace.go
- internal/serverstate/statetest/test_workspace.go
The current regex to validate names used in the `UpsertWorkspace` endpoint does not allow hyphens, which I do not believe were meant to be excluded in valid names in https://github.com/hashicorp/waypoint/pull/2758
Note: no changelog entry because at this time this endpoint is not yet released
> Allow hyphens in workspace names

- internal/server/singleprocess/service_project.go
- internal/server/singleprocess/service_project_test.go
This commit implements some unit tests for the Project API endpoint in
Waypoint Server. Trying to clean up these "TODO: test"
> internal/server: Implement service level unit tests for Project

- .circleci/config.yml
- Dockerfile
This is pretty long in the tooth probably since Go 1.18 now in beta, it just wasn't a priority for us, but I don't see any reason for us to not upgrade to the latest 1.17 version. This updates our CI and Dockerfile. We probably need to update our release repo too.
Don't think we should backport this, and just use it for the next minor.
> Update to Go 1.17

- internal/cli/base.go
- test-e2e/util.go
This should have been removed in #2760 
I ran all the cli smoke tests against this also, which had the added benefit of learning that `cp` works differently on osx vs linux. So now our smoke tests will also work in CI whenever we add them. 🐧 
If anyone is curious:
`cp -r` with a trailing slash on the source dir is supposed to copy _only the contents of the dir_ and not the dir itself. But (at least some flavors, mine included) of linux ignore that rule.
Observe:
```
$ mkdir hey
$ mkdir yo
$ vi hey/ho.txt
$ cp -r hey/ yo
$ ls yo
hey
```
On osx, you'd get:
```
$ ls yo
ho.txt
```
Anyway, happy Friday!
> cli: cleanup unused code path

- .changelog/2815.txt
- internal/cli/base.go
A user can add the `-project` flag when they're in some other project's directory:
Example:
```
$ cd ~/projects/project-a
$ cat waypoint.hcl # it exists
$ waypoint deploy -project=project-b
```
This means one of two things:
1: They added the flag explicitly, and they want to operate against `project-b`.
2: The user wants to operate against the project that matches the directory they're in, but they've copied the `-project` flag from some other command/example.
We could just error here, but it feels onerous to force the user from scenario 1 to `cd` into some safe directory before running their command.
The middle ground here is to continue to allow flags to override config, but issue a warning to help the user from scenario 2. We also force the operation to happen remotely, as the local …
> CLI: Warn if project from flags mismatches project from config

- website/content/docs/waypoint-hcl/registry.mdx
Broken link on the [Registry docs](https://www.waypointproject.io/docs/waypoint-hcl/registry). Without the `/` here the url ends up being `/docs/waypoint-hcl/docs/runner#remote-runner` which is a no-fun [`404`](https://www.waypointproject.io/docs/waypoint-hcl/docs/runner#remote-runner). The page we want is [`/docs/runner#remote-runner`](https://www.waypointproject.io/docs/runner#remote-runner)
> Fix broken link to remote-runners

- ui/package.json
- ui/yarn.lock
the latest upgrade (2.2.x) seemed to be causing some issues:
> lock ember-cli-flash to 2.1

- builtin/docker/task.go
A crash could occur if a container is already removing, since we set err
to nil and then later check `err.Error()`. This crash causes no actual
problems cause the container is already auto-removing, but it makes the
logs noisier than they need to be.
> builtin/docker: fix crash during stop task with ODR

- .changelog/2892.txt
- internal/config/dynamic/func.go
This was discussed heavily in Slack and Google Docs.
`configdynamic` remains functionality indefinitely, its harmless to keep it working for now as long as we note its deprecated and do not document that form.
> internal/config/dynamic: rename configdynamic() to dynamic()

- website/package-lock.json
- website/package.json
Upgrading the downloads page package, which includes some retry logic when fetching release data from releases.hashicorp.com. This should hopefully reduce the likelihood of a failed site deployment immediately after a product release.
> website: upgrade downloads page

- internal/serverinstall/nomad.go
This fixes a dropped `err` variable in `internal/serverinstall`.
> internal/serverinstall: fix dropped error

- .changelog/2901.txt
- ui/app/components/operation-logs/index.hbs
- ui/app/components/operation-logs/index.ts
- ui/tests/helpers/xterm.ts
- ui/tests/integration/components/operation-logs-test.ts
- ui/tests/test-helper.js
Closes #2855
https://user-images.githubusercontent.com/34030/149417773-8e4e1825-ada7-47a3-ba8a-e3e2d15af40c.mp4
https://user-images.githubusercontent.com/34030/149417793-9369d4fb-b597-49b5-8783-e3ab4f59240b.mp4
1. Check out the branch `git checkout ui/operation-logs-attr-change`
2. [Boot the dev server against a waypoint server](https://github.com/hashicorp/waypoint/tree/main/ui#running-with-a-local-waypoint-server)
3. Try navigating between deployments
4. Verify that  the logs are correctly refreshed
> ui: Ensure `<OperationLogs>` reacts correctly when `@jobId` updates

- website/content/docs/upgrading/index.mdx
Missing just a few things on the CLI command to upgrade via helm. Tested by updating from 0.6.3 to 0.7.0.
> Docs: Minor update to upgrading with helm

- Dockerfile
To avoid introducing unexpected changes on each build.
> Pin the build version of the kaniko container

- internal/serverclient/client.go
Extend the dial timeout for our gRPC connection to be 10 seconds, up from 5. I found with Waypoint on ECS the `grpc.DialContext()` call (around line 107 at time of writing) was taking around 6 seconds. Doubled the timeout to be safe. I'm not entirely sure why this method takes so long _sometimes_. For now though this change will greatly reduce the number of `context exceeded` errors from the CLI when talking to Waypoint on ECS
> Allow more time for grpc connection

- website/content/docs/entrypoint/index.mdx
This adds a link to our docs that takes you to the waypoint entrypoint binary download page
> Add link to the entrypoint download page

- flake.lock
This PR updates `flake-utils` to HEAD as of time of writing with the goal of adding support for `aarch64-darwin` from https://github.com/numtide/flake-utils/commit/c5d161cc0af116a2e17f54316f0bf43f0819785c to support anyone that might be using Nix from an Apple M1 host.  The couple additional changes since seemed reasonable to include.
* `nix flake lock --update-input flake-utils`
I believe this will take at least a couple minutes to rebuild your shell for anyone already using nix.  Be forewarned.
Initially I had updated `nixpkgs` as well by blindly running `nix flake update`, however it was not necessary to update `nixpkgs` to get `aarch64-darwin` support and given the rate of change in that repo it seemed inappropriate.  If there's a need for `nixpkgs` to be updated in the future it …
> feat(nix): support nix on aarch64-darwin

- .changelog/2950.txt
- internal/server/singleprocess/service_ui_deploy.go
Prior to this commit, when crafting a Deploy bundle, we would include
the applications deployment URL for each deployment in the bundle.
Looking up this hostname requires making an HTTP request to Horizon. The
way this was originally written, we would look up that URL for all
requested deployments. If a user had 80+ deployments in the bolt db,
this request would take quite some time.
Given that each applications deployment vanity name and hostname should
be the same, and only differs by the deployment sequence, we don't need
to get the hostname for each requested deployment. Instead we can grab
it once, and use it for the remaining deployments in the bundle.
Fixes #2304
In my testing, I had around 180 deployments and the request took about 5 seconds to process.
Now with this fix, the same …
> internal/server: Cache Horizon URL Name and Host for Deploy Bundle

- .changelog/2953.txt
- builtin/docker/builder.go
- website/content/partials/components/builder-docker.mdx
Allow to pass through the no-cache flag to disable the build cache.
This is useful in cases where you want to make sure you're doing a clean build or to mitigate issues with the build cache that arise from time to time.
> plugin/docker: add no-cache option

- .changelog/2968.txt
- internal/cli/base.go
Fix a panic
Before:
```
$ waypoint build -project=example-go1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x10248db40]
github.com/hashicorp/waypoint/internal/cli.(*baseCommand).Init(0x14000d3ce00, {0x14000e1fc60, 0x3, 0x3})
/Users/raekrantz/wp/waypoint/internal/cli/base.go:312 +0x820
github.com/hashicorp/waypoint/internal/cli.(*ArtifactBuildCommand).Run(0x140002b8be0, {0x140001a6860, 0x1, 0x2})
/Users/raekrantz/wp/waypoint/internal/cli/artifact_build.go:23 +0xb4
github.com/mitchellh/cli.(*CLI).Run(0x14000c0a000)
/Users/raekrantz/go/bin/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5c4
github.com/hashicorp/waypoint/internal/cli.Main({0x14000186090, 0x3, 0x3}) …
```
> replace nil value with non-nil value

- pkg/server/ptypes/release.go
- pkg/server/ptypes/workspace.go
- pkg/server/sort/config.go
- pkg/server/sort/release.go
- pkg/serverstate/statetest/test_artifact.go
- pkg/serverstate/statetest/test_build.go
- pkg/serverstate/statetest/test_config.go
- pkg/serverstate/statetest/test_config_source.go
- pkg/serverstate/statetest/test_deployment.go
- pkg/serverstate/statetest/test_instance.go
- pkg/serverstate/statetest/test_job.go
- pkg/serverstate/statetest/test_release.go
- pkg/serverstate/statetest/test_runner.go
- pkg/serverstate/statetest/test_server_config.go
- pkg/serverstate/statetest/test_server_urltoken.go
- pkg/serverstate/statetest/test_snapshot.go
- pkg/serverstate/statetest/test_status_report.go
- pkg/serverstate/statetest/test_workspace.go
Most timeouts were adjust to 3 seconds when the operation is expected to
block, allowing the state implementation more freedom about how quickly
it can detect and signal WatchSets.
This also brings out a config var sorted implementation that was embedded in singleprocess to be more general so other state implementations can use it.
> statetest: Add missing tests and make timeouts more flexible

- internal/cli/runner_token.go
- internal/server/singleprocess/auth.go
- internal/server/singleprocess/auth_test.go
- internal/server/singleprocess/service_runner.go
- internal/server/singleprocess/service_runner_test.go
- internal/server/singleprocess/state/runner.go
- pkg/server/ptypes/runner.go
- pkg/server/ptypes/runner_test.go
- pkg/serverstate/statetest/test_runner.go
- website/content/commands/runner-token.mdx
This improves #2935 by making adoption label-aware. If a label set changes, the adoption state of a runner is reset. Additionally, runner tokens include a hash of the labels they're minted for, so if the label changes, tokens are invalidated.
This prevents the following insecure scenario: a runner registers and is adopted with a set of labels for development targeting. After adoption, the runner restarts with a set of labels for production targeting. With this PR, this scenario would result in the runner reseting to the un-adopted state and the previously distributed tokens becoming invalid.
For pre-adoption, users can specify the `-label` flag to the `waypoint runner token` command to create a token for a specific set of labels.
> Hash labels as part of runner tokens and adoption

- website/content/plugins/aws-lambda.mdx
Fix html string in lambda docs
> fix(docs): aws-lambda typo

- internal/config/config.go
^ yup!
Original idea was to have `profile = ""` even if the user doesn't want to define any profile and have the server choose a default, but after considerations this is redundant and will bug out if the user omits this field.
> Make runner profile optional in waypoint HCL

- Makefile
- tools.Dockerfile
This introduces a new method to generate protos. You can run `make docker/tools` go create a new local docker container that contains all the tools in `tools/tools.go` and the correct version of protoc, then run `make docker/gen/server` to regenerate protobufs using that container.
This is an alternative to:
- Building protos locally by downloading the correct version of `protoc` locally and installing it (and its includes), and running `make tools; make gen/server`. 
- Building protos in nix with `nix-shell; make gen/server`
The downside here is that we're pinning the protoc version in the dockerfile, so if we upgrade protoc we'll need to update both here and in nix. I don't know of a great way to extract the `v3.15.8` from the nix definitions.
> Add tooling to generate protos with docker

- website/content/docs/exec.mdx
- website/content/docs/kubernetes/container-build.mdx
- website/content/docs/triggers.mdx
Found 3 broken links with `$ ack "]\(docs" website/content`. I did not find any for `commands` or `plugins`, the other two main sections of the site
> Fix some broken links in website documentation

- .changelog/3040.txt
- internal/cli/config_set.go
Currently, if the scope is set explicitly as "app" without an app provided, we set the scope with an empty app. We should return a helpful error message instead.
_Before:_
```
❯ waypoint-dev config set -scope=app tester=test
❯ waypoint-dev config get
SCOPE  |  NAME  | VALUE | WORKSPACE | LABELS  
----------+--------+-------+-----------+---------
project | test   | test  |           |         
app:    | tester | test  |           |        
```
_After:_
```
❯ waypoint-dev config set -scope=app testt=test
-scope requires -app set if scope is 'app'
```
> cli: Requires `-app` flag if `config set -scope=app` is set.

- internal/runner/runner.go
- internal/server/singleprocess/auth.go
- pkg/server/testing.go
The gRPC web client will send browser cookies automatically using the
"cookie" metadata. We don't want to conflict with anything because
invalid cookie values cause API requests to fail. This commit replaces
"cookie" with "wpcookie" but is otherwise functionally identical.
> Rename "cookie" metadata to "wpcookie"

- .changelog/3044.txt
- internal/cli/context_create.go
- website/content/commands/context-create.mdx
The flag was unused before this point. This also sets the default state to "true", which is what I think most users would expect.
```
$ waypoint context create is-default
$ waypoint context list
|         NAME         |  PLATFORM  |                                    SERVER ADDRESS
----+----------------------+------------+----------------------------------------------------------------------------------------
* | is-default           | n/a        |
$ waypoint context create -set-default=false not-default
Context "not-default" created.
$ waypoint context list
|         NAME         |  PLATFORM  |                                    SERVER ADDRESS
----+----------------------+------------+----------------------------------------------------------------------------------------
* | is-default …
```
> Fix the -set-default flag for `context create`.

- internal/cli/context_create.go
- website/content/commands/context-create.mdx
The CLI package will append the default value of a flag automatically so
no need to include it ourselves.
> fixup: Don't include default value

- .changelog/3035.txt
- builtin/aws/alb/releaser.go
This fixes a `DuplicateListener` error on subsequent `waypoint up`'s, after the first.
The error occurs with both the [`aws/ec2`](https://github.com/hashicorp/waypoint-examples/blob/main/aws/ec2/waypoint.hcl#L28-L32) and [`aws/lambda/ruby`](https://github.com/hashicorp/waypoint-examples/blob/main/aws/lambda/ruby/waypoint.hcl#L23-L24) examples which both use the `aws-alb` releaser
Closes https://github.com/hashicorp/waypoint/issues/2066
> fix(aws-alb): DuplicateListener on 2nd `up`

- .changelog/3052.txt
- internal/cli/runner_agent.go
Without this, with the helm runner-only install using the adoption flow, the runner pauses
waiting to be adopted before starting it's health check. It sits in that state for 10 seconds,
then k8s gives up on it and terminates it becasue it's failed too many health checks.
Verified through local testing
> Start runner liveness check _before_ starting the runner.

- .changelog/3055.txt
- internal/cli/context_create.go
- website/content/commands/context-create.mdx
Prior to this commit, there was no way for the CLI to set the server
platform when creating a context. This commit enables that flow by
introducing a string var flag so it can be set on creation.
> cli: Enable context create to set the server platform

- internal/cli/app_docs.go
- website/content/partials/components/configsourcer-aws-ssm.mdx
- website/content/partials/components/configsourcer-null.mdx
- website/content/partials/components/configsourcer-terraform-cloud.mdx
- website/content/partials/components/configsourcer-vault.mdx
Maybe this was a problem introduced in #868?
> docs: Fix typo for config source-set

- .changelog/3054.txt
- internal/server/singleprocess/service_job.go
- internal/server/singleprocess/service_job_test.go
Prior to this commit, if the state package returned nil or nothing for
an on-demand runner config based on the id set for a job, Waypoint would
still attempt to queue the job with a nil ODR config. This leads to a
panic immediately after when we attempt to set environment variables
from the ODR config for the job on a nil config. This commit fixes that
by returning an error if the requested ODR config does not exist in the
state database.
This is related to https://github.com/hashicorp/waypoint/issues/3051 but
mainly fixes the bad behavior with the panic, not the core bug of a invalid
or missing ODR config set on a job.
> internal/server: Ensure on-demand runner config exists before start job

- internal/server/singleprocess/state/runner.go
- pkg/server/gen/server.pb.go
- pkg/server/proto/server.proto
- pkg/serverstate/statetest/test_runner.go
Some [cleverness in modifying the `runner list` led to a change in output. ](https://hashicorp.slack.com/archives/C013QT1KG9W/p1646232325910549)This changes the protobuf to make the cleverness work.
> change runner adoption protobuf

- internal/client/job.go
Currently, if you have a default runner profile but no project-specific target, the waypoint server fails the job with the following error: `no runner profile name or id specified`. This is because the client's `waypointHCL.ConfigRunner()` is returning non-nil, but the profile field is an empty string, so the job is getting a runner profile assigned (but with an empty profile string).
The server is expecting a nil odr profile on a job to mean "no preference" [here](https://github.com/hashicorp/waypoint/blob/ff4406443d64d5f16812bef32d8b4428656aae6e/internal/server/singleprocess/service_job.go#L171), not an assigned profile with an empty string.
This fixes the problem by not assigning an odr profile to the job unless the profile name is actually set.
> Do not add ODR profile to job if profile is empty

- .changelog/3067.txt
- internal/cli/job_cancel.go
- internal/cli/job_get_stream.go
- internal/cli/job_inspect.go
- internal/cli/job_list.go
- internal/cli/main.go
- internal/client/job.go
- website/content/commands/job-cancel.mdx
- website/content/commands/job-get-stream.mdx
- website/content/commands/job-inspect.mdx
- website/content/commands/job-list.mdx
- website/data/commands-nav-data.json
This pull request introduces a new CLI command `waypoint job`. It includes subcommands for listing active jobs, inspecting a job, canceling a job, and a future TODO of attaching and outputing the job stream. It also updates the Operation queue message to include the job ID so users can check the status of a job while they're waiting and potentially cancel it if it's stuck.
Fixes https://github.com/hashicorp/waypoint/issues/3064
Fixes https://github.com/hashicorp/waypoint/issues/3063
> Feature: `waypoint job` CLI

- internal/cli/job_list.go
Prior to this commit, we relied on the job list being in order from the
database. This is fragile, so instead we first sort by compeltion time
before formatting the job list table.
Fixes #3078
> cli: Sort jobs by timestamp completetime before format

- .changelog/3070.txt
- builtin/k8s/platform.go
If for some reason a previous deployment is not found and on `waypoint up` we try to remove it, the entire operation will be reported as a failure even if we successfully deployed a new version.
Here we check for not found, and simply continue
> K8s: Don't error build/deploy/release because a previous deployment isn't found

- .changelog/3081.txt
- internal/cli/artifact_build.go
- internal/core/app_build.go
- internal/core/app_deploy.go
- internal/core/app_deploy_destroy.go
- internal/core/app_push.go
- internal/core/app_release.go
- internal/core/app_release_destroy.go
- internal/core/app_status_report.go
- internal/core/operation.go
Currently, when you run an operation on the CLI, there's no great way to know later which operation you just ran. I.e. you can run `waypoint build`, and later run `waypoint artifact list-builds` and assume the highest-numbered build is the one you just created, but you can't really know for sure. This also makes it hard to correlate between the CLI and the UI.
This change adds a new step group, printing `⠏ Running build v18`, or `⠏ Running deploy v3`, or equivalent, to every operation. It completes when the full op completes.
For artifacts in particular, this also prints the id of the produced artifact, if any (which is distinct from the build)
Example:
> CLI display improvements to operations

- .changelog/3087.txt
- internal/runner/config.go
- internal/runner/runner.go
- internal/runner/runner_test.go
This is the first body of work towards making runners more resilient to servers being down (and ultimately vice versa). This part focuses on the server going down or already being down during the runner startup process. 
This PR makes the runner able to tolerate the following conditions:
1. Server down prior to the runner ever starting - the runner blocks and attempts to reconnect
2. Server goes down while waiting on adoption - the runner reconnects and restarts the adoption (which is idempotent)
3. Server goes down after adoption but before the initial config stream - reconnect and re-establish initial config stream
4. Server goes down after start (adoption and config established) - reconnect to the config stream in the background
Prior to this PR, all four scenarios above would crash or …
> Runner resilience part 1/N: startup resilience to server being down or going down

- .changelog/3095.txt
- internal/cli/plugin.go
- website/content/commands/plugin.mdx
Prior to this commit, if a user just ran `waypoint plugin` with no
arguments, the CLI would panic assuming that an argument was passed in.
This commit fixes that by looking at the argument slice and printing an
error if none was passed in. It fixes up some of the other panics to
print errors and return 1.
> cli: Fix panic in `waypoint plugin` cli

- internal/runner/accept.go
- internal/runner/accept_test.go
- internal/runner/config.go
- internal/runner/runner.go
This starts by addressing only the initial job stream opening. This still does not add any resilience after the job stream is open (i.e. when a job is running).
I'm opening this PR early since this required some changes to how we track the state of the underlying runner config and it is complex enough on the surface that I didn't want to complicate a future PR. Additionally, this PR on its own still incrementally makes the runner more resilient to failure modes.
This PR builds on #3087 and adds the following scenarios the runner can now withstand:
* The server goes down after runner start but prior to `Accept`.
* The server goes down during `Accept` (its a stream, so while the initial handshake is blocking)
* The runner registration is disconnected at some point prior to or during …
> internal/runner: make Accept resilient to the server going down

- internal/server/singleprocess/service_runner.go
- internal/server/singleprocess/service_runner_test.go
- internal/server/singleprocess/testing.go
- pkg/server/gen/server.pb.go
- pkg/server/gen/server.swagger.json
- pkg/server/proto/server.proto
This fixes a possible vulnerability with runner adoption. Note this
vulnerability is not in any released Waypoint version, so there is no
broad communication necessary.
We were not validating the runner token against the runner identity for
RunnerJobStream. So long as the token was valid, any runner could
request a job impersonating any other runner. This did require that the
runner was authenticated already.
This adds token verification and a unit test to validate it.
> internal/server: RunnerJobStream verifies runner tokens

- Makefile
If you don't have a `waypoint` file at `$(GOPATH)/bin` then `make install` fails here.
But you could just as easily `touch $GOPATH/bin/waypoint`.
> chore: `make install` conditionally remove existing waypoint file

- .changelog/3076.txt
- builtin/aws/alb/releaser.go
This fixes a bug where the load balancer zone id was being used instead of the Route53 zone id for deleting a resource record.
This closes https://github.com/hashicorp/waypoint/issues/3075
> fix(aws-alb): destroy r53 record

- builtin/vault/config_sourcer.go
- website/content/partials/components/configsourcer-vault.mdx
This PR attempts to improve the current ambiguous description of the `key` parameter in the `vault` configsourcer doc:
https://www.waypointproject.io/plugins/vault#key
Basically, keys stored in the "KV2" (KV version 2) secret engine must be prefixed with `/data`.
```hcl
PASSWORD_KV1 = dynamic("vault", {
path = "kv1/my-secret"
key = "password"
})
PASSWORD_KV2 = dynamic("vault", {
path = "kv2/data/my-secret"
key = "/data/password"  # super confusing
})
```
ref. https://github.com/hashicorp/waypoint/blob/v0.7.2/builtin/vault/config_sourcer.go#L188
This is how `cachedSecretVal.Secret.Data` looks different between KV and KV2:
KV:
> map[string]interface {}{“password”:“foobar”}
KV2:
> map[string]interface {}{“data”:map[string]interface {}{“password”:“foobar”}, “metadata”:map[string]interface …
> builtin/vault(docs) clarify `key` value format difference

- .changelog/3068.txt
- builtin/aws/ecs/platform.go
- builtin/aws/ecs/platform_test.go
- website/content/partials/components/platform-aws-ecs.mdx
This is to support deploying Docker images built by the Apple M1 chip to ECS:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-arm64.html
Adding new `cpu_architecture` parameter (optional, no default value):
```hcl
app "example-nodejs" {
labels = {
"service" = "example-nodejs",
"env"     = "dev"
}
build {
use "docker" {}
registry {
use "aws-ecr" {
region     = "ap-northeast-1"
repository = "waypoint-example"
tag        = "latest"
}
}
}
deploy {
use "aws-ecs" {
region = "ap-northeast-1"
memory = "512"
cpu_architecture = "ARM64"
}
}
}
```
NOTE: Currently, this only works with the `docker` build plugin, and not with the `pack` plugin. But I believe that's due to the upstream buildpacks issue with arm64, not coming from Waypoint itself.
> builtin/aws: add `cpu_architecture` aws-ecs parameter

- Makefile
Some of our make commands referenced the old path to our protobufs. This fixes the `make gen/doc` and `make gen/ts` commands.
Closes https://github.com/hashicorp/waypoint/issues/3080
> Fix paths to proto files

- internal/cli/artifact_list.go
- internal/cli/deployment_list.go
- internal/cli/release_list.go
It's up to the server to choose the order (based on the -order-by and -desc flags).
NOTE: the server, in practice, doesn't respect any of the ordering flags. It only references the COMPLETE_TIME index (in app_operation), and totally ignores `-desc` and `-order-by=start-time` options.
In practice, this doesn't change any behavior - operations always come in ordered by sequence id, descending. But this opens the door for us to fix this in the server later (or for other server implementations to do this right).
> CLI respects server ordering

- .changelog/3133.txt
- internal/cli/runner_list.go
Adds a "labels" column in `runner list`.
```
❯ waypointdev runner list
ID             |   STATE    |  KIND  |          LABELS           | LAST REGISTERED  
-----------------------------+------------+--------+---------------------------+------------------
prod-static                | adopted    | remote |                           | 1 month ago      
dev-static                 | preadopted | remote |                           | 1 week ago       
01FYT7AKV1QNPDYKE1WNH87TH4 | preadopted | remote | region:testland env:test  | 5 seconds ago   
```
> `runner list` shows runner labels

- .changelog/3111.txt
- builtin/k8s/releaser.go
If a K8s deployment has multiple active deployments and a user runs `waypoint destroy -auto-approve`, Waypoint will hang trying to destroy the service multiple times. 
Here we check to see if the service is not found, and if so simply continue.
> K8s: Don't error/hang if deleting a service that isn't found

- .changelog/3136.txt
- internal/cli/runner_profile_set.go
- pkg/server/gen/server.pb.json.go
- website/content/commands/runner-profile-set.mdx
Per an internal discussion, we have decided to standardize using singular flags with `-flag=key=value` format to define repeatable configuration variables.
For example, instead of:
`runner profile set -plugin-type=docker -env-vars="foo=bar,bar=baz"`
the new standard is:
`runner profile set -plugin-type=docker -env-var=foo=bar -env-var=bar=baz`
> Deprecate `-env-vars` flag in `runner profile set`, replace with `-env-var`

- .changelog/3142.txt
- ui/app/controllers/workspace/projects/project/app/release.ts
- ui/app/routes/workspace/projects/project/app/release.ts
- ui/app/templates/workspace/projects/project/app/release.hbs
- ui/mirage/factories/release.ts
- ui/tests/acceptance/release-detail-test.ts
This button/link wasn’t working. Looks like it night never have worked. The tell-tale sign is the presence of `@isLatest` in the template. The only `@argument` route templates receive is `@model`. `@isLatest` will always be falsey. This adds the release URL back in.
1. `git checkout ui/fix-release-url-button`
2. `cd ui`
3. `yarn start`
4. `open http://localhost:4200/default/marketing-public/app/wp-matrix/release/seq/3`
5. Verify you see the release URL
> ui: fix release URL button

- website/package-lock.json
Errors like this:
https://app.circleci.com/pipelines/github/hashicorp/waypoint/14697/workflows/3a77dcb4-5de1-4500-bc0b-e6a877fca128/jobs/150782
Not exactly sure when/why the formatting changed, but hopefully this will keep us moving.
> website: commit reformatted `package-lock.json`

- .changelog/3158.txt
- internal/runner/operation_poll.go
- pkg/server/singleprocess/poll_application.go
- pkg/server/singleprocess/poll_test.go
Prior to this commit, our poll operation would set the poll jobs
singleton Id to Project/App/Workspace. However not all project
poll operations have an application, such as the initial QueueProject
operation. In this case, we only set Workspace and Project. This means
the singletonId for the Job included a double slash, such as:
```
poll-trigger/go-gitops-0//default
```
Where the application was not set for the job.
This commit fixes this by rearranging the singleton to start at
Workspace, Project, and then optionally Application if exists on the
job.
Discovered via https://github.com/hashicorp/waypoint/issues/3157
edit: This pull request also enhances the application status report poll singletonId to include the workspace and project it belongs to. Otherwise this would of been a job …
> internal: More Descriptive SingletonIds for Poll Jobs

- pkg/serverstate/statetest/test_runner_ondemand.go
`reflect.DeepEqual` doesn't serve us here - the proto messages have weird internal fields that differ that we don't care about. If anyone knows a more efficient way to compare these structs i'm all ears.
> Test getting and setting all odr config fields

- tools/tools.go
Turns out, leading whitespace is not allowed for go generate commands.
> Fixing `make tools`

- .changelog/3143.txt
- builtin/k8s/platform.go
- builtin/k8s/task.go
Fixes https://github.com/hashicorp/waypoint/issues/2641 by deleting the Kubernetes job and examining any pods stuck in `Pending` for the given job. Optionally we can expand to delete [other pods phases](https://pkg.go.dev/k8s.io/api@v0.23.5/core/v1#PodPhase) like `Running` or `Failed`, but for now it's just `Pending`
> Delete job and pods in k8s StopTask if stuck in pending

- .circleci/config.yml
Prior to this commit, any changes at all from running `make
gen/website-mdx` would notify a failure. This is extra tricky because
npm and lock files might change which causes `git diff` to notify the PR
that a failure occured. In reality, this check was only to tell the PR
author that they needed to run `make gen/website-mdx` to generate CLI
docs automatically. This commit updates that behavior to only check a
`git diff` in the `website/content` folder, where the auto generated
docs live.
> ci: Only notify PR check failures if `website/content` has changes

- internal/cli/job_list.go
Prior to this commit, when the job list CLI would sort on Complete time,
jobs with a nil complete time would be sorted as "oldest". Really as a
user you would expect these to show up as "latest" with no complete time
field set. This commit fixes the original behavior to make these jobs
show up at the beginning when there is no complete time set.
> cli: Sort uncomplete jobs as "latest"

- internal/server/boltdbstate/job.go
- pkg/server/logstream/logstream.go
- pkg/server/singleprocess/logstream.go
- pkg/server/singleprocess/service_job.go
- pkg/server/singleprocess/service_job_test.go
- pkg/server/singleprocess/service_runner.go
This is the last in a series of PRs meant to make our service handlers consumable by other projects.
Previous PRs in this series:
https://github.com/hashicorp/waypoint/pull/3169
https://github.com/hashicorp/waypoint/pull/3149
This PR focuses on service_job.go. This adds a new `Reader` method to the `LogStreamProvider`, which allows other projects to inject a log stream reader and not depend on the built-in singleprocess reader.
This should not change any behavior or functionality.
> Consumable job service handlers

- .changelog/3200.txt
- internal/server/boltdbstate/runner.go
Prior to this commit, if the server ever restarted, the runner db would
fail to parse the correct bucket in the server. This also means server
upgrades would fail with an invalid wire format. This commit fixes that
by ensuring the runner init uses the proper runner bucket.
Fixes #3192
> internal/server: Set correct bucket var for runnerIndexInit

- tools/tools.go
Currently, running `make format` will modify [tools/tools.go](https://github.com/hashicorp/waypoint/blob/993c2759d929b8dd5b35c30831a51fa95daa8ef5/tools/tools.go) in such a way that will break code generation, as `//go:generate` statements [must start at the beginning of the line](https://go.dev/blog/generate). Having these statements in the `import` block was causing `gofmt` to indent them. 
In this PR we simply move `//go:generate` commands above the `import` block.
> Restructure tools/tools.go to prevent gofmt issue

- Makefile
This commit adds two makefile target helpers for running the full test
suite for both boltdbstate and the service API functions.
> Makefile: Add make targets for running full state and service tests

- .changelog/3196.txt
- internal/cli/server_run.go
Without the context argument, the casting always failed and we’d never show the prompt with the bootstrap command.
1. `git checkout cli/run-bootstrap-fix`
2. `make bin`
3. `rm data.db`
4. `./waypoint server run -accept-tos`
5. Verify you see the bootstrap message
> cli: Pass context to `Bootstrapped` in `server_run`

- .changelog/3197.txt
- builtin/k8s/platform.go
I noticed that the following configuration did not apply the env vars to the app container as expected.
```hcl
deployment {
use "kubernetes" {
pod {
container {
static_environment = {
"MY_COOL_ENV_VAR" = "MY_COOL_VALUE"
}
}
```
1. `git checkout k8s/container-static-env`
2. `make bin`
3. Configure a deployment with `pod.container.static_environment` as above
4. Deploy
5. Verify the defined env vars were applied to the app container correctly
6. Try hoisting the `static_environment` config:
```hcl
deployment {
use "kubernetes" {
static_environment = {
```
7. Deploy again
8. Verify the env vars are still applied correctly
> builtin/k8s: Ensure `pod.container.static_environment` is applied

- .changelog/3207.txt
- internal/cli/release_create.go
If the most recently created deployment is running, and you attempt `waypoint release`, prior to this we would attempt to release that unfinished depoyment, and panic downstream in argmapper.
With this change, it's still possible for `waypoint release` (with no deployment targeting flag) to pick a running deployment, but at least the user will have a hint as to what has happened and can choose a different deploy to release, or wait, or delete the stuck running deployment.
This prevents the argmapper panic: https://github.com/hashicorp/go-argmapper/pull/11
> Prevent the release of a running deployment

- .changelog/3193.txt
- builtin/aws/lambda/platform.go
- builtin/aws/lambda/platform_test.go
- This adds `aws-lambda` platform config validation for `timeout` and `architecture`
- This updates the platform test
> chore: add lambda platform config validation - add tests

- Makefile
- pkg/serverstate/statetest/doc.go
Adds ability to run a specific state test to the `test/boltdbstate` make target and some minimal docs explaining
> Adds $TESTARGS option to test/boltdbstate step, with doc/example

- builtin/nomad/jobspec/releaser.go
This fixes a dropped `err` variable in `builtin/nomad/jobspec`.  No changelog entry is warranted.
> builtin/nomad/jobspec: fix dropped error

- .changelog/3226.txt
- internal/cli/exec.go
The `-workspace` flag was not passed to `ListDeployments()` when running
`waypoint exec`. This resulted in erratic `waypoint exec` behavior, as
any deployment from any workspace became a candidate to execute the given
command.
Fixes #3224
> `internal/cli`: Fix `waypoint exec` workspace selection 

- ui/app/components/project-input-variables/list.hbs
The `Add variable` button in the `true` block was missing the `"button--add-variable"` CSS class, causing the icon to become misaligned when the component was displaying existing input variables / add new input variable form.
Before:
After:
This matches how it's implemented in [`waypoint/ui/app/components/project-config-variables/list.hbs`](https://github.com/hashicorp/waypoint/blob/main/ui/app/components/project-config-variables/list.hbs)
Closes https://github.com/hashicorp/waypoint/issues/3175
> UI: Fix Add variable icon is misaligned

- builtin/k8s/config_sourcer.go
- website/content/partials/components/configsourcer-kubernetes.mdx
It's not immediately obvious in the docs that to read a Kubernetes
secret, you must set secret to be true. This commit adds some additional
notes at the top level description of the kubernetes dynamic config
plugin to explain this.
> docs: Include an additional note about reading a Secret vs ConfigMap

- pkg/server/singleprocess/service_job_test.go
Fixes the flaky TestServiceGetJobStream_bufferedData test 🤞 
Brief summary of the problem:
We were emitting job stream events, then connecting to a stream immediately, and assuming they would be buffered. In some cases, we read before the event finishes percolating through the tubes, so it comes through as an unbuffered event.
We could probably just sleep for a few millis after emitting the events, but this method should be more deterministic! We open a separate job stream, and wait for _it_ to see all the events. Good idea @demophoon !
Thanks Brian, Shirley, and Britt for the debug swarming
> Avoid race condition reading job stream data before it's buffered.

- pkg/server/singleprocess/service_job.go
- pkg/server/singleprocess/service_job_test.go
- pkg/server/singleprocess/service_runner.go
To fix this, we need to retry a connection until we get buffered data.
We have to do this because the buffered data is read on connection and
immediately queued to send. It is not dependent on the client receiving
(though, it'll block due to TCP backpressure if they aren't receiving).
> pkg/server: fix flaky test around buffered data

- ui/app/components/app-form/project-repository-settings.ts
Addresses https://github.com/hashicorp/waypoint/security/code-scanning/34
Hopefully identical to `main`.
1. `git checkout ui/code-scanning-34-fix`
2. `cd ui && yarn && yarn start`
3. [localhost:4200](http://localhost:4200)
4. Visit the project settings screen
5. Try changing project settings
6. Verify that the new values are applied correctly
> ui: guard against prototype pollution

- .changelog/3262.txt
- internal/cli/ui.go
Prior to this commit, if Waypoint had no contexts locally on disk, it
would still attempt to load one with an empty name, resulting in an
error about a nil context. This commit fixes that by first seeing if any
contexts exist at all, or if there's no default, showing a better error
message to tell the user what to do about it.
Fixes #3243
I paired with @demophoon on fixing this one!
> cli: Show error message if no Waypoint contexts found

- .changelog/3266.txt
- internal/cli/runner_list.go
Papercut fix
Before:
```
$ waypoint runner list
$
```
After:
```
$ waypoint runner list
No runners found
$
```
> add cli output if no runners found for 'list'

- go.mod
- go.sum
Picks up a minor change (https://github.com/hashicorp/go-argmapper/pull/11)
> Upgrading argmapper to v0.2.4

- builtin/vault/config_sourcer.go
- website/content/partials/components/configsourcer-vault.mdx
Missing 2 end quotes in example hcls
> Fix missing end quotes in configsourcer-vault.mdx

- .changelog/3253.txt
- builtin/docker/pull/builder.go
- builtin/docker/pull/kaniko.go
Closes #2780 & #3117.
Implementation is very similar to that of the Docker builder plugin, except the Dockerfile is created by this plugin & supplied to Kaniko with only a single line, containing `FROM` followed by the image & tag.
> Support remote operations for docker-pull

- website/content/docs/server/auth/oidc.mdx
Adds a note about using `-allowed-redirect-uri` when setting up UI-based OIDC auth. This was brought up in https://discuss.hashicorp.com/t/waypoint-oidc-issues/37428/5
> Docs: add allowed-redirect-url section

- internal/server/boltdbstate/state_test.go
- pkg/server/ptypes/ondemand_runner.go
- pkg/serverstate/statetest/statetest.go
- pkg/serverstate/statetest/test_runner_ondemand.go
Currently, there's no good way for any other project consuming these tests to selectively skip any of them. Maybe there will be [as of go 1.19](https://github.com/golang/go/issues/41583), but until then, this introduces a new "skipTests" argument that allows users to pass in test names to skip.
> Allow some state tests to be skipped

- .changelog/3299.txt
- builtin/k8s/task.go
https://github.com/hashicorp/waypoint/pull/3143 introduced changes to remove pods/jobs if any of the pods were stuck in pending. As written it unintentionally introduced a bug where no pods were getting automatically cleaned up, because we always destroyed the job when `StopTask` was called. This prevented the auto cleanup of pods via the `TTLSecondsAfterFinished` setting in the job spec.
In this PR we only destroy the job if it has any pods stuck in pending, otherwise we let Kubernetes clean things up when the TTL expires.
> Bug fix: Patch k8s stop task to only delete the job if it had pending pods

- .changelog/3300.txt
- internal/cli/runner_agent.go
- internal/runner/accept.go
- internal/runner/accept_test.go
- website/content/commands/runner-agent.mdx
This modifies `internal/runner` to support accepting multiple jobs in
parallel. Not much work here since we always designed the runner struct
from the beginning to support this so there are no data races.
This modifies `internal/cli` so that runners in non-ODR run in parallel
mode by default. ODR doesn't make sense to have any parallelism since
they always run exactly one job. Non-ODR runners typically ONLY launch
ODR tasks, which are highly IO-bound, so we default to a multiple above
CPU count for concurrency.
This is a necessary pre-requisite for pipelines since they'll likely
perform blocking jobs on the static runners to "watch" tasks. Today,
tasks are launched and stopped, but not watched so this is not an issue.
> runner: static runners accept multiple jobs in parallel

- contrib/serverinstall/kind-k8s/README.md
- contrib/serverinstall/kind-k8s/setup-k8s.sh
Due to a bug in Kaniko, there are issues with on-demand runners on the
latest version of Kubernetes, version 1.23. This commit updates the
contrib helper script to install 1.22 by default.
No changelog since this is a local dev helper script.
> contrib: Specify explicit Kind/K8s version in setup script 

- .changelog/3307.txt
- builtin/k8s/task.go
- internal/serverinstall/k8s.go
- website/README.md
- website/content/commands/install.mdx
- website/content/commands/server-install.mdx
- website/content/partials/components/task-kubernetes.mdx
This PR adds plumbing to enable users to add CPU and memory limits to on-demand runner profiles.
Closes #3047
> plugin/k8s: Add CPU/Memory resource limits to ODR

- .changelog/3322.txt
- builtin/k8s/task.go
Prior to this commit, if a certain version of Kaniko was used with the
current latest version of Kubernetes 1.23, Kaniko would fail to detect
that it was being run inside a container. This means Waypoint would then
faill back to try to use Docker inside a container for the build step.
This commit fixes this by setting the proper env var for Kaniko and
keeps ODR remote builds working.
Fixes #2984
> builtin/k8s/task: Explicitly set container env var for Kaniko

- .changelog/3279.txt
- internal/serverinstall/nomad.go
- website/content/commands/install.mdx
- website/content/commands/server-install.mdx
Closes #2801.
In keeping with the current pattern of supplying flags to the install command, this PR adds two new flags to the Nomad install. These flags are for persistence for Waypoint in Nomad provided by CSI (both of which are maps of strings):
- `-nomad-csi-secrets`
- `-nomad-csi-parameters`
> Support CSI parameters & secrets with Nomad install

- .changelog/3287.txt
- builtin/nomad/jobspec/platform.go
- go.mod
- go.sum
- website/content/partials/components/platform-nomad-jobspec-canary.mdx
- website/content/partials/components/platform-nomad-jobspec.mdx
Use [new API in Nomad](https://github.com/hashicorp/nomad/pull/12777) to parse a jobspec as HCL1 instead of HCL2.
Closes #3294.
> Support HCL1 Jobspec for Nomad

- pkg/serverhandler/handlertest/doc.go
I was trying to run an individual tests and noticed that the suggested `TestImpl` run string didn’t have the desired effect.
> serverhandler: tweak docs

- internal/config/pipeline.go
- internal/config/pipeline_test.go
- internal/config/testdata/pipelines/pipelines_many.hcl
- internal/core/pipeline.go
- internal/core/pipeline_config.go
- internal/core/project.go
This commit introduces a way for runners to initiate a pipeline config
sync. It loads the HCL eval context, evals the config, and translates the
parsed pipeline struct into a Proto Pipeline that is upserted to the server.
I've got a couple of questions that I'll ask as a PR comment, otherwise
this PR is ready for review!
> internal/core: Add ConfigSync for pipeline configs

- internal/server/boltdbstate/task.go
- pkg/server/singleprocess/service_job.go
- pkg/server/singleprocess/service_job_test.go
Prior to this commit, there was a bug with ODR and generating the Stop
Task job. If a plugin did not implement WatchTask, the WatchTask job would fail,
which would invoke the StopTask job and break the task state machine while the
main job was still running. This commit fixes that behavior by ensuring
that if a source job has no overrides defined and is not expected to
skip the operation, the source id gets added as a dependent for the stop
task.
> server: Ensure primary ODR job gets added as dependency

- builtin/nomad/jobspec/platform.go
- website/content/partials/components/platform-nomad-jobspec-canary.mdx
- website/content/partials/components/platform-nomad-jobspec.mdx
Add note to the docs regarding Nomad interpolation for the jobspec plugin being used with Waypoint's `templatefile` function. Closes #1615 .
> Nomad interpolation doc note

- .changelog/3282.txt
- builtin/aws/lambda/platform.go
- builtin/aws/lambda/plugin.proto
- website/content/partials/components/platform-aws-lambda.mdx
Note: this PR is temporarily based off https://github.com/hashicorp/waypoint/pull/3213 because of a bug fix that it contains to wait for the lambda config to finish updating before updating the function code.
This adds `static_environment` to the `aws-lambda` `deploy` component
example usage
```hcl
deploy {
use "aws-lambda" {
region = var.region
memory = 512
static_environment = {
"PORT" = "8001"
"READINESS_CHECK_PORT" = "8001"
}
}
}
```
Closes #2947
> feat(aws-lambda): `static_environment`

- go.mod
- go.sum
- internal/cli/init.go
This commit upgrades the go-getter library to the latest release, and
explicitly configures the Getters for its client in Waypoint CLI.
> internal/cli: Upgrade go-getter library to latest

- internal/client/job.go
- internal/jobstream/doc.go
- internal/jobstream/option.go
- internal/jobstream/stream.go
- internal/jobstream/stream_test.go
- internal/jobstream/test/doc.go
- internal/jobstream/test/stream_test.go
- internal/jobstream/ui.go
- internal/runner/operation_pipeline_step.go
This extracts job stream handling from `internal/client` into a dedicated, reusable package. See the tests and `internal/client` for usage. The goal here for pipelines is to be able to build on this to implement `pipeline run`. 
@briancain For an _initial_ step at `pipeline run`, I was thinking we just for loop over the returned IDs and just stream them _sequentially_. It isn't perfect but it gets us started. We can do smarter stuff later.
> Extract `internal/jobstream` from `internal/client`

- website/content/docs/troubleshooting.mdx
This adds 1 additional `kubectl` cleanup command to 
https://www.waypointproject.io/docs/troubleshooting#waypoint-server-in-kubernetes
> chore(docs): k8s troubleshooting improvements

- internal/cli/task_inspect.go
- internal/server/boltdbstate/task.go
- pkg/server/gen/server.pb.go
- pkg/server/gen/server.pb.gw.go
- pkg/server/gen/server.pb.json.go
- pkg/server/gen/server.swagger.json
- pkg/server/proto/server.proto
- pkg/server/singleprocess/service_job.go
- pkg/server/singleprocess/service_task.go
- pkg/server/singleprocess/service_task_test.go
- pkg/serverstate/serverstate.go
- pkg/serverstate/statetest/test_task.go
This commit includes the WatchTask job for the task state machine that
tracks the lifecycle of spawned on-demand runner tasks in a given
Waypoint job. The task state machine needs no changes, as `WatchTask`
simply watches the run task for log streaming. Given that, this commit
simply includes the watch task so it can be inspected via the CLI and
other operations that look at ODR tasks on a given job.
> internal/server: Include `WatchTask` in task state

- internal/server/boltdbstate/instance_exec.go
- internal/server/boltdbstate/instance_exec_test.go
- pkg/server/singleprocess/service_entrypoint.go
- pkg/server/singleprocess/service_entrypoint_test.go
- pkg/server/singleprocess/service_exec.go
- pkg/server/singleprocess/service_exec_test.go
- pkg/serverstate/instance.go
The bits within boltdb related to the instanceExec interface have been moved to serverstate, and then boltdb implements that interface.
> Decouple the server from the boltdb instanceExec functionality

- .changelog/3425.txt
- internal/cli/status.go
If an application has not been deployed, there will be no initial status report for it, and running `waypoint status -app=<name>` will panic. We fix that here by guarding on `nil`
> Fix panic in `waypoint status`

- internal/server/boltdbstate/job.go
- pkg/serverstate/statetest/test_job.go
Prior to this commit, when a job when to ack or complete its state, it
would return an error because it didn't account for the WatchJob id.
This commit fixes that by ignoring any WatchJob acks given it does not
affect the task state machine.
This was supposed to be included in https://github.com/hashicorp/waypoint/pull/3420 but was missed. This will fix any job ack job complete failures on `main`.
> internal/server: Ignore WatchTask on job ack and complete

- internal/cli/pipeline_run.go
- internal/cli/task_list.go
- internal/jobstream/stream.go
- website/content/commands/pipeline-run.mdx
This pull request introduces a CLI for manually executing pipeline runs via `waypoint pipeline run`. It currently streams the job stream sequentially in the order that the pipeline queued the job on Waypoint server.
Note, I haven't had a successful run of a `PipelineStep` operation yet, but I think the CLI is mostly there despite that.
This PR relies on https://github.com/hashicorp/waypoint/pull/3397 so that you can sync a pipeline config and run it.
> Feature/CLI: `waypoint pipeline run` CLI implementation

- pkg/serverhandler/handlertest/test_service_job.go
- pkg/serverhandler/handlertest/testing.go
This makes the job-related server tests consumable by external projects.
> Make job handler tests consumable

- .changelog/3465.txt
- internal/plugin/invoke.go
I had a typo in my task launcher config, and the result was that my plugin wasn't getting configured at all - it was running with the default config.
Now I get this useful error!
```
$ waypoint deploy
» Deploying example-nodejs-eks...
» Operation is queued waiting for job "01G5Q3MYHX95A4JS2BKMH24C4D". Waiting for runner assignment...
If you interrupt this command, the job will still run in the background.
! plugin.json:4,3-19: Extraneous JSON object property; No argument or block type
is named "service_accunt". Did you mean "service_account"?
```
> Show errors interpreting plugin config

- internal/server/boltdbstate/job.go
- pkg/server/singleprocess/service_job.go
- pkg/server/singleprocess/service_runner.go
- pkg/serverstate/serverstate.go
- pkg/serverstate/statetest/test_job.go
Prior to this commit, Waypoint server only expected queued jobs to wait
for 60 seconds before a runner accepted the job and began executing it
from its creation time. With the introduction of pipelines, this no
longer makes sense because a pipeline will queue all jobs in a pipeline
right away. This means downstream jobs could be waiting around to be
executing for a while, much longer than 1 minute. This is expected.
Given that, this commit updates the server behavior to set a jobs expiry
time to something much longer, 60 minutes, and then when the runner goes
to accept the job, we update the expiry time to the original expected
behavior of 60 seconds, because if the runner has accepted a job to work
on, it should run that job fairly quickly like the original intended
behavior.
> internal/server: Set expiry time on runner accept

- tools/tools.go
This is just upgrading the tools version for the upgrade that already happened https://github.com/hashicorp/waypoint/pull/3444. After making this change, running `make tools`, verifying the `mockery` version had upgraded, and running `make gen/server`, there were no generated changes to our pbs.
> update mockery version for make tools

- internal/cli/project_list.go
- website/content/commands/project-list.mdx
This commit adds a simple -json flag to output the project list as json
> internal/cli: Add a `-json` flag for project list

- internal/plugin/invoke.go
That's a pretty aggressive stance for the linter to take, I think.
> Remove trailing whitespace to pacify the linter

- internal/core/app_build.go
- internal/core/app_deploy.go
- internal/core/app_deploy_destroy.go
- internal/core/app_push.go
- internal/core/app_release.go
- internal/core/app_release_destroy.go
- internal/core/app_status_report.go
Due to an unrelated bug in the waypoint server, we were exiting early when creating status reports. The only error the client cound see was:
```
unknown error
```
Which is not helpful. This wrapps the errors in that flow to give more context as to what the client was attempting to do when it encountered the error.
> More error wrapping around ops

- pkg/serverstate/statetest/test_job.go
Removing the dupped test `TestJobComplete`. This was causing the test to get ran twice.
> rm dup TestJobComplete

- .github/CONTRIBUTING.md
The original `go get` command didn't work. The only command that worked to get go-bindata installed was the brew command. I figured it might be easier for others to not go thru the same install headache and just change it to one that works on the first try.
> docs: update go-bindata install cmd

- internal/runnerinstall/docker.go
* Fixes #3558
https://github.com/hashicorp/waypoint/blob/10585f14d3203a0a843fd726608031c42f4de3eb/internal/runnerinstall/docker.go#L43-L48
reference.FamiliarString does not check whether argument is nil as below.
Thus reference.ParseNormalizedNamed returns nil, err, then it must be checking error and return.
https://github.com/distribution/distribution/blob/8857a1948739db3520e2fb5211979aa62c3dd5da/reference/helpers.go#L27-L32
> Fix error check reference.ParseNomrmalizedNamed

- Makefile
This commit allows the caller of make to override the default server
platform for building waypoint server with an env var instead of it only
ever building linux/amd64.
Ideally, it would be nice to omit the `--platform` flag entirely if not set. Docker
buildx will use the host platform by default, but I couldn't find a graceful
way to do that with Make without extra if conditionals. I believe the original
hardcoded `amd64` flag was added for building `linux/amd64` on an `arm` machine
but to deploy to a remote `amd64` cluster.
> Makefile: Make architecture for Waypoint server build configurable

- .changelog/3522.txt
- pkg/config/funcs/doc.go
- pkg/config/funcs/stdlib.go
- website/content/partials/funcs.mdx
This adds the `replace` function from https://github.com/zclconf/go-cty
This achieves parity with https://www.terraform.io/language/functions/replace#replace-function
> chore: add hcl `replace`

- internal/cli/server_upgrade.go
- internal/installutil/adoption.go
- internal/installutil/aws/ecs.go
- internal/installutil/odr.go
- internal/runnerinstall/docker.go
- internal/runnerinstall/ecs.go
- internal/runnerinstall/nomad.go
- internal/runnerinstall/runnerinstall.go
- internal/serverinstall/ecs.go
This PR updates the `server upgrade` command to set the runner ID to `static`, which is the ID of the runner installed with the Waypoint server (using `waypoint install`) starting in 0.9. The ECS upgrade process requires this to be set in order to properly search the name of the ECS service to uninstall for the static runner as part of the upgrade.
A small refactor has also been done for querying services in ECS by creating a new helper function in `internal/installutil/aws`.
> Ecs upgrade runner

- .changelog/3580.txt
- internal/cli/destroy.go
- website/content/commands/destroy.mdx
Updating the `waypoint destroy -h` description, as previously it read only destroying resources for one app, when in fact it destroys all apps/resources in the workspace. See below:
```
$ waypoint up -w=test
$ kubectl get po
NAME                                                 READY   STATUS    RESTARTS   AGE
example-nodejs-metrics-sidecar-v7-6758bf9764-qvctl   2/2     Running   0          76s
test-example-nodejs-v7-54c9fb8448-mw4nw              1/1     Running   0          20s
waypoint-runner-0                                    1/1     Running   0          3h5m
waypoint-server-0                                    1/1     Running   0          3h5m
$ waypoint destroy -w=test -auto-approve
Performing operation locally
» Destroying releases for application …
```
> updating the waypoint destroy help description

- internal/cli/app_docs.go
- website/content/partials/components/configsourcer-terraform-cloud.mdx
- website/content/partials/components/configsourcer-vault.mdx
- website/content/partials/components/platform-azure-container-instance.mdx
- website/content/partials/components/platform-helm.mdx
- website/content/partials/components/platform-kubernetes-apply.mdx
- website/content/partials/components/platform-kubernetes.mdx
- website/content/partials/components/platform-nomad-jobspec-canary.mdx
- website/content/partials/components/platform-nomad-jobspec.mdx
- website/content/partials/components/platform-nomad.mdx
- website/content/partials/components/registry-aws-ecr.mdx
- website/content/partials/components/releasemanager-kubernetes.mdx
Environment variables are now displayed on the website if they exist for a given plugin parameter.
> EnvVars now represented on the website

- internal/serverinstall/k8s.go
This fixes a dropped `err` variable in `internal/serverinstall`.
> internal/serverintsall: fix dropped error

- .changelog/3546.txt
- internal/runnerinstall/nomad.go
- internal/serverinstall/nomad.go
- website/content/commands/install.mdx
- website/content/commands/runner-install.mdx
- website/content/commands/server-install.mdx
- website/content/commands/server-upgrade.mdx
This commit allows users to specify their own volume names within their
CSI provider. Some cases where the upstream provider is incompatible
with the default name because of limitations on their end make it so
that waypoint is unable to be used within those providers. In my testing
the DigitalOcean CSI provider doesn't handle capitalization of the
volume's name specifically within the runner ID. I suspect other 
providers may have different requirements which we should be able to 
work around since there is not an explicit requirement in the CSI spec 
for the names of volumes within a provider.
> core/install: Add --nomad-csi-volume-name flag to install

- .circleci/config.yml
- internal/runner/accept.go
- internal/server/boltdbstate/instance_test.go
- pkg/serverstate/statetest/test_instance.go
We already use the [next-gen](https://circleci.com/docs/circleci-images#next-gen-language-images) image in our release build, we must have just skipped updating the circleci config here.
This also updates golangci-lint to the latest version, and updated the syntax to continue intentionally ignoring the items that had comments explaining why they should be ignored.
> Update circleci config

- .changelog/3602.txt
- internal/cli/deployment_destroy.go
Update `waypoint deployment destroy` to continue with deleting the specified deployment from the database, while also warning the user that the resources created from the failed deployment may not be fully destroyed.
Addresses #533.
> Destroy Failed Deployments

- internal/server/boltdbstate/ondemand_runner.go
- pkg/server/singleprocess/service_ondemand_runner.go
- pkg/serverstate/serverstate.go
- pkg/serverstate/statetest/test_runner_ondemand.go
For better or worse, currently, we don't require that a user set an ODR config's name. If they call OnDemandRunnerConfigPut with no name OR id, it's OK, we'll generate an ID and use it as the name, then we return that ODR profile with the name and ID set.
The problem is, our state function wasn't returning an ODR profile with the name set - it was mutating the input, and relying on the server handler to know about it. If someone else were implementing a new state backend, the would have no way of knowing it was important to set the name on the input, and likely wouldn't. This bit us in HCP.
Now, state returns and explicit OnDemandRunnerConfig. A much more clear API contract.
> Explicitly returning ODR config when setting it in state

- .changelog/3657.txt
- internal/cli/base_init.go
- internal/cli/base_test.go
- internal/cli/testdata/invalid.hcl
- internal/cli/testdata/valid.hcl
Fixed a regression introduced in or around https://github.com/hashicorp/waypoint/pull/3605 when if a **local** `waypoint.hcl` file in the current directory had a validation error, the resulting error would not be converted to a validation result, and was then swallowed and never shown to the user. 
The result would be an empty reply from the CLI with no operation or messages:
```terminal
$> waypoint up
$> waypoint deployment list
$> waypoint deployment list -vvv
2022-08-08T17:02:19.550-0500 [INFO]  waypoint: waypoint version: full_string="v0.9.0-313-g1a48c27c4 (1a48c27c4+CHANGES)" version=v0.9.0-313-g1a48c27c4 prerelease="" metadata="" revision=1a48c27c4+CHANGES
2022-08-08T17:02:19.550-0500 [TRACE] waypoint: starting interrupt listener for context cancellation
2022-08-08T17:02:19.550-0500 …
```
> Base init load fix

- .circleci/config.yml
- test-e2e/docker_smoke_test.go
- test-e2e/ecs_smoke_test.go
- test-e2e/k8s_smoke_test.go
- test-e2e/nomad_smoke_test.go
- test-e2e/run-test.sh
- test-e2e/util.go
This fixes up a few things in our bash setup for e2e to run in CI, and adds support initially for the Docker platform.
Other platforms will be tracked in #3597. This base test case would have caught some of the edge cases we've missed in recent pre-release testing, so it's good to get this in as a starting point.
Since I've now set these to run only on `main` after an image is built off of `main`, look at [the second-to-last workflow](https://app.circleci.com/pipelines/github/hashicorp/waypoint/17223/workflows/b069f1e5-7c28-434f-b5aa-1a3c4d6f6b48) for the example run.
> CI: add e2e tests for Docker platform

- internal/ceb/server.go
- pkg/server/singleprocess/auth.go
- pkg/server/singleprocess/service.go
- pkg/server/singleprocess/service_job.go
The CEB was not perform the OAuth2 exchange, so that's fixed here.
Also, the hook allows HCP Waypoint to inject OAuth2 to a token before it's encoded.
> Add additional OAuth2 hooks and handling

- pkg/inlinekeepalive/client.go
- pkg/inlinekeepalive/server.go
Prior to this, if a stream were to exit very quickly, we would fail our call to the server's GetVersionInfo due to context cancelled, and log a warning. This is actually fine - we can just stop setting up the inlinekeepalive logic, because there's no stream anymore!
> Fixing inlinekeepalive early stream exit warning

- test-e2e/README.md
- test-e2e/cli_smoke.test.go
- test-e2e/docker_smoke_test.go
- test-e2e/ecs_smoke_test.go
- test-e2e/k8s_smoke_test.go
- test-e2e/nomad_smoke_test.go
- test-e2e/run-test.sh
Ignore the branch name; there was no bug with the tests -- they found a real bug!
But this does fix the fact that when it found the bug, we weren't seeing the error message from `stderr`. Plus updating the `CI` env var so that we don't see the spinner output `|\-/|\-/|\-/|\-/---` prefixing the test results.
As these only run on main; see [this run](https://app.circleci.com/pipelines/github/hashicorp/waypoint/17378/workflows/557a7efd-a414-4c1b-8d73-d765526f2a93/jobs/186773) for the results of this PR.
> e2e updates

- pkg/server/singleprocess/service_job.go
- pkg/serverhandler/handlertest/test_service_job.go
Currently, we queue the source job, but not the modified source job that contains the task information, and the taskSource (renamed sourceJob) variable is constructed, but never actually used.
Currently, if `job.Task` is called on the queued source job, Task related functions would silently exit, thinking the job is not a part of a Task.
> (potential) bug fix: properly queue ODR source job in a task

- .changelog/3688.txt
- internal/cli/server_upgrade.go
Prior to this PR we would show a hint about removing multiple runner profile defaults even if none existed. This was a bug, so this PR fixes it to only show the warning if more than 0 profiles were detected on upgrades.
Fixes https://github.com/hashicorp/waypoint/issues/3663
> cli: Only display hint text if more than 0 default profiles on upgrade

- pkg/server/singleprocess/service_runner.go
Missed this as part of https://github.com/hashicorp/waypoint/pull/3670, I think because this is a multi-line funciton call.
> Use the active key id for signing adopted runner tokens

- test-e2e/docker_smoke_test.go
If the CLI fails to execute during one of the end to end tests, we don't get too much information as to why we received an `err` and we fail early before printing `stdout` and `stderr`. This is a quick fix to include `stderr` if we get an `err` from executing the Waypoint CLI during the e2e tests.
Before this PR, we'd get:
>     docker_smoke_test.go:81: unexpected error deploying waypoint project: exit status 1
> test-e2e/docker: Include `stderr` output on CLI failures

- pkg/inlinekeepalive/client.go
That's normal apparently in our integration tests, and this is causing one of those tests to fail. Won't argue with it.
We don’t _need_ to warn log anything there. If we hit that condition, we’ll never send the inline keepalive messages. The log is nice in case someone starts reporting the the RST_STREAM errors again - we can ask for this log and figure out what the problem was. This isn’t worth more than one more round of whack a mole though. If we find another case like this, we should switch this to debug/trace log.
> inlinekeepalive client: ignore unavailable errors when determining compatibility

- internal/core/app_build.go
- internal/core/app_deploy.go
- internal/core/app_push.go
- internal/core/app_release.go
Prior to this commit, if any of the following plugins
build,deploy,artifactpush, or release did not properly return the
expected protobuf message, the internal core funcs would attempt to
convert the proto mesage without ensuring it was the proper expected
type. If this ever happened, the core func would panic and break
completely. This commit fixes that with some extra guarding to first
check if we can properly convert the message to our expected proto type,
and if not, return an internal error code rather than panicing.
> internal/core: Ensure proto message is proper type before return

- internal/config/validate.go
The config validation error was a little vague as to the fact that it
expects a non workspace scoped use stanza to exist as the default rather
than using a workspace for all `use` stanzas and using the "default"
workspace as the default use stanza.
> internal/config: Detail that default use expected to not be ws scoped

- .changelog/3702.txt
- internal/cli/runner_profile_set.go
- website/content/commands/runner-profile-set.mdx
This fixes a bug wherein if the default flag was not specified, waypoint would set default to false.
Bug behavior:
```
$ waypoint runner profile list
Runner profiles
NAME        | PLUGIN TYPE |                   OCI URL                   |               TARGET RUNNER               | DEFAULT  
---------------------+-------------+---------------------------------------------+-------------------------------------------+----------
docker             | docker      | hashicorp/waypoint-odr:latest               | *                                         | yes      
$ waypoint runner profile set -name=docker -plugin-type=docker -oci-url=hashicorp/waypoint-odr:latest
$ waypoint runner profile list
Runner profiles
NAME        | PLUGIN TYPE |                   OCI URL                   | …
```
> bug: do not reset runner profile default if flag not specified

- website/content/docs/waypoint-hcl/variables/input.mdx
Current state:
https://user-images.githubusercontent.com/34030/186507556-7c600445-47c2-41fe-9de3-e970c34ecffb.mp4
> website: fix link from input vars to “literal expressions”

- internal/runner/accept.go
Server responding with Unimpmlemented likely means that the server is running behind some kind of proxy, is failing health checks, and the proxy is responding with Unimplemented.
Also added some jitter to the sleep.
> Runner backoff if server 404s

- .changelog/3746.txt
- internal/cli/runner_inspect.go
- internal/cli/runner_install.go
- internal/cli/runner_list.go
- internal/runnerinstall/docker.go
- internal/runnerinstall/ecs.go
- internal/runnerinstall/k8s.go
- internal/runnerinstall/nomad.go
- internal/runnerinstall/runnerinstall.go
Allow extra arguments to be supplied to the `runner agent` command, run by the container installed with `runner install`.
Set the extra arguments on the k8s w/Helm, AWS ECS, Docker and Nomad runner installs.
> Runner install - extra arguments

- .changelog/3756.txt
- internal/server/boltdbstate/runner.go
Before this commit when Waypoint was determining whether or not to
remove a Runner from boltdb it was possible for runner to be nil at the
time we attempted to determine what type of Runner the Runner was. This
caused the server to panic as soon as the runner became unavailable.
This commit fixes the panic by avoiding the runner from being set to nil
by instead initializing an empty runner variable so that if a runner is
not found the type can still be determined and the runner cleaned up.
Fixes #3448
> core/runner: Fix server panic when runner is forgotten

- .changelog/3730.txt
- internal/runner/operation_release.go
> Prune old releases

- website/content/docs/runner/profiles.mdx
Seems this feature may have been planned but never implemented.
> website: remove section on `project apply -runner-profile=...`

- internal/cli/runner_install.go
- pkg/server/ptypes/ondemand_runner.go
This fixes a bug where if you tried a runner install with no targeting, it would attempt to target by labels but not include any actual labels, resulting in an invalid runner profile.
This fixes the cli, and also introduces a new validator on the server for the condition.
> Fix installing runner without specifying labels

- .changelog/3803.txt
- internal/cli/runner_profile_delete.go
- internal/server/boltdbstate/ondemand_runner.go
- pkg/serverhandler/handlertest/test_service_ondemand_runner.go
- website/content/commands/runner-profile-delete.mdx
Closes https://github.com/hashicorp/waypoint/issues/3481
This allows runner profiles to be deleted by name, not ID. We don't surface IDs to users, so it's not useful to delete them by ID.
I also found that we were able to create multiple runner profiles with the same name. This PR fixes that, adds a test around it, and still allows users to delete runner profiles by `id` (via a flag) if they find themselves with duplicate-named runners as an emergency backdoor.
> Delete runner profiles by name

- .changelog/3804.txt
- internal/serverinstall/nomad.go
`server upgrade`s for Nomad succeeded in upgrading the server, but failed to detect the runner because the old name for a runner's Nomad job, "waypoint-runner" was still being used. This PR corrects that by searching for a runner with the old name from before 0.9, "waypoint-runner", or the new name from after 0.9, "waypoint-static-runner".
> Fix Nomad upgrade of runner

- internal/config/pipeline.go
- internal/config/pipeline_test.go
- internal/config/stages.go
- internal/config/testdata/pipelines/pipeline_step_workspace.hcl
- internal/config/testdata/pipelines/pipeline_step_workspace_nested.hcl
This PR adds HCL parsing for workspace scoped pipeline steps, and builds off of https://github.com/hashicorp/waypoint/pull/3805. 
This PR is a draft and will remain until #3805 is merged into the target branch [f-workspace-scoped-steps](https://github.com/hashicorp/waypoint/tree/f-workspace-scoped-steps). Right now it targets the `f-workspace-scoped-steps-service` branch, until #3805 is merged
> Workspace scoped steps parsing: HCL parsing

- .github/dependabot.yml
Dependabot does a good job with our security and design system updates, I thought it might be worth giving it a spin with all ui dependencies.
> ui: allow dependabot to update all dependencies

- internal/core/app_deploy_destroy.go
- internal/core/app_release_destroy.go
The destroy plugin interface requires (Declared|Destroyed)ResourceResp now, but release was not updated to provide these values. This simply provides them but doesn't use them. This prevents calling a Release plugins Destroy method from failing to execute (which was failing because argmapper was looking for these values)
> Add values required for the updated Destroy interface

- Makefile
Preserve `bin` as the default make target in our Makefile
> maint: Ensure help is not default make target

- website/content/docs/internals/architecture.mdx
- website/content/docs/internals/execution.mdx
- website/content/docs/kubernetes/container-build.mdx
- website/content/docs/lifecycle/hooks.mdx
- website/content/docs/lifecycle/index.mdx
- website/content/docs/runner/adoption.mdx
- website/content/docs/runner/config.mdx
- website/content/docs/runner/index.mdx
- website/content/docs/runner/on-demand-runner.mdx
- website/content/docs/runner/profiles.mdx
- website/content/docs/runner/run-manual.mdx
- website/content/docs/troubleshooting.mdx
- website/content/docs/upgrading/index.mdx
- website/content/docs/waypoint-hcl/registry.mdx
- website/content/docs/waypoint-hcl/variables/dynamic.mdx
* Many various clarifications
* Clarify `remote runner` => `static runner`
* Remove many mentions of CLI runners being the most common setup
> Cleanup docs about runners

- internal/cli/project_inspect.go
- internal/client/runner.go
We introduced a Remote data source type, that goes along with Git and Local. The difference with Remote is that in indicates that only the Waypoint server knows how to perform the data source fetching.
The server already has the ability to translate a project with a Remote data source into job with a Git data source.
This updates the CLI to handle the presence of Remote properly (rather than assuming if it's not Git, it's local).
> Handle Remote datasources properly

- .changelog/3890.txt
- internal/cli/runner_install.go
- internal/cli/runner_profile_set.go
- internal/cli/server_upgrade.go
- internal/installutil/odr.go
- internal/runnerinstall/docker.go
- internal/runnerinstall/ecs.go
- internal/runnerinstall/k8s.go
- internal/runnerinstall/nomad.go
- internal/serverinstall/docker.go
- internal/serverinstall/k8s.go
- internal/serverinstall/nomad.go
- internal/serverinstall/serverinstall_test.go
- website/content/commands/runner-install.mdx
Currently, if you run `waypoint runner install -platform=kubernetes ...` but you *don't* specify a specific `-k8s-runner-image`, you get the ODR image for the static runner, which appears to be incapable of launching ODRs.
Reverts this change: https://github.com/hashicorp/waypoint/pull/3800/files#diff-33ed847d2fd425bf13e47f27760372eccaa88ed101ae6f05d13780095f486ab1L263
Only the on-demand runner needs its own image, because it needs kaniko for builds. If you use the ODR image for the static runner, you get this error when attempting to launch tasks (in the static runner logs)
```
2022-09-15T22:23:54.331Z [INFO]  waypoint.runner.agent.runner: launching plugin: job_id=01GD1M0P0N0PP6K9Q4FSFZ58PC job_op=*gen.Job_StartTask type=TaskLauncher path=/kaniko/waypoint args=["/kaniko/waypoint", …
```
> Not using the ODR image for the k8s static runner

- .changelog/3896.txt
- go.mod
- go.sum
Depends on https://github.com/hashicorp/waypoint-plugin-sdk/pull/74
This fixes and issue wherein if you attempt to create k8s resources and there's a problem, the ODR panics during the resource-manager rollback.
> Fixing destroying non-ecs resources

- .changelog/3894.txt
- internal/runnerinstall/k8s.go
- internal/runnerinstall/runnerinstall.go
Helm creates a service account, but we don't use it unless it's specified in the runner profile. Otherwise, you get an error like this:
```
$ wp up -workspace=dev
There are local changes that do not match the remote repository. By default,
Waypoint will perform this operation using a remote runner that will use the
remote repository’s git ref and not these local changes. For these changes
to be used for future operations, either commit and push, or run the operation
locally with the -local flag.
» Operation is queued waiting for job "01GD3CJWM5ABKYZ9YRH0VMCNCZ". Waiting for runner assignment...
If you interrupt this command, the job will still run in the background.
Performing operation on "kubernetes" with runner profile "kubernetes-DEV"
» Cloning data from Git
URL: …
```
> Setting the k8s runner install odr service account.

- .changelog/3922.txt
- internal/cli/runner_install.go
During `runner install`, if no existing runner profiles are detected, then we set the new runner profile as the default.
> Runner install default profile

- pkg/server/singleprocess/service_artifact.go
Wrap error returns in [hcerr.Externalize()](https://github.com/hashicorp/waypoint/blob/52e13de50ac6da2ffedb9c34f17f592c76de9fe1/pkg/server/hcerr/hcerr.go#L16-L29) to log more details correctly, and keep some details in logs as opposed to surfacing them to users.
> Initial set of externalized errors for artifact service

- pkg/server/singleprocess/service_ui_deploy.go
This picks up a dropped `err` variable in `pkg/server/singleprocess`.
> pkg/server/singleprocess: fix dropped error

- .changelog/3949.txt
- pkg/server/singleprocess/service_entrypoint.go
When a project is deleted, the EntrypointConfig could still access that project. This makes it such that the EntrypointConfig won't refresh config when the project has been deleted.
> Detected deleted projects in long-running EntrypointConfig

- pkg/server/singleprocess/service_build.go
Like https://github.com/hashicorp/waypoint/pull/3952, but for `singleprocess/service_auth_build.go`, which already had some externalization
> Externalize service_build

- .changelog/3995.txt
- internal/cli/runner_profile_set.go
Prior to this, assignment to the nil map would panic. E.x:
```
$ waypoint runner profile set -name=k8s -plugin-type=kubernetes -env-var=container=docker
❌ Updating runner profile "k8s" ("01GEMHHFSA3K6XXQR4Q0FVCKGJ")...
panic: assignment to entry in nil map
github.com/hashicorp/waypoint/internal/cli.(*RunnerProfileSetCommand).Run(0xc000246880, {0xc000311940, 0x6, 0xc})
/Users/izaaklauer/dev/waypoint/internal/cli/runner_profile_set.go:231 +0x15e5
github.com/mitchellh/cli.(*CLI).Run(0xc00056a280)
/Users/izaaklauer/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
github.com/hashicorp/waypoint/internal/cli.Main({0xc000198000?, 0x3813f60?, 0xc0000021a0?})
/Users/izaaklauer/dev/waypoint/internal/cli/main.go:127 +0x545
main.main() …
```
> Fix panic when setting odr env vars

- pkg/server/gen/server.pb.gw.go
- pkg/server/gen/server.swagger.json
- pkg/server/proto/gateway.yml
We missed it earlier. This also adds an endpoint for getting config by application. I'm not sure how we'd get globally scoped config vars, so I omitted that here - it's not a pressing need.
> Adding SetConfig to the grpc gateway config

- .changelog/4020.txt
- internal/cli/fmt.go
- website/content/commands/fmt.mdx
This PR is meant to handle #3817 and add check support to the fmt command. There's not much to it but in local testing with waypoint.hcl files it seemed to perform as expected, though it's kinda funny that the default config is generated needing formatting.
```
matt$ ./waypoint fmt -h
Usage: waypoint fmt [options] [FILE]
Rewrite a waypoint.hcl file to a canonical format.
This only works for HCL-formatted Waypoint configuration files. JSON-formatted
files do not work and will result in an error.
If FILE is not specified, then the current directory will be searched
for a "waypoint.hcl" file. If FILE is "-" then the content will be read
from stdin.
This command does not validate the waypoint.hcl configuration. This will
work for older and newer configuration formats.
Global Options: …
```
> add `-check` flag to fmt

- pkg/serverstate/statetest/test_job.go
Previously we were just checking that the `Commit` was successfully stored. This change adds assertions for `CommitMessage` and `Timestamp`.
> Increase coverage of `TestJobUpdateRef`

- .changelog/4063.txt
- internal/cli/runner_install.go
Resolves: https://github.com/hashicorp/waypoint/issues/3989
We shouldn't need to backport this change. 
~~@paladin-devops wondering if you can test this out on Nomad on your machine? Also down to pair. We tried bootstrapping a Nomad cluster with -dev, but it needed a host volume.~~ Update: done
> Remove automatic uppercasing of ids, so that future runner profiles will match

- .changelog/4100.txt
- internal/cli/job_list.go
- internal/server/boltdbstate/job.go
Previously, `waypoint job list -pipeline-name/id=` would display no results if no `-run` flag is supplied. 
Now output defaults to latest run.
> Job list filtered by pipelines displays latest run if none supplied

- .changelog/4099.txt
- internal/cli/deployment_create.go
- internal/cli/release_create.go
- internal/runner/operation_deploy.go
- internal/runner/operation_release.go
Prior to this commit, a status report operation was not auto-executed any time a deployment or release ran. This meant as Waypoint developers we had to be explicit when we wanted Waypoint to generate status reports. Given that our CLI runner auto-executes status reports on up, deploy, and release, it makes sense other systems that use these operations should also get status reports in an easy way. This commit updates the behavior of deploy and release to run a status report at the end of its execution so that we can get some simple checks after deploying or releasing.
Fixes #4072
> internal/runner: Run a status report on Deployments and Releases

- internal/datasource/git.go
This commit aligns the auth fields if used when displaying the git datasource information
> datasource/git: Align git fields for UX

- .changelog/4143.txt
- internal/cli/config_sync.go
- website/content/commands/config-sync.mdx
This PR adds the set of operation flags (-local, for example) to the config sync command.
One benefit that is gained here is that in the (albeit unlikely) scenario that a user does not have Waypoint configured to launch on-demand runners, but they do have a static runner, `waypoint config sync -local=false` can be used to still sync dynamic configuration variables. Such behavior is not possible on a local runner.
> Add operation flags to `config sync` command

- website/content/docs/runner/index.mdx
For merge into https://github.com/hashicorp/waypoint/pull/4162
- Manually made changes to merge main with stable-website
- Some content was deleted in https://github.com/hashicorp/waypoint/pull/3875, but that deleted content was later edited. If merged, this change would add the content from 3875 to what's live on https://developer.hashicorp.com/waypoint/docs/runner.
- I think it makes sense as-is, but let me know if you have feedback! We could also make another pass of this page in a separate PR if @evanphx prefers the deletion for clarity (wasn't sure why at first glance), following this cleanup of `main` / `stable-website`.
- Ran `make gen/website-mdx`
> Manual tweak to "Cleanup docs about runners."

- website/content/docs/runner/index.mdx
Saw in https://github.com/hashicorp/waypoint/pull/4163, but easier to do separately as should go to `main` and `stable-website`
> [website] Fix casing typo

- CHANGELOG.md
Should have added to `release/0.10.x` first for the release, but incorrectly added to `main` https://github.com/hashicorp/waypoint/pull/4177
> Add changelog to release/0.10.x

- website/content/docs/app-config/dynamic.mdx
Some previous auto-backports failed and this file had fallen behind main.
> Manual backport of `app-config/dynamic.mdx` onto `stable-website`

- website/content/docs/app-config/dynamic.mdx
Some previous auto-backports failed and this file had fallen behind main.
> Manual backport of `app-config/dynamic.mdx` onto `release/0.10.x`

- .changelog/4212.txt
- internal/cli/project_destroy.go
- internal/runner/accept.go
- website/content/commands/project-destroy.mdx
As the title suggests. :)
Previously, `waypoint project destroy` would ignore whatever arguments provided and attempt to destroy project in current directory. This enforces the use of the `-project` or `-p` flag regardless of where the command is called to resolve this bug, and for extra guardrails.
This PR also introduces the ability to delete projects created in the UI without a data source or `waypoint.hcl`.
> Modify `project destroy` to require `-p` flag and delete projects created in UI without data source

- .github/workflows/jira.yml
Things this does:
- checks for a `jira` label before doing anything
- checks for a ticket in Jira that matches the format this workflow will create new ticket titles with
- if the `jira` label was just added **and** a ticket does not already exist **and** the user who added the label is a `waypoint` team member, create a new ticket in the Waypoint project
- if the issue already had a `jira` label and was updated with a comment, was closed, or was reopened, update the activity/status of the corresponding Jira ticket
> Initial addition of GH->Jira workflow

- .changelog/4257.txt
- internal/clicontext/storage.go
On some operating systems (namely macOS), it's possible for something akin to a [`.DS_Store`](https://en.wikipedia.org/wiki/.DS_Store) file to exist in the directory where contexts are stored. If so, then when a user runs `waypoint context list` an internal method [`nameFromPath`](https://github.com/hashicorp/waypoint/blob/d4e1eddb95c8dad4300bad22ff5828258f9c77f8/internal/clicontext/storage.go#L242) returns an empty string for said file as it doesn't have a normal file extension. `context list` then tries to load a non-existing `/.hcl` file and errors like so:  
```
$ waypoint context list 
! Error loading context "": <nil>: Configuration file not found; The configuration file /Users/clint/Library/Preferences/waypoint/context/.hcl does not exist.
```
In this PR we simply filter out any …
> Bug fix: Filter out empty names from context list

- .github/workflows/failed-backport-check.yml
This workflow will check if a newly opened PR is a draft, and if it has "Backport" in the title. If both of those are true (which will both be true for failed backport PRs), it sends a small message to our team's Slack channel.
Just as a nudge, since this message will come within a minute or less of someone merging in a PR that had the `backport/*` label attached. I've updated the Slack workflow so it will now post to our team's channel, and added the necessary secrets to this repo.
> add slack notification for failed backports

- .changelog/4271.txt
- internal/cli/job_list.go
This pull request is my suggested feedback that came from the pull request https://github.com/hashicorp/waypoint/pull/4271
- I don't think we should print the page retrieval once complete. This is extra unrelated data that the user doesn't need to know and also breaks the `-json` flag
- Feedback on the changelog entry since it's user-facing, it's more targeted as to what this change is contributing.
- Extra check to prevent a panic in the case where the Waypoint API might return a malformed response that's missing the Pagination object
> Fixup: `waypoint job list` Fixups

- .changelog/4268.txt
- internal/cli/pipeline_run.go
Fixes https://github.com/hashicorp/waypoint/issues/3850 
Pipeline runs now show progress even on failed runs.
(Abridged output)
```
❯ waypoint-dev pipeline run tester
» Running pipeline "tester" for application "example-java"
✓ Pipeline "tester" has started running. Attempting to read job stream sequentially in order
✓ 2 steps detected, run sequence 16
» Performing operation locally
» Executing Step "build" in workspace: "default"
......
» Executing Step "deploy" in workspace: "default"
.....
! ✖ Pipeline "tester" (example-java) failed to complete. 1/2 steps successfully completed.
! 1 error occurred:
* rpc error: code = NotFound desc = failed to get latest artifact
```
> Pipeline run failures show run results

- .circleci/config.yml
- Dockerfile
- go.mod
- go.sum
- internal/assets/dev_assets.go
- internal/cli/base.go
- internal/cli/datagen/datagen.go
- internal/client/job.go
- internal/client/server.go
- internal/config/validate.go
- internal/core/app.go
- internal/pkg/ctystructure/object.go
- internal/pkg/gitdirty/gitdirty.go
- internal/pkg/httpfs/bindata_test.go
- internal/pkg/jsonpb/decode.go
- internal/pkg/jsonpb/encode.go
- internal/pkg/validationext/struct.go
- internal/plugin/discover.go
- internal/runner/runner.go
- internal/server/boltdbstate/db.go
- internal/serverinstall/k8s.go
- pkg/auth/oidc/claims.go
- pkg/protocolversion/current.go
- pkg/server/gen/server.pb.go
- pkg/server/logbuffer/logbuffer.go
- tools.Dockerfile
Most of these changes are the result of running the new go 1.19 formatter.
> Upgrading to go 1.19

- .github/workflows/failed-backport-check.yml
This workflow didn't run on the most recent failed backport. Upon inspection of the GitHub docs:
>Note: Workflows will not run on pull_request activity if the pull request has a merge conflict.
Switching to `pull_request_target` should fix this.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
> use pull_request_target instead of pull_request

- pkg/server/singleprocess/service_runner.go
We're getting vauge error messages now, and need to figure out where they're coming from.
> More detailed runner job stream logging

- internal/core/app_deploy_destroy.go
Prior to this commit, if a plugin returned a non-Deployment proto message, we would hard fail the entire operation. Considering that we are retreiving this message to print what resources were left around or destroyed, we should not hard fail on this and instead print the error to the user that we cannot tell them about these resources and move on. It also incldues the "type" that was returned.
> internal/core: Gracefully handle bad proto message from destroyments

- pkg/server/hcerr/doc.go
- pkg/server/hcerr/hcerr.go
- pkg/server/hcerr/hcerr_test.go
- pkg/server/hcerr/user_error.go
- pkg/server/singleprocess/service_job.go
Closes https://github.com/hashicorp/waypoint/issues/3994 (and recommend reading that for context)
Big thanks to @cicoyle for pairing on this! 
Will squash before merging
This adds a new error type in hcerr. If a function other than the top-level serivice handler (who calls hcerr.Externalize) wants to surface user-facing detail, they can use `hcerr.UserError*` functions to create a new error that contains user-safe detail. `hcerr.Externalize` will notice if the error stack has any UserErrors on it, and will gather those details and surface them to the user in the final error.
Running `waypoint pipeline run` on a project without a remote ref before:
```
$ waypoint pipeline run up
» Running pipeline "up" for application "web"
❌ Requesting to queue run of pipeline "up"...
» Performing …
```
> Adding mechanism for surfacing deep errors to users

- .changelog/4246.txt
- internal/runnerinstall/docker.go
- website/content/commands/runner-install.mdx
Add a socket-path flag to `waypoint runner install`, this allows to override the socket that will be bound using volume when creating the runner.
The issue is that docker socket may not be `/var/run/docker.sock` on the server that will host the runner, this would be in another place when running rootless docker for example.
This also helps greatly to start runners when using podman (ref: #3781).
> feat(cli): add socket-path flag to runner install

- pkg/server/singleprocess/service_project.go
I noticed a few spurious init jobs while testing. This won’t have a massive impact, but should make things a little tidier.
> core/server: only queue init ops for active projects

- .changelog/4382.txt
- internal/server/boltdbstate/config_source.go
This PR updates the Bolt DB implementation of config sources to "upgrade" a pre-v0.10.4 database record from the config_source table. Prior to v0.10.4, the unique identifier for each record in the table was the name of the plugin. This was changed in v0.10.4 with the addition of [scoped config sources](https://github.com/hashicorp/waypoint/pull/4191), and now the ID is a hashed value, whose hash structure is defined by the plugin name, scope, and workspace name.
This PR therefore deletes any "old" records, those whose ID is the name of any known config sourcer plugin, from Bolt DB, and creates new records with the ID correctly hashed. With this fix, users who had config sources prior to v0.10.3 may continue to interact with those config sources, whereas before this commit, they could not, …
> Scoped Config Sources Upgrade Fix

- website/content/commands/index.mdx
- website/content/plugins/index.mdx
Adds descriptions to the commands and plugins index pages, based on content from @tunzor
> website: add missing page descriptions

- .changelog/4424.txt
- internal/cli/pipeline_inspect.go
- internal/cli/pipeline_list.go
This commit fixes up the CLI to guard against empty PipelineRun Job slices. It also DRYs up some duplicated code in `pipeline inspect`.
Fixes https://github.com/hashicorp/waypoint/issues/4195
> CLI: Fix panics in `waypoint pipeline list` and `waypoint pipeline inspect`

- website/content/docs/use-cases/waypoint-gh-actions.mdx
Update a fully-qualified developer link to be relative. This ensures we can rely on client-side routing throughout the site.
Content checks before:
```
Status:  failure
content/docs/use-cases/waypoint-gh-actions.mdx
169:21-169:70  error  Unexpected fully-qualified link to `developer.hashicorp.com`: `https://developer.hashicorp.com/hcp/docs/waypoint`. Replace with a relative path internal to Developer. Possibly: `/hcp/docs/waypoint`.  ensure-valid-link-format
✖ 1 error
```
Content checks after:
```
Running content conformance checks...
Status:  success
```
> docs: convert link to be relative to developer

- .github/workflows/jira.yml
Per conversations on reorganizing our boards, we won't be using the `oss` label in Jira moving forward.
> jira - remove `oss` as label

- .github/workflows/jira.yml
Because the workflow runs each time any label is added, if someone adds multiple labels at once -- one of which is the `jira` label -- it creates a race condition.
For example, this could happen:
1. jira label added - workflow runs -> create new jira ticket with Task type
2. core label added - workflow runs -> check for duplicates with type `task`; finds the Task ticket; does not create new
3. bug label added - workflow runs -> check for duplicates with type `bug`; doesn't find a matching Bug ticket; create new jira ticket with Bug type
This PR fixes:
- removed the `issuetype` search filter to solve for the race condition that was ending up with duplicate issues.
Also bonus update:
- updated names of labels to match what we'll be using in Jira
> Jira - fix duplication bug

- .github/workflows/notify-integration-release-manual.yml
This adds a workflow file into `main` which is a requirement of GitHub actions. This will be used to the https://github.com/hashicorp/waypoint/tree/integrations branch
> chore: add integrations workflow file

- README.md
The README was referencing [HashiCorp Learn](https://learn.hashicorp.com/) & Docs on the Waypoint website directly, which have been replaced via [HashiCorp Developer](https://developer.hashicorp.com/).
Noticed this when making another small change in the Waypoint repo and wanted to get this up to date with the latest & greatest.
> Recontextualize README for HashiCorp Developer website

- internal/cli/install.go
- internal/cli/k8s_bootstrap.go
This picks up two dropped `err` variables in the `internal/cli` package.
> internal/cli: fix dropped errors

- pkg/server/hcerr/hcerr.go
- pkg/server/hcerr/user_error.go
- pkg/server/singleprocess/service_job.go
The code paths in service_job were passing a nil err in, which would cause an error to be generated on line 29.
This code fixes the issue in two ways:
1. The Error() function checks that err is nil before using it.
2. A new function is used to generate UserErrors without an underlaying error.
Lastly, we change UserError to be addressed as a pointer rather than a value because it's fairly large now.
> Fix crash created by passing a nil err

- website/content/docs/extending-waypoint/plugin-interfaces/platform-releaser.mdx
- website/data/docs-nav-data.json
This PR adds docs for the [`PlatformReleaser` interface of the plugin SDK](https://github.com/hashicorp/waypoint-plugin-sdk/blob/main/component/component.go#L119-L127)! 😄
> `PlatformReleaser` plugin interface docs

- website/content/docs/extending-waypoint/plugin-frameworks/index.mdx
Updated example to show `DestroyedResourcesResp` in use, and documented that the resource manager takes care of dependencies and an example of how to do that.
> Resource Manager Framework docs updates

- website/content/docs/extending-waypoint/plugin-interfaces/task-launcher.mdx
- website/data/docs-nav-data.json
This PR documents the [`TaskLauncher` interface of the plugin SDK](https://github.com/hashicorp/waypoint-plugin-sdk/blob/main/component/component.go#L54-L71)!
> `TaskLauncher` plugin interface documentation

- .changelog/4523.txt
- internal/server/boltdbstate/config_source.go
This PR updates how config source records are stored in BoltDB. Previously the key was a uint64 value converted to a byte slice - this is acceptable for BoltDB and reading from it; however, snapshots expect that the database values are UTF-8 encoded, which uint64 is not. This PR therefore converts the uint64 to a string BEFORE converting it to a byte slice, and that is the new "id" for a record in the config_source bucket.
Prior to this PR, `waypoint server snapshot` would fail, and the server would log an error indicating that an invalid UTF-8 character was written.
> Fix key for config sources in BoltDB

- internal/runner/operation_release.go
This fixes a dropped `err` variable in the `internal/runner` package.
> internal/runner: fix dropped error

- tools.Dockerfile
Adds line to install jq in tools.Dockerfile. `make docker/gen/server` was failing without this.
> Add jq install to tools.Dockerfile

- .github/workflows/gateway-yml-check.yml
- scripts/gateway-yml-check.sh
When adding new RPCs, we kept on forgetting to add them to `gateway.yml`[^1]. This patch adds a simple check to stop us making the same oversight in future.
Locally:
1. Delete an item from the `skip` list in `scripts/gateway-yml-check.sh` or delete an item from `pkg/server/proto/gateway.yml`
2. Run `./scripts/gateway-yml-check.yml`
3. Verify you see an error reporting that the RPC is missing
GitHub:
1. Make a branch of this PR
2. Delete an item from the `skip` list in `scripts/gateway-yml-check.sh` or delete an item from `pkg/server/proto/gateway.yml`
3. Commit and push
4. Open a PR for your branch
5. Verify the check fails
[^1]: `gateway.yml` declares gRPC->HTTP mappings for grpc-gateway
> Add `gateway.yml` check

- internal/runnerinstall/ecs.go
This fixes a dropped `err` variable in `internal/runnerinstall`. No changelog entry is required.
> internal/runnerinstall: fix dropped error

- .github/workflows/jira.yml
Remove no-longer-needed field from the Jira workflow.
> Jira sync fix

- .changelog/4596.txt
- pkg/server/singleprocess/service_runner.go
TLDR: calling all the job values 'job' introduced a goroutine-using-outer-scope-variable bug.
The source of all of this is ultimate a 3 year old bug:
https://github.com/hashicorp/waypoint/blob/9d34ba23599142a5b2efbdc7a79c7a4ce163f060/internal/server/singleprocess/service_runner.go#L586
That code used `=` instead of `:=`, which caused the goroutine to update the 'primary' job local variable used by everything else in the function. So WHEN (not if, as we'll see in a moment) ctx is canceled, job becomes nil, and any code further down in the function will see than nil DEPENDING on the goroutine scheduling order.
So, why would the context be canceled? The goroutine defined right after this does `defer cancel()` when the client disconnects. So due to the magic of goroutine scheduling, it's …
> Fix bug caused by trying to fix bug related to job "loss"

- .github/workflows/integration.yml
- Makefile
Output bath for `bin` make target was unnecessarily changed during migration to CRT.
> Revert output path for bin make target

- .github/workflows/integration.yml
- Makefile
This PR backports https://github.com/hashicorp/waypoint/pull/4636 which failed to auto-backport when I added the label. It's a fix for the `dev-build` integration step that was busted on main due to an accidental inclusion of a `dist/` directory in the process. 
Note that this PR is opened against the `release/0.11.x` branch, not `main`
> Backport #4636 to release/0.11.x

- internal/ceb/ssh/server_test.go
Using require.Eventually rather than an immediate assertion.
> Fix flakey ceb/ssh test

- .changelog/4660.txt
- pkg/server/ptypes/trigger.go
- pkg/serverhandler/handlertest/test_service_trigger.go
Prior to this commit, a user could create a bad HTTP path with a trigger name like `../bad`. This commit fixes that behavior by validating the given trigger name matches our expected valid path tokens.
With this fix:
```
brian@ubuntu:waypoint-tetris λ waypoint trigger create -name=../hello -op=build                                                                        ±[main]
! trigger: (name: name cannot contain '../'.).
```
> server: Ensure trigger names are valid paths

- pkg/server/gen/server.pb.gw.go
- pkg/server/gen/server.swagger.json
- pkg/server/proto/gateway.yml
Using dashes, like our other endpoints do!
Precedent:
```
/waypoint/2022-02-03/namespace/*/config-source
/waypoint/2022-02-03/namespace/*/runner/on-demand
```
NOTE: while this is a breaking api change, the templating feature is currently unreleased, so we don't need to worry about maintaining backwards compat.
> Standardizing templating routes

- .changelog/4672.txt
- internal/cli/runner_install.go
Prior to this commit, the runner install cli attempted to use the target var for the EnumVar platform. We make this an EnumVar because the flag package gives good validation when you pass a string that isn't one of the supported values. In practice however, the CLI only uses a single value, the first one in the slice. To avoid any panics, we simply use a string var once the flag package has parsed and actualized its values.
Fixes WAYP-1166
> cli/runner_install: Do not use cli slice for runner platform

- pkg/server/singleprocess/auth.go
Prior to this commit, the servers auth would not validate that a proper user was found for the given context prior to generating a token. We should not generate a token if no user was found, so this commit updates the login token func to return an unathenticated error if no user was found in the given context.
Fixes WAYP-1155
> server: Check that UserFromContext gets user before generating token

- .changelog/4675.txt
- internal/pkg/gitdirty/gitdirty.go
Prior to this commit, it was possible to craft a bad git remote and bypass our normalize func for remote git URLs. TrimLeft and TrimRight remote all occurances of the given pattern. The intention however is to only remove the first instance of `git@` and the last instance of `.git` from the given url. This commit fixes that by updating the string trimmers to use TrimPrefix and TrimSuffix, which will only remove the single instance of the pattern.
Fixes WAYP-1173
> internal: Cleanup remote URL trimming for git

- internal/cli/deployment_list.go
- internal/cli/release_list.go
- internal/cli/status.go
Prior to this commit, if a func calls shortImg with an improper string length, the whole CLI could panic given the shortImg func has a hardcoded expectation for the length of the passed in string. This commit fixes that by first validating the string length and then returning an error if the passed in string is not long enough to trim as expected.
Fixes WAYP-1151 (part 1)
> cli: Ensure that img string passed is proper length

- internal/version/version.go
After the CRT integration, the load-bearing version is kept in `version/VERSION`. However, this hard-coded value wasn't update to match at the time. Since it's the value used by local development builds (or builds off of main), we should keep it in-sync.
Since we don't have the runway to properly refactor. For the next release, we will update this value to match by hand.
A future patch will address this gap and use automation to maintain the value.
See also: hashicorp/waypoint#4583
> Update hardcoded version to 0.12.0

- .changelog/4699.txt
- internal/cli/runner_install.go
Currently we’re only assigning a value to `runnerPlatform` if `c.platform` is empty, leading to the following bug:
```
$ waypoint runner install -platform=docker
! Error installing runner into "": unsupported platform
```
This patch ensures we use the given value for `c.platform`.
```
$ waypoint runner install -platform=docker
✓ Finished connecting to: host.docker.internal:9701
```
> fix(cli): honor runner install -platform arg

- .changelog/4705.txt
- pkg/server/singleprocess/service_job.go
Previously, it was theoretically possible for multiple goroutines to write to `err` at the same time in GetJobStream, which would have caused a panic. 
Failing test output: https://gist.github.com/izaaklauer/ff8b42abc38db7785bf49bc3c9b45731
This PR modifies one of the goroutines in job stream handling to reassign the `err` variable when it uses it, avoiding a concurrent write
Run the `TestStream_single` test with the `-race` flag, and verify passing!
> Fixing a race condition in GetJobStream

- .changelog/4707.txt
- pkg/server/singleprocess/auth.go
- pkg/server/singleprocess/auth_test.go
This change in this PR prevents a runner token from being used to generate a new token for a runner other than the runner ID which is encoded in the runner token.
> Runner token ID check

- internal/server/boltdbstate/state_test.go
- pkg/server/gen/server.pb.go
- pkg/server/gen/server.swagger.json
- pkg/server/proto/server.proto
- pkg/serverstate/statetest/test_project.go
This adds state-layer tests for CRUD operations on the new template-related protobuf fields.
Note that the tests are added to a new "unimplemented" stanza in the state tests. Open-source waypoint does not implement templating. 
This also sneaks in a related protobuf change, updating the readme fields from `string` type to `bytes` on the `Project` and `ProjectTemplate`, as they represent the contents of whole files.
> Tests for template-related fields Projects

- pkg/serverstate/statetest/test_job.go
This removes a race condition where we're writing to `job` in one goroutine and reading in another during a test.
Race report: https://github.com/hashicorp/waypoint/actions/runs/4962203124/jobs/8879981994?pr=4708#step:8:387
> Remove race condition in job test

- pkg/server/ptypes/auth.go
- pkg/server/ptypes/deployment.go
- pkg/server/singleprocess/auth.go
Currently, we aren't validating that tokens that have passed the hmac test and proto unmarshalling are otherwise valid! 
This is mostly only relevant for testing - the server shouldn't ever generate a token that it doesn't think is valid - but this at least turns a category of bug from a panic to an appropriate server error.
This implements a basic ptypes validator for our protobuf tokens and calls it in appropriate spots.
> Validating tokens

- internal/pkg/graph/transitive.go
- internal/pkg/graph/transitive_test.go
- pkg/server/ptypes/pipeline.go
- pkg/server/ptypes/pipeline_ui.go
- pkg/server/ptypes/pipeline_ui_test.go
- pkg/server/singleprocess/service_ui_pipeline_run.go
- pkg/serverhandler/handlertest/test_service_ui_pipeline_run.go
This API will feed the pipeline run detail page.
Given a run of a valid pipeline ([something like this](https://github.com/jgwhite/waypoint-demos/blob/main/pipelines/waypoint.hcl#L30-L44)), running the command below should produce a big ol’ pile of JSON that looks something like [this gist](https://gist.github.com/jgwhite/b2c8d8b22ec10761633c4d8687fdf577).
```sh
./contrib/waypoint-grpc/waypoint-grpc.sh UI_GetPipelineRun '
{
"pipeline": {
"id": "01H06BBZH5BK3M7761PD8WP892"
},
"sequence": 2
}
'
```
1. Run a pipeline
2. From your waypoint source directory, run the following:
```sh
./contrib/waypoint-grpc/waypoint-grpc.sh UI_GetPipelineRun '
{
"pipeline": {
"id": "<YOUR-PIPELINE-ID>"
},
"sequence": <YOUR-RUN-SEQUENCE>
}
'
```
3. Verify that you see some lovely deeply-nested JSON
> Add `UI_GetPipelineRun`

- pkg/server/ptypes/pipeline_ui.go
Ideally, these wouldn’t be passed-in in the first place, but if they are then it’s better to ignore them.
> Ignore `{Start,Stop,Watch}Task` in `ptypes.UI_PipelineRunTreeFromJobs`

- .changelog/4712.txt
- internal/server/http_log.go
Add `forwardedIP` section to response so that `X-Forwarded-For` request header does not overwrite actual client IP, and validate it is a proper IP address.
> Do not allow forwarded IP to overwrite request source IP in logs

- internal/cli/task_inspect.go
Removed typo in line 300 of [task-inspect.go](https://github.com/hashicorp/waypoint/blob/main/internal/cli/task_inspect.go)
> Fixed typo: task-inspect.go

- pkg/server/gen/server.pb.gw.go
- pkg/server/gen/server.swagger.json
- pkg/server/proto/gateway.yml
Turns out this doesn’t work:
```yaml
- selector: hashicorp.waypoint.Waypoint.SetConfig
put: /project/config
body: "*"
- selector: hashicorp.waypoint.Waypoint.DeleteConfig
put: /project/config
body: "*"
```
Because both requests are for `PUT /project/config` and as a result grpc-gateway doesn’t know how to direct the request. protoc-grpc-gateway fails with the following:
```
go generate ./pkg/server
--swagger_out: must not set request body when http method is DELETE except allow_delete_body option is true: DeleteConfig
pkg/server/server.go:6: running "sh": exit status 1
make: *** [gen/server] Error 1
```
This change disambiguates the paths, but at the cost of a rather unintuitive path for the Delete rpcs. We can’t use `delete: /project/config` because grpc-gateway does not permit DELETE …
> api: fix duplicate gateway.yml paths

- .changelog/4792.txt
- internal/runnerinstall/ecs.go
This PR fixes an error which sometimes occurred during a `runner uninstall` for AWS ECS runners:
```terminal
❌ Uninstalling runner...
✓ Finding runner in ECS services...
! InvalidParameter: 1 validation error(s) found.
```
This occurred when no AWS EFS file systems were detected which had a tag `waypoint-runner`, with the value of the runner's ID assigned to it. This PR fixes that by properly looping through all paginated results of AWS EFS file systems to find a match, and later use that match correctly during deletion. If no matching file systems are found, `runner uninstall` will skip attempting to delete it.
There was also a possible resource leak with a `defer` inside of a `for` loop, which has been fixed.
Successful output looks like:
```shell
$ waypoint runner uninstall …
```
> AWS ECS Runner Uninstall Fix

- internal/server/boltdbstate/pipeline_run.go
- pkg/server/singleprocess/service_pipeline_run.go
- pkg/server/singleprocess/service_ui_pipeline_run.go
- pkg/serverstate/serverstate.go
- pkg/serverstate/statetest/test_pipeline_run.go
We’d like to be able to show runs newest-first in the UI.
Note that this PR only addresses sorting at the state layer. Longer term, we hope to [allow sorting options](https://github.com/hashicorp/waypoint/blob/WAYP-1541/pkg/server/proto/server.proto#L581) to be passed to `UI_ListPipelineRuns`, but that’s for another PR.
```sh
$ ./contrib/waypoint-grpc/waypoint-grpc.sh ListPipelineRuns '{ "pipeline": { "id": "01H2QGNVQ77KB4H67VJDESEATA" } }'
{
"pipelineRuns": [
{
"sequence": "1",
// ...
},
{
"sequence": "2",
// ...
},
{
"sequence": "3",
// ...
}
]
}
$ ./contrib/waypoint-grpc/waypoint-grpc.sh UI_ListPipelineRuns '{ "pipeline": { "id": "01H2QGNVQ77KB4H67VJDESEATA" } }'
{
"pipelineRunBundles": [
{
"pipelineRun": {
"sequence": "3",
// ... 
},
},
{
"pipelineRun": {
"sequence": "2",
// ...
},
}, …
```
> Add sorting to `serverstate.PipelineRunList`

- .changelog/4798.txt
- internal/runnerinstall/nomad.go
- website/content/commands/runner-install.mdx
The Nomad runner install configuration has fields for CPU and memory, but no flags for the user to set them - this PR adds those flags. This fix stems from a [discussion on HashiCorp Discuss](https://discuss.hashicorp.com/t/hcp-waypoint-unable-to-install-runner-on-nomad-client/54759/8), where a user installing a runner had insufficient resources on their Nomad client to run the runner, and I realized I could not suggest setting lower memory or CPU on the runner because there were no CLI flags to support it.
> Nomad runner install CPU and memory flags

- .changelog/4804.txt
- internal/serverinstall/nomad.go
- website/content/commands/install.mdx
- website/content/commands/server-install.mdx
- website/content/commands/server-upgrade.mdx
This enables users to configure the networking of the Waypoint server Nomad job to use a host network other than one named "default", for the gRPC and HTTP (UI) server ports. Closes #4751.
> install/nomad: Add host network config option.

- .changelog/4819.txt
- pkg/server/singleprocess/service_project.go
- pkg/serverhandler/handlertest/test_service_project.go
We have found it testing that it’s not _that_ easy to get remote-init working, and it’s not strictly necessary when all we want to do is register the applications for the project. This patch allows the server to perform the app-registration when a server-stored waypoint.hcl is present.
- Start and bootstrap a new waypoint server
- Write some HCL to disk (for example: https://github.com/hashicorp/waypoint-examples/blob/main/docker/static/waypoint.hcl)
- Run `waypoint project apply`, creating a new project with that waypoint.hcl stored server-side:
```
$ waypoint project apply -waypoint-hcl=`pwd`/waypoint.hcl foo
✓ Project "foo" updated
```
- Inspect the project, and notice that the app is registered! The server read them from the hcl.
```
$ waypoint project inspect -json foo
{
"name": …
```
> Automatically register apps when project has server-stored waypoint.hcl

- .changelog/4818.txt
- internal/runnerinstall/ecs.go
The `AddTags` permission is required when Waypoint manages the ALB resource for the AWS ECS plugin. If the user supplies their own ALB, this permission is not needed, because the plugin won't add a tag to indicate that it's managed by Waypoint.
> runnerinstall/aws-ecs: Add AddTags permission to ODR IAM policy.

- .changelog/4811.txt
- internal/serverinstall/ecs.go
Without this change, if the server isn't becoming healthy and the user wants to ctrl-c the install process, nothing will happen!
> Respecting context when installing the ECS server

- internal/server/boltdbstate/pipeline_run.go
This picks up three dropped `err` variables in `internal/server/boltdbstate`.
> internal/server/boltdbstate: fix dropped errors

- .changelog/4867.txt
- internal/cli/job_get_stream.go
- internal/cli/job_inspect.go
- internal/cli/job_list.go
- internal/cli/task_inspect.go
If a project has been destroyed, both the project and app are removed from the state. Jobs and Tasks still reference things by application ID and if null in the state are being set to nil in the gRPC response. 
In this PR we simply guard against nil values when outputting to the CLI. We assume a nil Project/Application means the project/application was deleted. If we use `""` instead then these columns will simply not show in the output, so we felt it should be explicit that those projects/applications have been deleted.
> Add guards against nil derefernce panics in job/task CLI commands

- .changelog/4873.txt
- internal/runnerinstall/ecs.go
Closes https://github.com/hashicorp/waypoint/issues/4872
Fixes a json syntax error in the ecs inline policy introduced in https://github.com/hashicorp/waypoint/pull/4840 by adding a close quote
Run a `waypoint install` against an AWS account without a role named `waypoint-runner`, and verify success:
```
$ ./waypoint runner install   -platform=ecs   -server-addr=api.hashicorp.cloud:443   -ecs-runner-image=hashicorp/waypoint -ecs-region=us-east-1 -ecs-cluster=waypoint
✓ Finished connecting to: api.hashicorp.cloud:443
✓ Runner "01H7BA4XNXE0Y4CEMEHKFQAK3R" installed successfully to ecs
✓ Runner profile "ecs-01H7BA4XNXE0Y4CEMEHKFQAK3R" created successfully.
✓ Networking setup
✓ EFS ready
✓ Found existing IAM role to use: waypoint-runner-execution-role
✓ Created IAM task role: waypoint-runner …
```
> Fix syntax error in ECS policy doc

- .github/workflows/build-waypoint-oss.yml
This updates the linux package license to BUSL-1.1.
This PR should be merged to main so that the change is included in the next minor release that is cut from main.
License changes are not required on release branches (ongoing patch releases of current minor releases).
> Update linux package license to BUSL-1.1
